### ISSUE TITLE
using ycsb test hbase 

### ISSUE THREAD

**Issue by 2victoria** [brianfrankcooper/YCSB#1013]
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.util.ClassSize
        at org.apache.hadoop.hbase.ipc.IPCUtil.<init>(IPCUtil.java:74)
        at org.apache.hadoop.hbase.ipc.AbstractRpcClient.<init>(AbstractRpcClient.java:91)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl.<init>(RpcClientImpl.java:1082)
        at org.apache.hadoop.hbase.ipc.RpcClientImpl.<init>(RpcClientImpl.java:1108)
HOW TO SOLVE?

**Comment by busbey** [comment]
how are you running YCSB? what version are you running? Are you starting with a release convenience binary? (e.g. https://github.com/brianfrankcooper/YCSB/releases/download/0.12.0/ycsb-hbase10-binding-0.12.0.tar.gz)

**Comment by busbey** [comment]
closing as stale. if you're still having issues please reopen and address the questions above.
