### ISSUE TITLE
Cassandra1.06:InvalidRequestException(why:Keyspace user table doesn't exist)

### ISSUE THREAD

**Issue by cornelius80** [brianfrankcooper/YCSB#103]
Hi m1ch1 and everyone,

I am trying out ycsb with mongdodb and have managed to benchmark it with the help of my own perl script.

However, now that I am benchmarking cassandra v1.0.6 in that same perl script, I encountered this error with not much of a help.

Loading workload...
Starting test.
 0 sec: 0 operations; 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
InvalidRequestException(why:Keyspace usertable does not exist)
	at org.apache.cassandra.thrift.Cassandra$set_keyspace_result.read(Cassandra.java:4816)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_set_keyspace(Cassandra.java:451)
	at org.apache.cassandra.thrift.Cassandra$Client.set_keyspace(Cassandra.java:426)
	at com.yahoo.ycsb.db.CassandraClient10.insert(CassandraClient10.java:437)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:145)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:461)
	at com.yahoo.ycsb.ClientThread.run(Client.java:269)
 0 sec: 0 operations; [INSERT AverageLatency(us)=25297] 

any ideas, please?

Thank you.

Kind Regards,
Cornelius

**Comment by busbey** [comment]
closing as stale. @cornelius80 if you are still having problems please try with the current README and reopen.

@namaggarwal we currently have CQL support added, if that's not sufficient to work against a cassandra 2.x cluster please open a new issue. (not that we still have a large number of outstanding cassandra changes to merge in)
