### ISSUE TITLE
java.lang.NullPointerException when starting YCSB with high thread count

### ISSUE THREAD

**Issue by twblamer** [brianfrankcooper/YCSB#1042]
I've seen this as an intermittent issue running YCSB with high thread counts. The common theme is a NullPointerException in com.yahoo.ycsb.measurements.Measurements, and/or somewhere in the HdrHistogram stack immediately at the start of a load or run. This causes YCSB to terminate.

See the [attached log file](https://github.com/brianfrankcooper/YCSB/files/1337860/ycsb_nullptrexception.log). The stack trace is typical, but I have examples of other stack traces that originate in different parts of HdrHistogram. They frequently involve the Histogram constructor, but not always.

It doesn't seem to be a binding specific issue. It seems to happen more frequently on some systems than others. It is seen on our more powerful hosts with 56 cores (w/hyperthreading), not with our weaker hosts. It feels like a race condition causing something to hit an uninitialized object, but I haven't had the time to really dive in to the code.

Using YCSB 0.12.0. Environment is Fedora 25 x86_64, JDK package is java-1.8.0-openjdk-1.8.0.111-1.b16.fc25.x86_64.

```
Command line: -db com.yahoo.ycsb.db.MongoDbClient -s -threads 96 -P workloads/workloada -p mongodb.url=mongodb://node1.example.com:27017/node1_0?w=1 -p fieldcount=10 -p recordcount=25000000 -p fieldlength=100 -p hdrhistogram.percentiles=70,80,90,95,99,99.9,99.99 -p operationcount=10000000 -p mongodb.upsert=true -p exporter=com.yahoo.ycsb.measurements.exporter.JSONArrayMeasurementsExporter -p exportfile=/tmp/ioutil/ycsb/ycsb_client_0.json -t
Loading workload...
Starting test.
2017-09-25 14:21:26:076 0 sec: 0 operations; est completion in 0 seconds 
...
java.lang.NullPointerException
    at java.lang.StrictMath.floorOrCeil(StrictMath.java:403)
    at java.lang.StrictMath.ceil(StrictMath.java:340)
    at java.lang.Math.ceil(Math.java:423)
    at org.HdrHistogram.AbstractHistogram.init(AbstractHistogram.java:268)
    at org.HdrHistogram.AbstractHistogram.<init>(AbstractHistogram.java:231)
    at org.HdrHistogram.Histogram.<init>(Histogram.java:225)
    at org.HdrHistogram.ConcurrentHistogram.<init>(ConcurrentHistogram.java:457)
    at org.HdrHistogram.ConcurrentHistogram.<init>(ConcurrentHistogram.java:421)
    at org.HdrHistogram.Recorder$InternalConcurrentHistogram.<init>(Recorder.java:261)
    at org.HdrHistogram.Recorder$InternalConcurrentHistogram.<init>(Recorder.java:257)
    at org.HdrHistogram.Recorder.<init>(Recorder.java:46)
    at com.yahoo.ycsb.measurements.OneMeasurementHdrHistogram.<init>(OneMeasurementHdrHistogram.java:85)
    at com.yahoo.ycsb.measurements.Measurements.constructOneMeasurement(Measurements.java:146)
    at com.yahoo.ycsb.measurements.Measurements.getOpMeasurement(Measurements.java:243)
    at com.yahoo.ycsb.measurements.Measurements.measure(Measurements.java:205)
    at com.yahoo.ycsb.DBWrapper.measure(DBWrapper.java:195)
    at com.yahoo.ycsb.DBWrapper.update(DBWrapper.java:218)
    at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionUpdate(CoreWorkload.java:801)
    at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:634)
    at com.yahoo.ycsb.ClientThread.run(Client.java:458)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by busbey** [comment]
thanks for the report. If the origination points all look like they're in HdrHistogram, do you have an issue filed with that project that we could attach here to track?

**Comment by twblamer** [comment]
I did not go that route yet, I was wondering if any other YCSB users saw the same thing.

It looks like updating the openjdk package on our machines may have helped, but I want to sit on this for a while and wait to see if it crops up again.

**Comment by busbey** [comment]
any update @twblamer ?

**Comment by twblamer** [comment]
No update. I'm not sure if it's still happening in our environment...if it is, it's not very often.

I'm just going to close this. I'll open a new issue if I find a root cause or consistent repro steps.
