### ISSUE TITLE
Connection YCSB in a couchbase 5 cluster 

### ISSUE THREAD

**Issue by tudorantohi** [brianfrankcooper/YCSB#1062]
Hi there and thanks everybody for reading me, 

I am trying to build a connection in a normal Couchbase 5.0 cluster. 

The command line I used after successfully building the repository with Maven is:

[root@ip-10-100-101-178 YCSB]# bin/ycsb load couchbase2 -s -P workloads/workloada -p couchbase.host=10.100.101.117 -p couchbase.password=XYXYXY -p couchbase.bucket=beer-sample -p couchbase.user=Administrator

And the answer is complaining about password but it does not ask me for an username. 

WARNING: Unknown ResponseStatus with Protocol HTTP: 401
com.yahoo.ycsb.DBException: Could not connect to Couchbase Bucket.
        at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:208)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
        at com.yahoo.ycsb.ClientThread.run(Client.java:423)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.couchbase.client.java.error.InvalidPasswordException: Passwords for bucket "beer-sample" do not match.
        at com.couchbase.client.java.CouchbaseAsyncCluster$OpenBucketErrorHandler.call(CouchbaseAsyncCluster.java:474)
        at com.couchbase.client.java.CouchbaseAsyncCluster$OpenBucketErrorHandler.call(CouchbaseAsyncCluster.java:457)
        at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:139)
        at rx.internal.operators.OperatorMap$MapSubscriber.onError(OperatorMap.java:85)
        at rx.observers.Subscribers$5.onError(Subscribers.java:224)
        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:264)
        at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:207)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more

**Comment by pavel-paulau** [comment]
Couchbase Server 5.0 requires RBAC users for authentication. You can find more information in the official documentation:

https://developer.couchbase.com/documentation/server/current/security/concepts-rba-for-apps.html

Please note, "couchbase.user" property is not implemented in YCSB. See:

https://github.com/brianfrankcooper/YCSB/blob/master/couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java#L78

If you want to use YCSB then you need to create a user that matches the bucket name. In your particular case you need to create user "beer-sample" with password "XYXYXY". Don't forget to grant the required privileges.

**Comment by pavel-paulau** [comment]
Those timeout exceptions have nothing to do with the authentication issue reported by @tudorantohi .

My recommendation is to collect the database logs and report a bug:

https://developer.couchbase.com/documentation/server/current/cli/cbcollect-info-tool.html

https://issues.couchbase.com/secure/Dashboard.jspa

**Comment by dsukhoroslov** [comment]
@pavel-paulau yes, you're right. I mixed this issue with the #955

**Comment by busbey** [comment]
@tudorantohi did @pavel-paulau's pointers help solve your issue?

**Comment by busbey** [comment]
closing as stale. please reopen if you're still having issues.
