### ISSUE TITLE
Couchbase error inserting 

### ISSUE THREAD

**Issue by ajimenezu** [brianfrankcooper/YCSB#1065]
Hi, I'm trying to load a workload but I had an error and I don't know how to fixed.
The command line I use to load is: 

bin/ycsb load couchbase2 -s -P workloads/workloadr100

and the error is this 

ADVERTENCIA: [null][KeyValueEndpoint]: Authentication Failure.
nov 22, 2017 11:07:58 AM com.couchbase.client.core.config.DefaultConfigurationProvider$8 call
INFORMACIÓN: Opened bucket default
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2017-11-22 11:08:07:570 10 sec: 0 operations; est completion in 106751991167300 days 15 hours 
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at com.couchbase.client.java.util.Blocking.blockForSingle(Blocking.java:71)
	at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.waitForMutationResponse(Couchbase2Client.java:733)
	at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.insertKv(Couchbase2Client.java:419)
	at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.insert(Couchbase2Client.java:393)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:221)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:562)
	at com.yahoo.ycsb.ClientThread.run(Client.java:467)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException
	... 8 more
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0

**Comment by busbey** [comment]
That looks like a simple auth failure. Does the cli for poking at Couchbase work?

**Comment by agyryk** [comment]
What version of Couchbase do you use? If prior 5.0 you probably have a password for your bucket. Try adding these two parameters:
_bin/ycsb load couchbase2 -s -P workloads/workloadr100 -p couchbase.bucket=default -p couchbase.password=\<bucket password>_

The 5.0 introduces few new authentication features. The best way to run YCSB w/o modifying its code is to create a user for your bucket with the same name as the bucket name. The command will stay the same:
_bin/ycsb load couchbase2 -s -P workloads/workloadr100 -p couchbase.bucket=default -p couchbase.password=\<bucket user password>_

You can read more about Couchbase 5.0 Authentication here: https://blog.couchbase.com/new-sdk-authentication/

**Comment by busbey** [comment]
@ajimenezu did this solve your issue?

**Comment by ajimenezu** [comment]
@busbey yeah, that solve the issue! thanks!

**Comment by ksamir18** [comment]
tumcha aaichi gaand .....yed zavnyano
