### ISSUE TITLE
YCSB for Cassandra Multinode Cluster

### ISSUE THREAD

**Issue by sririzkiwulandari** [brianfrankcooper/YCSB#1076]
Hello, im Wulan.
Im a beginner in NoSQL Cassandra, i have a cassandra cluster that consist of 4 nodes, when i used YCSB for benchmarking in Cassandra with this command:
./bin/ycsb load cassandra-cql -p hosts=172.16.34.22,172.16.34.21,172.16.34.20,172.16.34.10 -P workloads/workloada

i got this output:
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:cassandra-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
/usr/lib/jvm/java-8-oracle/bin/java -cp /home/wulan01/YCSB/cassandra/conf:/home/wulan01/YCSB/cassandra/target/cassandra-binding-0.14.0-SNAPSHOT.jar:/home/wulan01/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/wulan01/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/wulan01/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar:/home/wulan01/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/wulan01/.m2/repository/com/datastax/cassandra/cassandra-driver-core/3.0.0/cassandra-driver-core-3.0.0.jar:/home/wulan01/.m2/repository/io/netty/netty-handler/4.0.33.Final/netty-handler-4.0.33.Final.jar:/home/wulan01/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/wulan01/YCSB/core/target/core-0.14.0-SNAPSHOT.jar:/home/wulan01/.m2/repository/com/google/guava/guava/17.0/guava-17.0.jar:/home/wulan01/.m2/repository/io/netty/netty-transport/4.0.33.Final/netty-transport-4.0.33.Final.jar:/home/wulan01/.m2/repository/io/netty/netty-codec/4.0.33.Final/netty-codec-4.0.33.Final.jar:/home/wulan01/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar:/home/wulan01/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/wulan01/.m2/repository/io/netty/netty-buffer/4.0.33.Final/netty-buffer-4.0.33.Final.jar:/home/wulan01/.m2/repository/org/slf4j/slf4j-log4j12/1.6.4/slf4j-log4j12-1.6.4.jar:/home/wulan01/.m2/repository/io/netty/netty-common/4.0.33.Final/netty-common-4.0.33.Final.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=172.16.34.22,172.16.34.21,172.16.34.20,172.16.34.10 -P workloads/workloada -load
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=172.16.34.22,172.16.34.21,172.16.34.20,172.16.34.10 -P workloads/workloada -loadYCSB Client 0.14.0-SNAPSHOT

Loading workload...
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
Connected to cluster: Test Cluster
Datacenter: datacenter1; Host: /172.16.34.20; Rack: rack1
Datacenter: datacenter1; Host: /172.16.34.21; Rack: rack1
Datacenter: datacenter1; Host: /172.16.34.22; Rack: rack1
Datacenter: datacenter1; Host: /172.16.34.10; Rack: rack1
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
com.datastax.driver.core.exceptions.InvalidQueryException: Unknown identifier y_id
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:63)
	at com.yahoo.ycsb.db.CassandraCQLClient.insert(CassandraCQLClient.java:451)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:221)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:562)
	at com.yahoo.ycsb.ClientThread.run(Client.java:467)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Unknown identifier y_id
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:136)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:184)
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:798)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:617)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1005)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:928)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	... 1 more
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
[OVERALL], RunTime(ms), 2995
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 2
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 9
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.3005008347245409
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 2
[TOTAL_GC_TIME], Time(ms), 9
[TOTAL_GC_TIME_%], Time(%), 0.3005008347245409
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 2214912.0
[CLEANUP], MinLatency(us), 2213888
[CLEANUP], MaxLatency(us), 2215935
[CLEANUP], 95thPercentileLatency(us), 2215935
[CLEANUP], 99thPercentileLatency(us), 2215935
[CLEANUP], 2215935, 1.0
[INSERT], Operations, 0
[INSERT], AverageLatency(us), NaN
[INSERT], MinLatency(us), 9223372036854775807
[INSERT], MaxLatency(us), 0
[INSERT], 95thPercentileLatency(us), 0
[INSERT], 99thPercentileLatency(us), 0
[INSERT], Return=ERROR, 1
[INSERT-FAILED], Operations, 1
[INSERT-FAILED], AverageLatency(us), 43760.0
[INSERT-FAILED], MinLatency(us), 43744
[INSERT-FAILED], MaxLatency(us), 43775
[INSERT-FAILED], 95thPercentileLatency(us), 43775
[INSERT-FAILED], 99thPercentileLatency(us), 43775
[INSERT-FAILED], 43775, 1.0

please help to solve this problem, thankyou so much!!

**Comment by dbjoa** [comment]
@sririzkiwulandari ,
Could you show the result of the cql, "desc ycsb.usertable;" in your cqlsh ?

**Comment by busbey** [comment]
@sririzkiwulandari  any luck trying @dbjoa's suggestion?
