### ISSUE TITLE
Cannot execute YCSB

### ISSUE THREAD

**Issue by ChristianNavolskyi** [brianfrankcooper/YCSB#1105]
I have cloned the repository and packaged everything via

`mvn clean package`

but when I try to run it by

`bin/ycsb.sh load basic -P workloads/workloada`

it prints

> /usr/bin/java  -classpath /Users/navolskyi/Desktop/YCSB/conf:/Users/navolskyi/Desktop/YCSB/core/target/core-0.14.0-SNAPSHOT.jar:/Users/navolskyi/Desktop/YCSB/core/target/core-0.14.0-SNAPSHOT.jar com.yahoo.ycsb.Client -load -db com.yahoo.ycsb.BasicDB -P workloads/workloada
> Command line: -load -db com.yahoo.ycsb.BasicDB -P workloads/workloadaYCSB Client 0.14.0-SNAPSHOT
> 
> Loading workload...
> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/htrace/core/Tracer$Builder
>         at com.yahoo.ycsb.Client.getTracer(Client.java:902)
>         at com.yahoo.ycsb.Client.main(Client.java:751)
> Caused by: java.lang.ClassNotFoundException: org.apache.htrace.core.Tracer$Builder
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         ... 2 more
>  (might take a few minutes for large data sets)

I am using macOS version 10.13.3 and Maven version 3.5.0.

As far as I can tell the shell script does not include the needed dependencies in the classpath.

**Comment by busbey** [comment]
This sounds like #908. Could you try downloading and using our last release's binaries?

**Comment by busbey** [comment]
In the event that you need some functionality that isn't in a release yet, could you try using the python script `bin/ycsb`?

**Comment by ChristianNavolskyi** [comment]
>This sounds like #908. Could you try downloading and using our last release's binaries?

When I run the benchmark from the binary everything works as expected.

>In the event that you need some functionality that isn't in a release yet, could you try using the python script bin/ycsb?

Running it with the python script works within my IDE, strange that the other scripts don't work.

When I build the source by myself with `mvn clean package` extract it and run `./bin/ycsb.sh load basic -P workloads/workloada` it also works.

I am using IntelliJ and I can run the benchmark with a binding by setting "Use classpath of module" to the module of the binding.

**Comment by ChristianNavolskyi** [comment]
I think the problem is, that the dependencies from the core module are not included in the build `core.jar`.
The `ycsb.sh` script only uses the `target/dependency` folder for the bindings.

So eighter the dependencies should be built, packaged in the target folder and the script looks it up there or the dependencies should be included in the `core.jar`.

**Comment by busbey** [comment]
Thanks! I think that confirms that this is the same issue as #908. That PR is just waiting on a test on the windows side for merge.

**Comment by busbey** [comment]
#908 has merged now. would you mind trying again?
