### ISSUE TITLE
HBase client with 1.1 has contention on client side due to shared connections

### ISSUE THREAD

**Issue by ramkrish86** [brianfrankcooper/YCSB#1108]
While testing YCSB hbase-1.2 based client against a 2.0 server found that the client was not performing as expected because of a contention on the client side due to sharing of connections by all the worker threads.
` "Thread-87" #108 prio=5 os_prio=0 tid=0x00007efd484d8000 nid=0x451ba waiting for monitor entry [0x00007efab2dec000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.writeRequest(RpcClientImpl.java:913)
	- waiting to lock <0x000000008024c5f0> (a java.lang.Object)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.tracedWriteRequest(RpcClientImpl.java:873)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1241)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:227)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:336)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:34070)
	at org.apache.hadoop.hbase.client.HTable$3.call(HTable.java:857)
	at org.apache.hadoop.hbase.client.HTable$3.call(HTable.java:848)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:136)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:865)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:831)
`

Ideally the same issue should be there when we test against a 1.1 server also. It is better to either provide an option to go with individual connections as in PerformanceEvaluation tool provided in HBase. But that could be costly one if there are meta looks up on merge/splits. If so we need to provide a connection pool atleast. 
@busbey - You have any opinion/suggestion here?

**Comment by ramkrish86** [comment]
That is perfect. In an ideal case they may even do connection pooling. Probably in such a case the problem here may even not be visible.
My point was that in case of 2.0 even with shared connection we don see the contention in the hbase-client code.  So if they really want to really get max throughput if there is a config available then it may be useful. Say for the read only workload tests.

**Comment by saintstack** [comment]
What you thinking @ramkrish86  ? An option so a Connection per thread?

Looking at the client (1.2 against 2.0 workloadc) I see a few BLOCKED here:
```

"Thread-113" #134 prio=5 os_prio=0 tid=0x00007f4dfc5aa800 nid=0x4d41 in Object.wait() [0x00007f4d8a2e1000]
   java.lang.Thread.State: BLOCKED (on object monitor)
  at java.lang.Object.wait(Native Method)
  at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1256)
  - locked <0x0000000724bcbf50> (a org.apache.hadoop.hbase.ipc.Call)
  at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:227)
  at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:336)
  at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:34070)
  at org.apache.hadoop.hbase.client.HTable$3.call(HTable.java:857)
  at org.apache.hadoop.hbase.client.HTable$3.call(HTable.java:848)
  at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:136)
  at org.apache.hadoop.hbase.client.HTable.get(HTable.java:865)
  at org.apache.hadoop.hbase.client.HTable.get(HTable.java:831)
  at com.yahoo.ycsb.db.HBaseClient10.read(HBaseClient10.java:272)
  at com.yahoo.ycsb.DBWrapper.read(DBWrapper.java:135)
  at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionRead(CoreWorkload.java:683)
  at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:605)
  at com.yahoo.ycsb.ClientThread.run(Client.java:454)
  at java.lang.Thread.run(Thread.java:748)
```
Our stack traces are different (I seem to have a lock higher up in the stack). I'm on tip of YCSB. What you on sir?

I played around with this patch

```
diff --git a/hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java b/hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
index 12b13d9..1ad7264 100644
--- a/hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
+++ b/hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
@@ -81,7 +81,7 @@ public class HBaseClient10 extends com.yahoo.ycsb.DB {
    * with a 'lock' object.
    * @See #CONNECTION_LOCK.
    */
-  private static Connection connection = null;
+  private Connection connection = null;

   // Depending on the value of clientSideBuffering, either bufferedMutator
   // (clientSideBuffering) or currentTable (!clientSideBuffering) will be used.
@@ -149,6 +149,7 @@ public class HBaseClient10 extends com.yahoo.ycsb.DB {
       synchronized (THREAD_COUNT) {
         if (connection == null) {
           // Initialize if not set up already.
+          System.out.println("CREATING CONNECTION FOR " + this);
           connection = ConnectionFactory.createConnection(config);

           // Terminate right now if table does not exist, since the client
```

I didn't see much difference. Do you? The picture below starts up w/ default single connection and 128 clients (threads)... Then next two humps are 16 clients. The fourth hump is 16 clients and a connection each; i.e. 16 Connections. Seems a bit slower?  Next I do two 128 clients/threads and 128 connections. Again they seem a little down from the first peak which was one connection.  The mess on the right is 48 clients/threads/connections. This matches how many handlers there are on the server. This seems best perf. At extreme right I put up 48 threads over one Connection... ... Its about the same, maybe a bit better....

This is rough testing. The numbers are down because something wrong w/ the hbase2 metric for reads. Need to fix.
 
![reads](https://user-images.githubusercontent.com/48398/37867862-b3c7af1a-2f5b-11e8-8e38-719828794b0d.png)

**Comment by ramkrish86** [comment]
Even when I try PE with hbase-1.1 with oneCon=true, there is a difference in the runtime. 
Can you try compiling the YCSB with hbase-2.0 client? I think you may see some difference.

**Comment by ramkrish86** [comment]
I tried with the latest (tip of ycsb ) the stack trace that I mentioned is not pronounced much. But the other version that I was using was blocking on the above stack trace and was getting very low throughput. will report back if there is a problem. If not will close this ticket for now. Thanks @busbey and @saintstack .

**Comment by ramkrish86** [comment]
Ok I deleted my last comment. I still feel hbase 1.2 client has the stack trace issue that I mentioned earlier. Tried with YCSB prepared against the latest tip of current master. 
Since already hbase2.0 binding is added am able to easily switch over from hbase1.2 to hbase2.0 and the difference in throughput in clearly visible.

**Comment by busbey** [comment]
Anyone up for putting up a PR to make a config?

I haven't seen any change in guidance on Connection creation over in HBase, so I'd want it to default to the current behavior of a Connection per JVM.

Or is this moot now that HBase 2.0 is GA?

**Comment by busbey** [comment]
Closing as stale. If someone would like to continue working on this, please put up a PR as mentioned earlier.
