### ISSUE TITLE
redis：Exception in thread "Thread-1" java.lang.NullPointerException

### ISSUE THREAD

**Issue by AlvinLv00** [brianfrankcooper/YCSB#1163]
**_# ./bin/ycsb load redis -s -P workloads/workloada -p "redis.host=172.30.1.58" -p "redis.port=26310"_** 

java -cp /root/ycsb/core/target/core-0.1.4.jar:/root/ycsb/dynamodb/conf:/root/ycsb/gemfire/src/main/conf:/root/ycsb/hbase/src/main/conf:/root/ycsb/infinispan/src/main/conf:/root/ycsb/jdbc/src/main/conf:/root/ycsb/nosqldb/src/main/conf:/root/ycsb/voldemort/src/main/conf com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.RedisClient -s -P workloads/workloada -p redis.host=172.30.1.58 -p redis.port=26310 -load
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.RedisClient -s -P workloads/workloada -p redis.host=172.30.1.58 -p redis.port=26310 -load
Loading workload...
Starting test.
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.RedisClient
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:713)
**Exception in thread "Thread-1" java.lang.NullPointerException**
        at com.yahoo.ycsb.ClientThread.run(Client.java:189)
[OVERALL], RunTime(ms), 1.0
[OVERALL], Throughput(ops/sec), 0.0

**Comment by busbey** [comment]
Could you try with the latest release please?

https://github.com/brianfrankcooper/YCSB/releases/latest

**Comment by AlvinLv00** [comment]
@busbey The problem has been solved by the latest version， Thank you very much ！
