### ISSUE TITLE
"mvn clean package" there are test failures

### ISSUE THREAD

**Issue by meSmashsta** [brianfrankcooper/YCSB#1193]
Windows 10
Apache Maven 3.5.4
Java version: 1.8.0_172, vendor: Oracle Corporation
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

git clone git://github.com/brianfrankcooper/YCSB.git
cd YCSB
mvn clean package

```
[main] INFO com.yahoo.ycsb.db.CassandraCQLClient - Datacenter: datacenter1; Host: localhost/127.0.0.1; Rack: rack1

[main] ERROR com.yahoo.ycsb.db.CassandraCQLClient - Error inserting key: key
java.lang.NullPointerException
        at com.yahoo.ycsb.db.CassandraCQLClient.insert(CassandraCQLClient.java:547)
        at com.yahoo.ycsb.db.CassandraCQLClientTest.testInsert(CassandraCQLClientTest.java:165)
        at com.yahoo.ycsb.db.CassandraCQLClientTest.testPreparedStatements(CassandraCQLClientTest.java:233)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:119)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
        at com.sun.proxy.$Proxy0.invoke(Unknown Source)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
[main] ERROR com.yahoo.ycsb.db.CassandraCQLClient - Error deleting key: user1
java.lang.NullPointerException
        at com.yahoo.ycsb.db.CassandraCQLClient.delete(CassandraCQLClient.java:603)
        at com.yahoo.ycsb.db.CassandraCQLClientTest.testDelete(CassandraCQLClientTest.java:214)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:119)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
        at com.sun.proxy.$Proxy0.invoke(Unknown Source)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
[main] ERROR com.yahoo.ycsb.db.CassandraCQLClient - Error inserting key: key
java.lang.NullPointerException
        at com.yahoo.ycsb.db.CassandraCQLClient.insert(CassandraCQLClient.java:547)
        at com.yahoo.ycsb.db.CassandraCQLClientTest.testInsert(CassandraCQLClientTest.java:165)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:119)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
        at com.sun.proxy.$Proxy0.invoke(Unknown Source)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
[main] ERROR com.yahoo.ycsb.db.CassandraCQLClient - Error updating key: user1
java.lang.NullPointerException
        at com.yahoo.ycsb.db.CassandraCQLClient.update(CassandraCQLClient.java:475)
        at com.yahoo.ycsb.db.CassandraCQLClientTest.testUpdate(CassandraCQLClientTest.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:119)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:101)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
        at com.sun.proxy.$Proxy0.invoke(Unknown Source)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Tests run: 17, Failures: 4, Errors: 11, Skipped: 0, Time elapsed: 268.994 sec <<< FAILURE!

Results :

Failed tests:
  testPreparedStatements(com.yahoo.ycsb.db.CassandraCQLClientTest):
  testDelete(com.yahoo.ycsb.db.CassandraCQLClientTest):
  testInsert(com.yahoo.ycsb.db.CassandraCQLClientTest):
  testUpdate(com.yahoo.ycsb.db.CassandraCQLClientTest):

Tests in error:
  testReadMissingRow(com.yahoo.ycsb.db.CassandraCQLClientTest): com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/0:0:0:0:0:0:0:1:9142 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect), localhost/127.0.0.1:9142 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1] Operation timed out))
  testReadMissingRow(com.yahoo.ycsb.db.CassandraCQLClientTest): All host(s) tried for query failed (tried: localhost/127.0.0.1:9142 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1] Timed out waiting for server response))
  testReadMissingRow(com.yahoo.ycsb.db.CassandraCQLClientTest)
  testPreparedStatements(com.yahoo.ycsb.db.CassandraCQLClientTest): All host(s) tried for query failed (tried: localhost/127.0.0.1:9142 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1] Timed out waiting for server response))
  testPreparedStatements(com.yahoo.ycsb.db.CassandraCQLClientTest)
  testDelete(com.yahoo.ycsb.db.CassandraCQLClientTest): All host(s) tried for query failed (tried: localhost/127.0.0.1:9142 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1] Timed out waiting for server response))
  testDelete(com.yahoo.ycsb.db.CassandraCQLClientTest)
  testInsert(com.yahoo.ycsb.db.CassandraCQLClientTest): All host(s) tried for query failed (tried: localhost/127.0.0.1:9142 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1] Timed out waiting for server response))
  testInsert(com.yahoo.ycsb.db.CassandraCQLClientTest)
  testUpdate(com.yahoo.ycsb.db.CassandraCQLClientTest): All host(s) tried for query failed (tried: localhost/127.0.0.1:9142 (com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1] Timed out waiting for server response))
  testUpdate(com.yahoo.ycsb.db.CassandraCQLClientTest)

Tests run: 17, Failures: 4, Errors: 11, Skipped: 0

[StorageServiceShutdownHook] INFO org.apache.cassandra.hints.HintsService - Paused hints dispatch
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] YCSB Root 0.15.0-SNAPSHOT .......................... SUCCESS [ 12.106 s]
[INFO] Core YCSB .......................................... SUCCESS [ 21.037 s]
[INFO] Per Datastore Binding descriptor ................... SUCCESS [  0.461 s]
[INFO] YCSB Datastore Binding Parent ...................... SUCCESS [  3.175 s]
[INFO] Accumulo 1.6 DB Binding ............................ SUCCESS [ 43.647 s]
[INFO] Accumulo 1.7 DB Binding ............................ SUCCESS [  9.726 s]
[INFO] Accumulo 1.8 DB Binding ............................ SUCCESS [ 24.268 s]
[INFO] Aerospike DB Binding ............................... SUCCESS [  1.714 s]
[INFO] ArangoDB Binding ................................... SUCCESS [  2.465 s]
[INFO] AsyncHBase Client Binding for Apache HBase ......... SUCCESS [ 19.363 s]
[INFO] Cassandra 2.1+ DB Binding .......................... FAILURE [18:00 min]
[INFO] Cloud Spanner DB Binding ........................... SKIPPED
[INFO] Couchbase Binding .................................. SKIPPED
[INFO] Couchbase Java SDK 2.x Binding ..................... SKIPPED
[INFO] Azure DocumentDB Binding ........................... SKIPPED
[INFO] Azure table storage Binding ........................ SKIPPED
[INFO] DynamoDB DB Binding ................................ SKIPPED
[INFO] Elasticsearch Binding .............................. SKIPPED
[INFO] Elasticsearch 5.x Binding .......................... SKIPPED
[INFO] FoundationDB Binding ............................... SKIPPED
[INFO] Geode DB Binding ................................... SKIPPED
[INFO] Google Cloud Datastore Binding ..................... SKIPPED
[INFO] Google Cloud Bigtable Binding ...................... SKIPPED
[INFO] HBase 0.98.x DB Binding ............................ SKIPPED
[INFO] HBase 1.0 DB Binding ............................... SKIPPED
[INFO] HBase 1.2 DB Binding ............................... SKIPPED
[INFO] HBase 1.4 DB Binding ............................... SKIPPED
[INFO] HBase 2.0 DB Binding ............................... SKIPPED
[INFO] Hypertable DB Binding .............................. SKIPPED
[INFO] Apache Ignite ...................................... SKIPPED
[INFO] Infinispan DB Binding .............................. SKIPPED
[INFO] JDBC DB Binding .................................... SKIPPED
[INFO] Kudu DB Binding .................................... SKIPPED
[INFO] memcached binding .................................. SKIPPED
[INFO] MapRDB Binding ..................................... SKIPPED
[INFO] MapR JSON DB Binding ............................... SKIPPED
[INFO] MongoDB Binding .................................... SKIPPED
[INFO] Oracle NoSQL Database Binding ...................... SKIPPED
[INFO] OrientDB Binding ................................... SKIPPED
[INFO] rados of Ceph FS binding ........................... SKIPPED
[INFO] Redis DB Binding ................................... SKIPPED
[INFO] Rest Client Binding ................................ SKIPPED
[INFO] Riak KV Binding .................................... SKIPPED
[INFO] RocksDB Java Binding ............................... SKIPPED
[INFO] S3 Storage Binding ................................. SKIPPED
[INFO] Solr Binding ....................................... SKIPPED
[INFO] Solr 6 Binding ..................................... SKIPPED
[INFO] Tarantool DB Binding ............................... SKIPPED
[INFO] YCSB Release Distribution Builder 0.15.0-SNAPSHOT .. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20:19 min
[INFO] Finished at: 2018-07-17T21:52:52+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.8:test (default-test) on project cassandra-binding: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\lenovo\Documents\Projects\YCSB\cassandra\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :cassandra-binding

```

**Comment by diogojfernandes** [comment]
Hello. I had the same problem. Solved that by running the binaries. 

https://github.com/brianfrankcooper/YCSB/releases

Just unzip the "ycsb-0.14.0.tar.gz" and it must work.

**Comment by busbey** [comment]
unfortunately, I don't believe you can. Is there something you need to change in the source code for your use case?

**Comment by meSmashsta** [comment]
I need to create a class that extends the workload to benchmark my own data.

**Comment by busbey** [comment]
you should look at the full output of the surefire log for an error in initialization. a null pointer exception there means that the cassandra session never got set, but we should have errored out when that happened.

**Comment by meSmashsta** [comment]
Where can I find that surefire log? I will also try and look for that log file.

**Comment by busbey** [comment]
it'll be in `target/surefire-reports` of the failed module

**Comment by meSmashsta** [comment]
By the way, I was able to build it without any error because I skipped the testing part...

`mvn clean install -DskipTests`

But I would still report that logs when I get back to the device I that used.

**Comment by busbey** [comment]
Closing as stale. Please reopen if you're still having trouble.
