### ISSUE TITLE
errors when test mongodb ssl 

### ISSUE THREAD

**Issue by ThreeOrange** [brianfrankcooper/YCSB#1243]
try to test mongodb ssl connection, appear some errors

com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches PrimaryServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=10.142.90.96:5153, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketReadException: Prematurely reached end of stream}}]
        at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:370)
        at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101)
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
        at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
        at com.mongodb.binding.ClusterBinding.getWriteConnectionSource(ClusterBinding.java:68)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:175)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:141)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:72)
        at com.mongodb.Mongo.execute(Mongo.java:747)
        at com.mongodb.Mongo$2.execute(Mongo.java:730)
        at com.mongodb.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:482)
        at com.mongodb.MongoCollectionImpl.insertOne(MongoCollectionImpl.java:277)
        at com.yahoo.ycsb.db.MongoDbClient.insert(MongoDbClient.java:270)
        at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:240)
        at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:593)
        at com.yahoo.ycsb.ClientThread.run(Client.java:475)
        at java.lang.Thread.run(Thread.java:745)

**Comment by risdenk** [comment]
Is Mongodb actually up and running? Have you confirmed that before trying with YCSB? Looks like there is some issue with Mongo or the connection string you provided to YCSB.

**Comment by ThreeOrange** [comment]
> Is Mongodb actually up and running? Have you confirmed that before trying with YCSB? Looks like there is some issue with Mongo or the connection string you provided to YCSB.

Thanks for your reply.
I have solved the problem, the protogenetic code doesn't support SSL, I change the script(ycsb) firstly, then set the CA certificate.

**Comment by liucgbj** [comment]
@ThreeOrange , can you please share more detail information, it will be great if you can share all the necessary steps which are used to fix this problem, thanks.

**Comment by ThreeOrange** [comment]
> @ThreeOrange , can you please share more detail information, it will be great if you can share all the necessary steps which are used to fix this problem, thanks.

@liucgbj , I did two operations. The version of YCSB is 0.12.0 which I used at that moment.

Firstly, change the script like below. 
![image](https://user-images.githubusercontent.com/14704632/114119804-ef21c080-991d-11eb-823a-01f1fb4628aa.png)

Secondly , set the ca file for java and turn on the sslInvalidHostnameAllowed.

Hope it's useful for you.

**Comment by liucgbj** [comment]
@ThreeOrange , Thank you for your prompt reply ! 

I have few questions, can you please provide feedback, thanks.

Q1 : I've modified the script like below, is that correct ?
```
    truststore = "-Djavax.net.ssl.trustStore=/tmp/ycsb/YCSB/"
    truststore_pass = "-Djavax.net.ssl.trustStorePassword=changeit"

    ycsb_command = ([java] + args.jvm_args +
                    #["-cp", classpath,
                    [truststore, truststore_pass, "-cp", classpath,
                     main_classname, "-db", db_classname] + remaining)
```

Q2 : may i know how to set the ca file, should i run below command to set it ? please let me know.
```
keytool -import -alias cacert -storepass changeit -keystore cacerts.jks -file /tmp/ycsb/cert.pem
```

Q3 : may i know how to turn on the sslInvalidHostnameAllowed ?
