### ISSUE TITLE
Cassandra gives com.yahoo.ycsb.db.CassandraCQLClient - Error inserting key: error

### ISSUE THREAD

**Issue by oylumalatli** [brianfrankcooper/YCSB#1288]
Hello,

I am trying to test Cassandra 2.2.12 with YCSB 0.15.0. I have prepared my own workload. When I run it with the command:

./bin/ycsb load cassandra-cql -P workloads/workload_egeuniversity_writeonly_histogram -p hosts="127.0.0.1"

I get the following output:

<pre>oading workload...
Starting test.
[Thread-2] INFO com.datastax.driver.core.NettyUtil - Did not find Netty&apos;s native epoll transport in the classpath, defaulting to NIO.
[Thread-2] INFO com.datastax.driver.core.policies.DCAwareRoundRobinPolicy - Using data-center name &apos;datacenter1&apos; for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
[Thread-2] INFO com.datastax.driver.core.Cluster - New Cassandra host /127.0.0.1:9042 added
[Thread-2] INFO com.yahoo.ycsb.db.CassandraCQLClient - Connected to cluster: Test Cluster

[Thread-2] INFO com.yahoo.ycsb.db.CassandraCQLClient - Datacenter: datacenter1; Host: /127.0.0.1; Rack: rack1

DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
[Thread-2] ERROR com.yahoo.ycsb.db.CassandraCQLClient - Error inserting key: user1
com.datastax.driver.core.exceptions.SyntaxError: line 1:28 no viable alternative at input &apos;0&apos; (INSERT INTO usertable (y_id,[0]...)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:58)
	at com.datastax.driver.core.exceptions.SyntaxError.copy(SyntaxError.java:24)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:110)
	at com.yahoo.ycsb.db.CassandraCQLClient.insert(CassandraCQLClient.java:547)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:221)
	at com.yahoo.ycsb.workloads.EgeUniversityWorkload.doInsert(EgeUniversityWorkload.java:720)
	at com.yahoo.ycsb.ClientThread.run(ClientThread.java:118)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.SyntaxError: line 1:28 no viable alternative at input &apos;0&apos; (INSERT INTO usertable (y_id,[0]...)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:132)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1174)
	at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1168)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:184)
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:798)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:617)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1005)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:928)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	... 1 more

What can be the reason for this? The record structure I use is as follows: 

create table usertable (y_id varchar primary key,date varchar,elevation varchar,latitude varchar,longitude varchar,name varchar,prcp varchar,snwd varchar,station varchar,tavg varchar,tmax varchar,tmin varchar);

Thanks a lot,

Oylum

**Comment by busbey** [comment]
YCSB requires a table with a specific format. Please use the README included in the Cassandra module for the needed definition.

**Comment by Boopalanmani** [comment]
Hi Team,

Am getting below error while run benchmarking, Could you please help to resolve this issue
[root@node-a ycsb-0.17.0]# bin/ycsb load cassandra-cql -p hosts=127.0.0.1 -s -P workloads/workloada
java -cp /root/ycsb-0.17.0/cassandra-binding/conf:/root/ycsb-0.17.0/conf:/root/ycsb-0.17.0/lib/core-0.17.0.jar:/root/ycsb-0.17.0/lib/htrace-core4-4.1.0-incubating.jar:/root/ycsb-0.17.0/lib/jackson-mapper-asl-1.9.4.jar:/root/ycsb-0.17.0/lib/jackson-core-asl-1.9.4.jar:/root/ycsb-0.17.0/lib/HdrHistogram-2.1.4.jar:/root/ycsb-0.17.0/lib/slf4j-api-1.7.30.jar:/root/ycsb-0.17.0/lib/slf4j-jdk14-1.7.30.jar:/root/ycsb-0.17.0/lib/slf4j-simple-1.7.30.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-common-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-transport-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/slf4j-api-1.7.25.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-codec-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-buffer-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/cassandra-driver-core-3.0.0.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-handler-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/metrics-core-3.1.2.jar:/root/ycsb-0.17.0/cassandra-binding/lib/guava-16.0.1.jar:/root/ycsb-0.17.0/cassandra-binding/lib/cassandra-binding-0.17.0.jar site.ycsb.Client -db site.ycsb.db.CassandraCQLClient -p hosts=127.0.0.1 -s -P workloads/workloada -load
Command line: -db site.ycsb.db.CassandraCQLClient -p hosts=127.0.0.1 -s -P workloads/workloada -load
YCSB Client 0.17.0

Loading workload...
Starting test.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/ycsb-0.17.0/lib/slf4j-jdk14-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/ycsb-0.17.0/lib/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
2020-03-28 11:27:04:251 0 sec: 0 operations; est completion in 0 second 
Mar 28, 2020 11:27:04 AM com.datastax.driver.core.NettyUtil <clinit>
INFO: Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
Mar 28, 2020 11:27:04 AM com.datastax.driver.core.policies.DCAwareRoundRobinPolicy init
INFO: Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
Mar 28, 2020 11:27:04 AM com.datastax.driver.core.Cluster$Manager init
INFO: New Cassandra host /127.0.0.1:9042 added
Mar 28, 2020 11:27:04 AM site.ycsb.db.CassandraCQLClient init
INFO: Connected to cluster: Test Cluster

Mar 28, 2020 11:27:04 AM site.ycsb.db.CassandraCQLClient init
INFO: Datacenter: datacenter1; Host: /127.0.0.1; Rack: rack1

DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Mar 28, 2020 11:27:04 AM site.ycsb.db.CassandraCQLClient insert
SEVERE: Error inserting key: user6284781860667377211
com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name field9
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:110)
	at site.ycsb.db.CassandraCQLClient.insert(CassandraCQLClient.java:557)
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221)
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601)
	at site.ycsb.ClientThread.run(ClientThread.java:135)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name field9
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:136)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1174)
	at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1168)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:184)
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:798)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:617)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1005)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:928)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	... 1 more

Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
2020-03-28 11:27:07:123 2 sec: 0 operations; est completion in 106751991167300 days 15 hours [CLEANUP: Count=1, Max=2242559, Min=2240512, Avg=2241536, 90=2242559, 99=2242559, 99.9=2242559, 99.99=2242559] [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=?, 90=0, 99=0, 99.9=0, 99.99=0] [INSERT-FAILED: Count=1, Max=11567, Min=11560, Avg=11564, 90=11567, 99=11567, 99.9=11567, 99.99=11567] 
[OVERALL], RunTime(ms), 2897
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 1
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 7
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.2416292716603383
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 7
[TOTAL_GC_TIME_%], Time(%), 0.2416292716603383
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 2241536.0
[CLEANUP], MinLatency(us), 2240512
[CLEANUP], MaxLatency(us), 2242559
[CLEANUP], 95thPercentileLatency(us), 2242559
[CLEANUP], 99thPercentileLatency(us), 2242559
[INSERT], Operations, 0
[INSERT], AverageLatency(us), NaN
[INSERT], MinLatency(us), 9223372036854775807
[INSERT], MaxLatency(us), 0
[INSERT], 95thPercentileLatency(us), 0
[INSERT], 99thPercentileLatency(us), 0
[INSERT], Return=ERROR, 1
[INSERT-FAILED], Operations, 1
[INSERT-FAILED], AverageLatency(us), 11564.0
[INSERT-FAILED], MinLatency(us), 11560
[INSERT-FAILED], MaxLatency(us), 11567
[INSERT-FAILED], 95thPercentileLatency(us), 11567
[INSERT-FAILED], 99thPercentileLatency(us), 11567
