### ISSUE TITLE
Can't test couchbase

### ISSUE THREAD

**Issue by andrecalcada** [brianfrankcooper/YCSB#1316]
Hi I'm trying to test couchbase trough YCSB I've tried couchbase and couchbase2 for this but when I execute the load command (bin/ycsb load couchbase -s -P workloads/workloada) this error shows:

com.yahoo.ycsb.DBException: Could not connect to Couchbase Bucket.
	at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:208)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
	at com.yahoo.ycsb.ClientThread.run(ClientThread.java:91)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.couchbase.client.java.error.InvalidPasswordException: Passwords for bucket "projeto" do not match.
	at com.couchbase.client.java.CouchbaseAsyncCluster$OpenBucketErrorHandler.call(CouchbaseAsyncCluster.java:474)
	at com.couchbase.client.java.CouchbaseAsyncCluster$OpenBucketErrorHandler.call(CouchbaseAsyncCluster.java:457)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:139)
	at rx.internal.operators.OperatorMap$MapSubscriber.onError(OperatorMap.java:85)
	at rx.observers.Subscribers$5.onError(Subscribers.java:224)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:264)
	at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:207)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	... 1 more

**Comment by busbey** [comment]
What version of couchbase and what version of ycsb?

**Comment by andrecalcada** [comment]
couchbase server community 6.0.0 ubuntu 18.04 and ycsb is this version https://github.com/brianfrankcooper/YCSB

**Comment by andrecalcada** [comment]
> couchbase server community 6.0.0 ubuntu 18.04 and ycsb is this version https://github.com/brianfrankcooper/YCSB

can you please help me?

**Comment by busbey** [comment]
We're all volunteers here; sometimes responses take a bit. Please be patient. If you'd like things to go faster, see of you can help answer someone else's question in the meantime.

**Comment by busbey** [comment]
One quick thing, you should reproduce the issue with one of our published binaries from the releases page.

**Comment by andrecalcada** [comment]
you mean the couchbase?

**Comment by busbey** [comment]
No I meant one of the YCSB released binaries.

**Comment by andrecalcada** [comment]
I don't understand what you mean because the YCSB I'm using is from git, can you put here a link?

**Comment by busbey** [comment]
As a project we publish releases with precompiled binaries. the latest is always here:

https://github.com/brianfrankcooper/YCSB/releases/latest

The bottom of the release description has a section titled "Assets" and in it you should find `ycsb-%VERSION%.tar.gz` for everything or `ycsb-couchbase2-binding-%VERSION%.tar.gz` for just checking couchbase 2.

**Comment by aakarshg** [comment]
Can confirm that I face the same issue, this is with version6 of couchbase. Looks like the connection string from 5 onwards requires the username and password for the cluster, maybe why the issue?

**Comment by YLonely** [comment]
You have to create a user which has the same name of your bucket

**Comment by edihasaj** [comment]
@YLonely is right.
Make the bucket name the same as the user, or the other way around and then execute

$ ./bin/ycsb run couchbase2 -s -P workloads/workloada -p couchbase.bucket=test -p couchbase.password=secret -p recourdcount=1000000

**Comment by douaberigoale** [comment]
Can confirm @edihasaj instructions work. Thanks a bunch!
