### ISSUE TITLE
Required property "hosts" missing for CassandraCQLClient

### ISSUE THREAD

**Issue by josemRZ** [brianfrankcooper/YCSB#1341]
Hi,

I have installed and prepared table and keyspace for my Cassandra 3.11.4 and I am using YCSB 0.15.0, first doubt I have is if the latest version of Cassandra is supported by the latest YCSB cassandra binding interface? 

Anyway I still would like to ask in order to understand things a bit better, I am initiating a loading of core workload A with the line:

$ ./bin/ycsb load cassandra-cql -P workloads/workloada

I get the following error:

Loading workload...
**Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.yahoo.ycsb.DBException: com.yahoo.ycsb.DBException: Required property "hosts" missing for CassandraCQLClient
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:225)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
	at com.yahoo.ycsb.ClientThread.run(Client.java:424)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.yahoo.ycsb.DBException: Required property "hosts" missing for CassandraCQLClient
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:154)
	... 3 more
com.yahoo.ycsb.DBException: com.yahoo.ycsb.DBException: Required property "hosts" missing for CassandraCQLClient
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:225)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
	at com.yahoo.ycsb.ClientThread.run(Client.java:424)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.yahoo.ycsb.DBException: Required property "hosts" missing for CassandraCQLClient
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:154)**

My understanding is that this is directly related to the hosts property as adviced on readme.md for Cassandra binding.

## Cassandra Configuration Parameters
- 'hosts' (**required**)
   -Cassandra nodes to connect to.
   -No default. 

Where can I find and edit correctly this property on Cassandra Configuration files?

Thanks very much,

**Comment by busbey** [comment]
you can set it in a properties file (same format as `workloads/workloada`) and then pass that via e.g. `-P /some/path/to/my/cassandra_ycsb.properties` or you can just pass it in the cli to ycsb, e.g. if Cassandra is running on localhost then `./bin/ycsb load cassandra-cql -P workloads/workloada -p hosts=localhost`

**Comment by josemRZ** [comment]
Thanks will try, do i need to reduce my Cassandra to a previous version 2.x?

**Comment by busbey** [comment]
The release notes for the YCSB you're using should include what versions of Cassandra are expected to work.

**Comment by josemRZ** [comment]
Hi, it worked passing the hosts in command line . Also I can confirm Cassandra 3.11.4 can be benchmarked with ycsb 0.15.0
