### ISSUE TITLE
ElasticSearch ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by huystuhh** [brianfrankcooper/YCSB#1347]
Hello,

I'm trying to use the ElasticSearch5-Rest Client to connect to an AWS ElasticSearch instance but I keep getting an exception when trying to start the workload.

```
Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.yahoo.ycsb.db.elasticsearch5.ElasticsearchRestClient.init(ElasticsearchRestClient.java:87)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
	at com.yahoo.ycsb.ClientThread.run(ClientThread.java:91)
	at java.lang.Thread.run(Thread.java:748)
```

I've also tried with the regular ElasticSearch and ElasticSearch5 bindings. Any help would be much appreciated.

Thanks,
Huy

**Comment by busbey** [comment]
The operation count in your second example looks like YCSB never manages to connect to the ES cluster.

**Comment by madonhe** [comment]
==this elasticsearch 7.2.0  write this ok.
./bin/ycsb load elasticsearch5-rest  -P workloads/workloadb -p "es.hosts.list=172.18.3.121:9200"   -p "es.index.key=customer1"  -p "es.number_of_shards=1" -p "es.number_of_replicas=1"  -p "es.setting.cluster.name=my-application" -p "insertproportion=1"  -s 

2019-09-11 13:58:28:439 0 sec: 0 operations; est completion in 0 second 
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Sep 11, 2019 1:58:28 PM org.elasticsearch.client.RestClient logResponse
WARNING: request [POST http://172.18.3.121:9200/customer1/usertable/] returned 1 warnings: [299 Elasticsearch-7.2.0-508c38a "[types removal] Specifying types in document index requests is deprecated, use the typeless endpoints instead (/{index}/_doc/{id}, /{index}/_doc, or /{index}/_create/{id})."]
2019-09-11 13:58:29:006 0 sec: 1 operations; 1.68 current ops/sec; [CLEANUP: Count=1, Max=9687, Min=9680, Avg=9684, 90=9687, 99=9687, 99.9=9687, 99.99=9687] [INSERT: Count=1, Max=125247, Min=125184, Avg=125216, 90=125247, 99=125247, 99.9=125247, 99.99=125247] 
[OVERALL], RunTime(ms), 596
[OVERALL], Throughput(ops/sec), 1.6778523489932886


==this  elasticsearch 5.5.0   write this waning
2019-09-11 13:59:26:646 0 sec: 0 operations; est completion in 0 second 
2019-09-11 13:59:36:623 10 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2019-09-11 13:59:46:623 20 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2019-09-11 13:59:56:623 30 sec: 0 operations; est completion in 106751991167300 days 15 hours 
java.io.IOException: listener timeout after waiting for [30000] ms
        at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:660)

**Comment by madonhe** [comment]
> @risdenk Hi Risdenk, thank you for the assistance!
> 
> You were right, dumb mistake by me not specifying the port in the full host. I'm running into another error now if it's not too much of a bother. I'm able to load/run a workload directly through the command line like so:
> 
> ```
> ./bin/ycsb run elasticsearch5-rest -s -P workloads/workloadb -p exportfile=... -p path.home=... -p es.remote=true -p es.hosts.list=... -s -t
> ```
> 
> But when trying to launch a similar command through a Python script that runs the benchmark, I receive this error on trying to load and I'm not quite sure why I would get this error here as opposed to successfully on the command line:
> 
> ```
> Loading workload...
> Starting test.
> 2019-08-26 19:59:55:795 0 sec: 0 operations; est completion in 0 second 
> 2019-08-26 20:00:05:770 10 sec: 0 operations; est completion in 106751991167300 days 15 hours 
> 2019-08-26 20:00:15:770 20 sec: 0 operations; est completion in 106751991167300 days 15 hours 
> 2019-08-26 20:00:25:770 30 sec: 0 operations; est completion in 106751991167300 days 15 hours 
> java.io.IOException: listener timeout after waiting for [30000] ms
> 	at org.elasticsearch.client.RestClient$SyncResponseListener.get(RestClient.java:660)
> 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:219)
> 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:191)
> 	at com.yahoo.ycsb.db.elasticsearch5.ElasticsearchRestClient.performRequest(ElasticsearchRestClient.java:162)
> 	at com.yahoo.ycsb.db.elasticsearch5.ElasticsearchRestClient.performRequest(ElasticsearchRestClient.java:144)
> 	at com.yahoo.ycsb.db.elasticsearch5.ElasticsearchRestClient.init(ElasticsearchRestClient.java:124)
> 	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
> 	at com.yahoo.ycsb.ClientThread.run(Client.java:424)
> 	at java.lang.Thread.run(Thread.java:748)
> ```
> 
> The load command as executed from the Python script:
> 
> ```
> Command line: -db com.yahoo.ycsb.db.elasticsearch5.ElasticsearchRestClient -s -P workloads/workloadb -P /root/YCSB/workload.dat -p es.index.key=ycsb_4krpny6ibdhad30m34gc -p es.remote=true -p es.hosts.list=... -p exportfile=output/run-transactions0.dat -s -threads 1 -t
> ```

==my use this code this ok  . this Elasticsearch-5.5.0
./bin/ycsb run  elasticsearch5-rest  -P workloads/workloada -p "es.hosts.list=172.18.3.120:9200,172.18.3.121:9200,172.18.3.122:9200"
