### ISSUE TITLE
mongodb-async driver showing I/O error when connecting with mongodb url

### ISSUE THREAD

**Issue by hroyrh** [brianfrankcooper/YCSB#1369]
When trying to run ycsb benchmark with mongodb-async driver, we see an IO error while the mongodb-sync driver works fine. Here is a snapshot of the error we get --
```
15:39:14.751 [Thread-3] WARN  c.a.m.c.c.b.BootstrapConnectionFactory - I/O error during bootstrap to mongo0-0.mongo0:27017.
java.net.UnknownHostException: mongo0-0.mongo0
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_232]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_232]
	at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_232]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.openSocket(AbstractSocketConnection.java:808) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.<init>(AbstractSocketConnection.java:172) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.SocketConnection.<init>(SocketConnection.java:121) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.SocketConnectionFactory.connect(SocketConnectionFactory.java:210) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.bootstrap(BootstrapConnectionFactory.java:177) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.createDelegate(BootstrapConnectionFactory.java:290) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getDelegate(BootstrapConnectionFactory.java:268) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getClusterStats(BootstrapConnectionFactory.java:114) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.ClientImpl.getClusterStats(ClientImpl.java:199) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.doInsertAsync(AbstractMongoOperations.java:1037) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.insertAsync(AbstractMongoOperations.java:583) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractAsyncMongoCollection.insertAsync(AbstractAsyncMongoCollection.java:1255) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:684) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:722) [mongodb-async-driver-2.0.1.jar:na]
	at site.ycsb.db.AsyncMongoDbClient.insert(AsyncMongoDbClient.java:272) [mongodb-binding-0.17.0.jar:na]
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221) [core-0.17.0.jar:na]
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601) [core-0.17.0.jar:na]
	at site.ycsb.ClientThread.run(ClientThread.java:135) [core-0.17.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_232]
15:39:14.754 [Thread-3] WARN  c.a.m.c.c.b.BootstrapConnectionFactory - Could not bootstrap a connection to the MongoDB servers.
com.allanbank.mongodb.error.CannotConnectException: Could not bootstrap a connection to the MongoDB servers.
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.createDelegate(BootstrapConnectionFactory.java:293)
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getDelegate(BootstrapConnectionFactory.java:268)
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getClusterStats(BootstrapConnectionFactory.java:114)
	at com.allanbank.mongodb.client.ClientImpl.getClusterStats(ClientImpl.java:199)
	at com.allanbank.mongodb.client.AbstractMongoOperations.doInsertAsync(AbstractMongoOperations.java:1037)
	at com.allanbank.mongodb.client.AbstractMongoOperations.insertAsync(AbstractMongoOperations.java:583)
	at com.allanbank.mongodb.client.AbstractAsyncMongoCollection.insertAsync(AbstractAsyncMongoCollection.java:1255)
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:684)
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:722)
	at site.ycsb.db.AsyncMongoDbClient.insert(AsyncMongoDbClient.java:272)
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221)
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601)
	at site.ycsb.ClientThread.run(ClientThread.java:135)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by busbey** [comment]
Are you sure you're passing the correct information about connecting to your mongo instance? the error message here:

```
15:39:14.751 [Thread-3] WARN  c.a.m.c.c.b.BootstrapConnectionFactory - I/O error during bootstrap to mongo0-0.mongo0:27017.
java.net.UnknownHostException: mongo0-0.mongo0
```

Suggests that you are saying the mongodb host is named "mongo0-0.mongo0" but that isn't a resolvable host name

**Comment by hroyrh** [comment]
Updated the full hostname as per the original error message

**Comment by busbey** [comment]
okay, it's still saying it can't resolve that host name. Does it resolve via other tools?

**Comment by hroyrh** [comment]
I mean for the same setup/hostname the ycsb with mongodb-sync driver works perfectly fine. But as soon as I switch to the mongodb-async driver I get this issue.

**Comment by aakarshg** [comment]
@busbey it does resolve using other tools, what's even more interesting is that mongo logs show that a connection has been opened ( ip seems to be the same pod/container where ycsb is running )

**Comment by busbey** [comment]
@allanbank any ideas about how the async client might be looking at things differently here?

**Comment by allanbank** [comment]
Short answer - no.

The driver line is doing a simple [Socket.connect(InetAddress,timeout)](http://www.allanbank.com/mongodb-async-driver/xref/com/allanbank/mongodb/client/connection/socket/AbstractSocketConnection.html#L808) on the socket. But the socket is complaining that the InetAddress is [not resolved](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/net/AbstractPlainSocketImpl.java#l183).

What does the URI you are using look like?

**Comment by hroyrh** [comment]
@allanbank we are using `mongodb.url=mongodb://mongo0-0.mongo0.builder-infra.svc.cluster.local:27017/ycsb`
