### ISSUE TITLE
python bin\ycsb is broken and bat file does not accept '-cp' flag

### ISSUE THREAD

**Issue by VinayBanakar** [brianfrankcooper/YCSB#1383]
Hi, I seem to be facing an issue while running `python bin\ycsb`. I have python 2.7 and Java SE 8 installed. 
```
PS C:\Users\XXX\YCSB> C:\Python27\python.exe bin\ycsb load basic -P workloads\workloada -p recordcount=4
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:core -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
Traceback (most recent call last):
  File "bin\ycsb", line 332, in <module>
    sys.exit(main())
  File "bin\ycsb", line 305, in main
    maven_says = get_classpath_from_maven(project)
  File "bin\ycsb", line 220, in get_classpath_from_maven
    "-Dmdep.outputFilterFile=true"])
  File "bin\ycsb", line 169, in check_output
    process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```
I would have used bat file but it doesn't seem to support -cp flag which I need to pass my db jdbc connector jar.
`.\bin\ycsb.bat load jdbc -P .\workloads\workloada -P .\jdbc\src\main\conf\db.properties -p recordcount=1000 -p operationcount=1000 -cp .\jdbc\target\mssql-jdbc-7.4.1.jre8-shaded.jar`
and I get
```
Usage: java site.ycsb.Client [options]
Options:
  -threads n: execute using n threads (default: 1) - can also be specified as the
        "threadcount" property using -p
  -target n: attempt to do n operations per second (default: unlimited) - can also
       be specified as the "target" property using -p
  -load:  run the loading phase of the workload
  -t:  run the transactions phase of the workload (default)
  -db dbname: specify the name of the DB to use (default: site.ycsb.BasicDB) -
        can also be specified as the "db" property using -p
  -P propertyfile: load properties from the given file. Multiple files can
           be specified, and will be processed in the order specified
  -p name=value:  specify a property to be passed to the DB and workloads;
          multiple properties can be specified, and override any
          values in the propertyfile
  -s:  show status during run (default: no status)
  -l label:  use label for status (e.g. to label one experiment out of a whole batch)

Required properties:
  workload: the name of the workload class to use (e.g. site.ycsb.workloads.CoreWorkload)

To run the transaction phase from multiple servers, start a separate client on each.
To run the load phase from multiple servers, start a separate client on each; additionally,
use the "insertcount" and "insertstart" properties to divide up the records to be inserted
Unknown option -cp
```

**Comment by busbey** [comment]
We should add classpath handling to the bat file, that's a good find.

To work around the issue with the python launcher, please use a release binary tarball rather than a git checkout.

They should be listed at the bottom of the release page:

https://github.com/brianfrankcooper/YCSB/releases/latest

**Comment by VinayBanakar** [comment]
Can you please elaborate on why python launcher won't work with git checkout?

**Comment by busbey** [comment]
The failure you're getting is from the git checkout trying to automate finding the jars and/or building from source. It might be broken or your environment might not be set up correctly. I'd rather we focus on you running things successfully rather than figure out which of those things is going wrong.

**Comment by VinayBanakar** [comment]
Okay, I modified the bat file to add my jdbc jar classpath directly, however loading workload is failing with the error 
```
Loading workload...
Starting test.
Adding shard node URL: jdbc:sqlserver://localhost:1433
Using shards: 1, batchSize:-1, fetchSize: -1
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Error in processing insert to table: usertablecom.microsoft.sqlserver.jdbc.SQLServerException: String or binary data would be truncated in table 'master.dbo.usertable', column 'YCSB_KEY'. Truncated value: 'u'.
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
[OVERALL], RunTime(ms), 859
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 309.0
[CLEANUP], MinLatency(us), 309
[CLEANUP], MaxLatency(us), 309
[CLEANUP], 95thPercentileLatency(us), 309
[CLEANUP], 99thPercentileLatency(us), 309
[INSERT], Operations, 0
[INSERT], AverageLatency(us), NaN
[INSERT], MinLatency(us), 9223372036854775807
[INSERT], MaxLatency(us), 0
[INSERT], 95thPercentileLatency(us), 0
[INSERT], 99thPercentileLatency(us), 0
[INSERT], Return=ERROR, 1
[INSERT-FAILED], Operations, 1
[INSERT-FAILED], AverageLatency(us), 81248.0
[INSERT-FAILED], MinLatency(us), 81216
[INSERT-FAILED], MaxLatency(us), 81279
[INSERT-FAILED], 95thPercentileLatency(us), 81279
[INSERT-FAILED], 99thPercentileLatency(us), 81279
```
and the command is `.\bin\ycsb2.bat load jdbc -P .\workloads\workloada -P .\jdbc\src\main\conf\db.properties -p recordcount=1000 -p operationcount=1000`.
I created `usertable` with `java -cp "jdbc\target\jdbc-binding-0.18.0-SNAPSHOT.jar;jdbc\target\mssql-jdbc-7.4.1.jre8-shaded.jar" site.ycsb.db.JdbcDBCreateTable -P jdbc\src\main\conf\db.properties -n usertable`

**Comment by busbey** [comment]
Generally we don't support folks running their own launching stuff. However, that sounds like your table wasn't created correctly and it's limiting the length of the primary key to 1 byte/character

**Comment by VinayBanakar** [comment]
I wonder why. I have tried other jdbc drivers too and I see the same problem. I didn't see this on linux but saw a whole different problem ( #1381 ) which made me move to Windows. Maybe this has to do with MSSQL itself rather than the jdbc driver.

**Comment by busbey** [comment]
Right, the failure running from source you're getting isn't necessarily about the jdbc stuff at all. It's a problem with managing to execute maven.

**Comment by busbey** [comment]
How did you create your table? Can you run a describe on it?

**Comment by VinayBanakar** [comment]
I created usertable with `java -cp "jdbc\target\jdbc-binding-0.18.0-SNAPSHOT.jar;jdbc\target\mssql-jdbc-7.4.1.jre8-shaded.jar" site.ycsb.db.JdbcDBCreateTable -P jdbc\src\main\conf\db.properties -n usertable`

```SQL
exec sp_help usertable;
```

```
Name                                                                                                                             Owner                                                                                                                            Type                            Created_datetime
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ------------------------------- -----------------------
usertable                                                                                                                        dbo                                                                                                                              user table                      2020-01-07 17:41:53.350

 
 
Column_name                                                                                                                      Type                                                                                                                             Computed                            Length      Prec  Scale Nullable                            TrimTrailingBlanks                  FixedLenNullInSource                Collation
-------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ----------------------------------- ----------- ----- ----- ----------------------------------- ----------------------------------- ----------------------------------- --------------------------------------------------------------------------------------------------------------------------------
YCSB_KEY                                                                                                                         varchar                                                                                                                          no                                  1                       no                                  no                                  no                                  SQL_Latin1_General_CP1_CI_AS
FIELD0                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS
FIELD1                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS
FIELD2                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS
FIELD3                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS
FIELD4                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS
FIELD5                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS
FIELD6                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS
FIELD7                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS
FIELD8                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS
FIELD9                                                                                                                           text                                                                                                                             no                                  16                      yes                                 (n/a)                               (n/a)                               SQL_Latin1_General_CP1_CI_AS

 
Identity                                                                                                                         Seed                                    Increment                               Not For Replication
-------------------------------------------------------------------------------------------------------------------------------- --------------------------------------- --------------------------------------- -------------------
No identity column defined.                                                                                                      NULL                                    NULL                                    NULL

 
RowGuidCol
--------------------------------------------------------------------------------------------------------------------------------
No rowguidcol column defined.

 
Data_located_on_filegroup
--------------------------------------------------------------------------------------------------------------------------------
PRIMARY

 
index_name                                                                                                                       index_description                                                                                                                                                                                                  index_keys
-------------------------------------------------------------------------------------------------------------------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PK__usertabl__D9AD07867EB69F88                                                                                                   clustered, unique, primary key located on PRIMARY                                                                                                                                                                  YCSB_KEY

 
constraint_type                                                                                                                                                                                                                                                  constraint_name                                                                                                                  delete_action update_action status_enabled status_for_replication constraint_keys
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------- ------------- ------------- -------------- ---------------------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PRIMARY KEY (clustered)                                                                                                                                                                                                                                          PK__usertabl__D9AD07867EB69F88                                                                                                   (n/a)         (n/a)         (n/a)          (n/a)                  YCSB_KEY
```

**Comment by VinayBanakar** [comment]
I tried with the latest release build which has jdbc-binding-0.17.0.jar and YCSB_KEY to still have length 1. I even tried with mssql 6.4 jdbc driver combinations but have all resulted the same.

**Comment by busbey** [comment]
Try manually creating the table rather than using the helper utility.

**Comment by VinayBanakar** [comment]
Yes, I just observed the length of all the columns is 1. 
When I create it with
```sql
CREATE TABLE usertable(YCSB_KEY VARCHAR PRIMARY KEY,
  FIELD0 VARCHAR, FIELD1 VARCHAR,
  FIELD2 VARCHAR, FIELD3 VARCHAR,
  FIELD4 VARCHAR, FIELD5 VARCHAR,
  FIELD6 VARCHAR, FIELD7 VARCHAR,
  FIELD8 VARCHAR, FIELD9 VARCHAR);
```
I thought default length of VARCHAR is 30!?

Anyway, load worked fine once I created a table as follows
```sql
CREATE TABLE usertable(
	YCSB_KEY VARCHAR(30) PRIMARY KEY,
	FIELD0 VARCHAR(255), FIELD1 VARCHAR(255),
	FIELD2 VARCHAR(255), FIELD3 VARCHAR(255),
	FIELD4 VARCHAR(255), FIELD5 VARCHAR(255),
	FIELD6 VARCHAR(255), FIELD7 VARCHAR(255),
	FIELD8 VARCHAR(255), FIELD9 VARCHAR(255)
);
```
However, I wonder what the performance impact would be by defining huge VARCHAR lengths. 
Also unlike #1381 I don't see any deadlocks during `'run`

`.\bin\ycsb2.bat run jdbc -P .\workloads\workloada -P .\jdbc\src\main\conf\db.properties -p recordcount=1000 -p operationcount=1000 -threads 6`

```
[OVERALL], RunTime(ms), 1970
[OVERALL], Throughput(ops/sec), 507.61421319796955
[TOTAL_GCS_PS_Scavenge], Count, 0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0
[READ], Operations, 520
[READ], AverageLatency(us), 6174.848076923077
[READ], MinLatency(us), 1024
[READ], MaxLatency(us), 118527
[READ], 95thPercentileLatency(us), 9567
[READ], 99thPercentileLatency(us), 117119
[READ], Return=OK, 520
[CLEANUP], Operations, 6
[CLEANUP], AverageLatency(us), 160.0
[CLEANUP], MinLatency(us), 101
[CLEANUP], MaxLatency(us), 348
[CLEANUP], 95thPercentileLatency(us), 348
[CLEANUP], 99thPercentileLatency(us), 348
[UPDATE], Operations, 480
[UPDATE], AverageLatency(us), 6382.164583333333
[UPDATE], MinLatency(us), 2238
[UPDATE], MaxLatency(us), 26095
[UPDATE], 95thPercentileLatency(us), 10119
[UPDATE], 99thPercentileLatency(us), 21519
[UPDATE], Return=OK, 480
```

**Comment by VinayBanakar** [comment]
@busbey What cis the minimum length of YCSB_KEY and FIELD that would be required?
