### ISSUE TITLE
Elasticsearch remote mode has NoNodeAvailableException Error

### ISSUE THREAD

**Issue by akshayraj17** [brianfrankcooper/YCSB#1408]
I am trying to use YCSB to benchmark Elasticsearch.
Here is the node I am trying to test:
[root@elasticsearch-n1 ~]# curl '10.0.3.5:9200'
{
  "name" : "elasticsearch-n1",
  "cluster_name" : "ycsb-elastic",
  "cluster_uuid" : "cyZyZnCBRrWfZUjx2QXSbg",
  "version" : {
    "number" : "7.6.0",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "7f634e9f44834fbc12724506cc1da681b0c3b1e3",
    "build_date" : "2020-02-06T00:09:00.449973Z",
    "build_snapshot" : false,
    "lucene_version" : "8.4.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

Here is what happens when I run it 
[ycsb@elastic-ycsb ycsb-0.17.0]$ ${YCSB_HOME}/bin/ycsb load elasticsearch -s -threads 1 -P workloads/workloadc -p recordcount=100000 -p es.remote=true -p es.hosts.list=10.0.3.5:9200 -p cluster.name=ycsb-elastic -p path.home=/elasticsearch/data/
/opt/JAVA/jdk1.8.0_211/bin/java -cp /ycsb/ycsb-0.17.0/elasticsearch-binding/conf:/ycsb/ycsb-0.17.0/conf:/ycsb/ycsb-0.17.0/lib/core-0.17.0.jar:/ycsb/ycsb-0.17.0/lib/htrace-core4-4.1.0-incubating.jar:/ycsb/ycsb-0.17.0/lib/jackson-mapper-asl-1.9.4.jar:/ycsb/ycsb-0.17.0/lib/jackson-core-asl-1.9.4.jar:/ycsb/ycsb-0.17.0/lib/HdrHistogram-2.1.4.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/commons-cli-1.3.1.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/elasticsearch-2.4.0.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/HdrHistogram-2.1.4.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/securesm-1.0.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-core-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/guava-18.0.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-sandbox-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/joda-convert-1.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-misc-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/jackson-dataformat-smile-2.8.1.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-backward-codecs-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-grouping-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/jackson-dataformat-cbor-2.8.1.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-memory-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-join-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/jackson-core-2.8.1.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/snakeyaml-1.15.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/jackson-dataformat-yaml-2.8.1.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/t-digest-3.0.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/jna-4.1.0.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-spatial-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/netty-3.10.6.Final.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/hppc-0.7.1.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/spatial4j-0.5.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-queryparser-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/jsr166e-1.1.0.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/compress-lzf-1.0.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-queries-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-suggest-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/joda-time-2.9.4.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-analyzers-common-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-spatial3d-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/lucene-highlighter-5.5.2.jar:/ycsb/ycsb-0.17.0/elasticsearch-binding/lib/elasticsearch-binding-0.17.0.jar site.ycsb.Client -db site.ycsb.db.ElasticsearchClient -s -threads 1 -P workloads/workloadc -p recordcount=100000 -p es.remote=true -p es.hosts.list=10.0.3.5:9200 -p cluster.name=ycsb-elastic -p path.home=/elasticsearch/data/ -load
Command line: -db site.ycsb.db.ElasticsearchClient -s -threads 1 -P workloads/workloadc -p recordcount=100000 -p es.remote=true -p es.hosts.list=10.0.3.5:9200 -p cluster.name=ycsb-elastic -p path.home=/elasticsearch/data/ -load
YCSB Client 0.17.0

Loading workload...
Starting test.
2020-02-21 14:08:13:657 0 sec: 0 operations; est completion in 0 second
Elasticsearch starting node = ycsb-elastic
Elasticsearch node path.home = /elasticsearch/data/
Elasticsearch Remote Mode = true
Elasticsearch Remote Hosts = 10.0.3.5:9200
Feb 21, 2020 2:08:13 PM org.elasticsearch.plugins.PluginsService <init>
INFO: [Erik Josten] modules [], plugins [], sites []
2020-02-21 14:08:23:639 10 sec: 0 operations; est completion in 106751991167300 days 15 hours
2020-02-21 14:08:33:639 20 sec: 0 operations; est completion in 106751991167300 days 15 hours
2020-02-21 14:08:43:639 30 sec: 0 operations; est completion in 106751991167300 days 15 hours
Feb 21, 2020 2:08:44 PM org.elasticsearch.client.transport.TransportClientNodesService$SniffNodesSampler$1$1 handleException
INFO: [Erik Josten] failed to get local cluster state for {#transport#-1}{10.0.3.5}{10.0.3.5:9200}, disconnecting...
ReceiveTimeoutTransportException[[][10.0.3.5:9200][cluster:monitor/state] request_id [0] timed out after [30001ms]]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:696)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Exception in thread "Thread-3" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{10.0.3.5}{10.0.3.5:9200}]]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1221)
        at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1241)
        at site.ycsb.db.ElasticsearchClient.init(ElasticsearchClient.java:149)
        at site.ycsb.DBWrapper.init(DBWrapper.java:86)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.lang.Thread.run(Thread.java:748)
2020-02-21 14:08:44:195 30 sec: 0 operations; est completion in 106751991167300 days 15 hours
[OVERALL], RunTime(ms), 30555
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 1
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 25
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.08181966944853543
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 25
[TOTAL_GC_TIME_%], Time(%), 0.08181966944853543

**Comment by Lumotheninja** [comment]
are you using elasticsearch module, iirc elasticsearch only supports up to ES3
