### ISSUE TITLE
failed to load workload [voldemort-bingding]

### ISSUE THREAD

**Issue by kasaciyo** [brianfrankcooper/YCSB#1414]
I use "bin/ycsb.sh load basic -P workloads/workloada" and face following errors,
three versions of htrace are included by maven, htrace,htrace-core, htrace-core4. 
are there any conflicts of those packages or the problems of env?

> Command line: -load -db site.ycsb.BasicDB -P workloads/workloada
> YCSB Client 0.17.0
> 
> Loading workload...
> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/htrace/core/Tracer$Builder
>         at site.ycsb.Client.getTracer(Client.java:458)
>         at site.ycsb.Client.main(Client.java:304)
> Caused by: java.lang.ClassNotFoundException: org.apache.htrace.core.Tracer$Builder
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
>         ... 2 more
>  (might take a few minutes for large data sets)

**Comment by busbey** [comment]
What version of ycsb are you trying to use?

**Comment by laulee5135** [comment]
I also encountered the same problem, both 0.17.0 and the latest. But running 0.17.0.jar is normal,Is there any temporary solution, thanks.

**Comment by laulee5135** [comment]
Already resolved ~.
