### ISSUE TITLE
Ruuning YCSB benchmark getting "Error inserting key: user" 

### ISSUE THREAD

**Issue by Boopalanmani** [brianfrankcooper/YCSB#1417]
Hi Team,

I have created a new table and run the benchmark profile.

Cassandra version: [cqlsh 5.0.1 | Cassandra 3.11.6 | CQL spec 3.4.4 | Native protocol v4]
Java version: openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
YCSB: 0.17.0

**Table:**
cqlsh:ycsb> desc usertable

CREATE TABLE ycsb.usertable (
    y_id text PRIMARY KEY,
    fiel20 text,
    field0 text,
    field1 text,
    field3 text,
    field4 text,
    field5 text,
    field6 text,
    field7 text,
    field8 text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

 **Error in YCSB:**

[root@node-a ycsb-0.17.0]# bin/ycsb load cassandra-cql -p hosts=127.0.0.1 -s -P workloads/workloada
java -cp /root/ycsb-0.17.0/cassandra-binding/conf:/root/ycsb-0.17.0/conf:/root/ycsb-0.17.0/lib/core-0.17.0.jar:/root/ycsb-0.17.0/lib/htrace-core4-4.1.0-incubating.jar:/root/ycsb-0.17.0/lib/jackson-mapper-asl-1.9.4.jar:/root/ycsb-0.17.0/lib/jackson-core-asl-1.9.4.jar:/root/ycsb-0.17.0/lib/HdrHistogram-2.1.4.jar:/root/ycsb-0.17.0/lib/slf4j-api-1.7.30.jar:/root/ycsb-0.17.0/lib/slf4j-jdk14-1.7.30.jar:/root/ycsb-0.17.0/lib/slf4j-simple-1.7.30.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-common-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-transport-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/slf4j-api-1.7.25.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-codec-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-buffer-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/cassandra-driver-core-3.0.0.jar:/root/ycsb-0.17.0/cassandra-binding/lib/netty-handler-4.0.33.Final.jar:/root/ycsb-0.17.0/cassandra-binding/lib/metrics-core-3.1.2.jar:/root/ycsb-0.17.0/cassandra-binding/lib/guava-16.0.1.jar:/root/ycsb-0.17.0/cassandra-binding/lib/cassandra-binding-0.17.0.jar site.ycsb.Client -db site.ycsb.db.CassandraCQLClient -p hosts=127.0.0.1 -s -P workloads/workloada -load
Command line: -db site.ycsb.db.CassandraCQLClient -p hosts=127.0.0.1 -s -P workloads/workloada -load
YCSB Client 0.17.0

Loading workload...
Starting test.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/ycsb-0.17.0/lib/slf4j-jdk14-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/ycsb-0.17.0/lib/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
2020-03-28 11:41:30:909 0 sec: 0 operations; est completion in 0 second 
Mar 28, 2020 11:41:31 AM com.datastax.driver.core.NettyUtil <clinit>
INFO: Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
Mar 28, 2020 11:41:31 AM com.datastax.driver.core.policies.DCAwareRoundRobinPolicy init
INFO: Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
Mar 28, 2020 11:41:31 AM com.datastax.driver.core.Cluster$Manager init
INFO: New Cassandra host /127.0.0.1:9042 added
Mar 28, 2020 11:41:31 AM site.ycsb.db.CassandraCQLClient init
INFO: Connected to cluster: Test Cluster

Mar 28, 2020 11:41:31 AM site.ycsb.db.CassandraCQLClient init
INFO: Datacenter: datacenter1; Host: /127.0.0.1; Rack: rack1

DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Mar 28, 2020 11:41:31 AM site.ycsb.db.CassandraCQLClient insert
SEVERE: Error inserting key: user6284781860667377211
com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name field9
	at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.AbstractSession.prepare(AbstractSession.java:110)
	at site.ycsb.db.CassandraCQLClient.insert(CassandraCQLClient.java:557)
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221)
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601)
	at site.ycsb.ClientThread.run(ClientThread.java:135)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name field9
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:136)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
	at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861)
	at com.google.common.util.concurrent.MoreExecutors$SameThreadExecutorService.execute(MoreExecutors.java:297)
	at com.google.common.util.concurrent.ExecutionList.executeListener(ExecutionList.java:156)
	at com.google.common.util.concurrent.ExecutionList.execute(ExecutionList.java:145)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:185)
	at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1174)
	at com.datastax.driver.core.Connection$Future.onSet(Connection.java:1168)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:184)
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:798)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:617)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1005)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:928)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	... 1 more

Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
2020-03-28 11:41:33:792 2 sec: 0 operations; est completion in 106751991167300 days 15 hours [CLEANUP: Count=1, Max=2242559, Min=2240512, Avg=2241536, 90=2242559, 99=2242559, 99.9=2242559, 99.99=2242559] [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=?, 90=0, 99=0, 99.9=0, 99.99=0] [INSERT-FAILED: Count=1, Max=11383, Min=11376, Avg=11380, 90=11383, 99=11383, 99.9=11383, 99.99=11383] 
[OVERALL], RunTime(ms), 2906
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 1
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 7
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.24088093599449414
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 7
[TOTAL_GC_TIME_%], Time(%), 0.24088093599449414
[CLEANUP], Operations, 1
[CLEANUP], AverageLatency(us), 2241536.0
[CLEANUP], MinLatency(us), 2240512
[CLEANUP], MaxLatency(us), 2242559
[CLEANUP], 95thPercentileLatency(us), 2242559
[CLEANUP], 99thPercentileLatency(us), 2242559
[INSERT], Operations, 0
[INSERT], AverageLatency(us), NaN
[INSERT], MinLatency(us), 9223372036854775807
[INSERT], MaxLatency(us), 0
[INSERT], 95thPercentileLatency(us), 0
[INSERT], 99thPercentileLatency(us), 0
[INSERT], Return=ERROR, 1
[INSERT-FAILED], Operations, 1
[INSERT-FAILED], AverageLatency(us), 11380.0
[INSERT-FAILED], MinLatency(us), 11376
[INSERT-FAILED], MaxLatency(us), 11383
[INSERT-FAILED], 95thPercentileLatency(us), 11383
[INSERT-FAILED], 99thPercentileLatency(us), 11383

**Comment by busbey** [comment]
Your create statement is incorrect. The error mentions a failure to write to `field9` and your create doesn't include that field.

Please follow the instructions in the README for the Cassandra binding.

**Comment by Boopalanmani** [comment]
Thanks busbey and its worked now

**Comment by Boopalanmani** [comment]
We want to validate our SSD storage with YCSB benchmarking, Could you please let us know what the configuration to be made for Single Node.

Steps followed:
I have created a filesystem on our SSD and ext4 file system, then mount in /mnt 

**Edit the config file**
/mnt/data
/mnt/commitlog
/mnt/cdc_raw
/mnt/hints
/mnt/saved_caches

**Create Table:**
cqlsh:ycsb> DESC keyspace

CREATE KEYSPACE ycsb WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE ycsb.usertable (
    y_id text PRIMARY KEY,
    field0 text,
    field1 text,
    field2 text,
    field3 text,
    field4 text,
    field5 text,
    field6 text,
    field7 text,
    field8 text,
    field9 text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy', 'max_threshold': '32', 'min_threshold': '4'}
    AND compression = {'chunk_length_in_kb': '64', 'class': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';

**YCSB Workload A Run:**
[root@node-master YCSB]# bin/ycsb run cassandra-cql -p hosts=127.0.0.1 -s -P workloads/workloada -threads 16
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:cassandra-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
/usr/lib/jvm/jre-1.8.0-openjdk/bin/java -cp /root/YCSB/cassandra/conf:/root/YCSB/cassandra/target/cassandra-binding-0.18.0-SNAPSHOT.jar:/root/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/root/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/root/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar:/root/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/root/.m2/repository/com/datastax/cassandra/cassandra-driver-core/3.0.0/cassandra-driver-core-3.0.0.jar:/root/.m2/repository/io/netty/netty-handler/4.0.33.Final/netty-handler-4.0.33.Final.jar:/root/.m2/repository/org/slf4j/slf4j-log4j12/1.7.30/slf4j-log4j12-1.7.30.jar:/root/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/root/YCSB/core/target/core-0.18.0-SNAPSHOT.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar:/root/.m2/repository/io/netty/netty-transport/4.0.33.Final/netty-transport-4.0.33.Final.jar:/root/.m2/repository/io/netty/netty-codec/4.0.33.Final/netty-codec-4.0.33.Final.jar:/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar:/root/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/root/.m2/repository/io/netty/netty-buffer/4.0.33.Final/netty-buffer-4.0.33.Final.jar:/root/.m2/repository/io/netty/netty-common/4.0.33.Final/netty-common-4.0.33.Final.jar site.ycsb.Client -db site.ycsb.db.CassandraCQLClient -p hosts=127.0.0.1 -s -P workloads/workloada -threads 16 -t
Command line: -db site.ycsb.db.CassandraCQLClient -p hosts=127.0.0.1 -s -P workloads/workloada -threads 16 -t
YCSB Client 0.18.0-SNAPSHOT

Loading workload...
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
2020-04-08 10:25:34:154 0 sec: 0 operations; est completion in 0 second 
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2020-04-08 10:25:37:237 3 sec: 1000 operations; 320.72 current ops/sec; [READ: Count=507, Max=61567, Min=479, Avg=2711.51, 90=3723, 99=39295, 99.9=61439, 99.99=61567] [CLEANUP: Count=16, Max=2238463, Min=1, Avg=139841.5, 90=1, 99=2238463, 99.9=2238463, 99.99=2238463] [UPDATE: Count=493, Max=38239, Min=433, Avg=2699.89, 90=3539, 99=37759, 99.9=38239, 99.99=38239] 
[OVERALL], RunTime(ms), 3118
[OVERALL], Throughput(ops/sec), 320.7184092366902
[TOTAL_GCS_PS_Scavenge], Count, 1
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 10
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.3207184092366902
[TOTAL_GCS_PS_MarkSweep], Count, 0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 10
[TOTAL_GC_TIME_%], Time(%), 0.3207184092366902
[READ], Operations, 507
[READ], AverageLatency(us), 2711.5108481262328
[READ], MinLatency(us), 479
[READ], MaxLatency(us), 61567
[READ], 95thPercentileLatency(us), 4187
[READ], 99thPercentileLatency(us), 39295
[READ], Return=OK, 507
[CLEANUP], Operations, 16
[CLEANUP], AverageLatency(us), 139841.5
[CLEANUP], MinLatency(us), 1
[CLEANUP], MaxLatency(us), 2238463
[CLEANUP], 95thPercentileLatency(us), 10
[CLEANUP], 99thPercentileLatency(us), 2238463
[UPDATE], Operations, 493
[UPDATE], AverageLatency(us), 2699.8904665314403
[UPDATE], MinLatency(us), 433
[UPDATE], MaxLatency(us), 38239
[UPDATE], 95thPercentileLatency(us), 3843
[UPDATE], 99thPercentileLatency(us), 37759
[UPDATE], Return=OK, 493

Could you please verify the result and suggest to maximize the throughtput.

**Comment by Boopalanmani** [comment]
Can you please help anyone in above query
