### ISSUE TITLE
site.ycsb.DBException: java.lang.NullPointerException during memcached connection

### ISSUE THREAD

**Issue by GrayXu** [brianfrankcooper/YCSB#1420]
```
$ ./bin/ycsb load memcached -s -P workloads/workloada > outputLoad.txt
java -cp /root/ycsb-0.17.0/memcached-binding/conf:/root/ycsb-0.17.0/conf:/root/ycsb-0.17.0/lib/core-0.17.0.jar:/root/ycsb-0.17.0/lib/HdrHistogram-2.
1.4.jar:/root/ycsb-0.17.0/lib/htrace-core4-4.1.0-incubating.jar:/root/ycsb-0.17.0/lib/jackson-core-asl-1.9.4.jar:/root/ycsb-0.17.0/lib/jackson-mappe
r-asl-1.9.4.jar:/root/ycsb-0.17.0/memcached-binding/lib/core-0.17.0.jar:/root/ycsb-0.17.0/memcached-binding/lib/log4j-1.2.17.jar:/root/ycsb-0.17.0/m
emcached-binding/lib/HdrHistogram-2.1.4.jar:/root/ycsb-0.17.0/memcached-binding/lib/htrace-core4-4.1.0-incubating.jar:/root/ycsb-0.17.0/memcached-bi
nding/lib/jackson-core-asl-1.9.4.jar:/root/ycsb-0.17.0/memcached-binding/lib/spymemcached-2.11.4.jar:/root/ycsb-0.17.0/memcached-binding/lib/jackson
-mapper-asl-1.9.13.jar:/root/ycsb-0.17.0/memcached-binding/lib/memcached-binding-0.17.0.jar site.ycsb.Client -db site.ycsb.db.MemcachedClient -s -P
workloads/workloada -load
Command line: -db site.ycsb.db.MemcachedClient -s -P workloads/workloada -load
YCSB Client 0.17.0

Loading workload...
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
2020-04-22 17:41:37:112 0 sec: 0 operations; est completion in 0 second
site.ycsb.DBException: java.lang.NullPointerException
        at site.ycsb.db.MemcachedClient.init(MemcachedClient.java:133)
        at site.ycsb.DBWrapper.init(DBWrapper.java:86)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at site.ycsb.db.MemcachedClient.createMemcachedClient(MemcachedClient.java:165)
        at site.ycsb.db.MemcachedClient.init(MemcachedClient.java:122)
        ... 3 more
2020-04-22 17:41:37:125 0 sec: 0 operations; est completion in 106751991167300 days 15 hours
```

latest release of YCSB, openjdk 8, py 2.7.12  
memcached server is running correctly, and can be connected by telnet.  

I tried example commands in [`memcached/readme.md`](https://github.com/brianfrankcooper/YCSB/tree/master/memcached#4-load-data-and-run-tests), but it failed.😢

thanks for help

**Comment by GrayXu** [comment]
fix it by adding `-p memcached.hosts=...`
