### ISSUE TITLE
com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified

### ISSUE THREAD

**Issue by magaofeng2010** [brianfrankcooper/YCSB#1432]
hi，i get a error  

the ycsb version i used : ycsb-0.17.0.tar.gz
the mongo version i used:  mongodb-linux-x86_64-rhel62-4.2.6
my mongo server is in shard mode 
the error infomations is below，who can help me  , thanks
```
D:\program\ycsb-0.17.0>"C:\Program Files\Java\jdk1.8.0_144\bin\java.exe"  -classpath "D:\program\ycsb-0.17.0\conf;D:\program\ycsb-0.17.0\lib\core-0.17.0.jar;D:\program\ycsb-0.17.0\lib\HdrHistogram-2.1.4.jar;D:\program\ycsb-0.17.0\lib\htrace-core4-4.1.0-incubating.jar;D:\program\ycsb-0.17.0\lib\jackson-core-asl-1.9.4.jar;D:\program\ycsb-0.17.0\lib\jackson-mapper-asl-1.9.4.jar;D:\program\ycsb-0.17.0\mongodb-binding\lib\logback-classic-1.1.2.jar;D:\program\ycsb-0.17.0\mongodb-binding\lib\logback-core-1.1.2.jar;D:\program\ycsb-0.17.0\mongodb-binding\lib\mongo-java-driver-3.8.0.jar;D:\program\ycsb-0.17.0\mongodb-binding\lib\mongodb-async-driver-2.0.1.jar;D:\program\ycsb-0.17.0\mongodb-binding\lib\mongodb-binding-0.17.0.jar;D:\program\ycsb-0.17.0\mongodb-binding\lib\slf4j-api-1.7.25.jar;D:\program\ycsb-0.17.0\mongodb-binding\lib\snappy-java-1.1.7.1.jar" site.ycsb.Client -load -db site.ycsb.db.AsyncMongoDbClient -s -P workloads/workloada -p mongodb.url=mongodb://test:test@10.13.1.111:9420/ycsb 
mongo connection created with mongodb://test:test@10.13.1.111:9420/ycsb
17:19:04.751 [Thread-3] WARN  c.a.m.c.c.a.AuthenticatingConnection - Authentication failed: []
com.allanbank.mongodb.error.MongoDbAuthenticationException: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:123) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.ensureAuthenticated(AuthenticatingConnection.java:181) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.send(AuthenticatingConnection.java:133) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.bootstrap(BootstrapConnectionFactory.java:179) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.createDelegate(BootstrapConnectionFactory.java:290) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getDelegate(BootstrapConnectionFactory.java:268) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getClusterStats(BootstrapConnectionFactory.java:114) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.ClientImpl.getClusterStats(ClientImpl.java:199) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.doInsertAsync(AbstractMongoOperations.java:1037) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.insertAsync(AbstractMongoOperations.java:583) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractAsyncMongoCollection.insertAsync(AbstractAsyncMongoCollection.java:1255) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:684) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:722) [mongodb-async-driver-2.0.1.jar:na]
	at site.ycsb.db.AsyncMongoDbClient.insert(AsyncMongoDbClient.java:272) [mongodb-binding-0.17.0.jar:na]
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221) [core-0.17.0.jar:na]
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601) [core-0.17.0.jar:na]
	at site.ycsb.ClientThread.run(ClientThread.java:135) [core-0.17.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.util.concurrent.ExecutionException: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.FutureCallback$Sync.getValue(FutureCallback.java:581) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback$Sync.get(FutureCallback.java:489) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback.get(FutureCallback.java:223) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:117) ~[mongodb-async-driver-2.0.1.jar:na]
	... 17 common frames omitted
Caused by: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:197) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:216) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:141) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:112) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.checkForError(AbstractValidatingReplyCallback.java:244) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.verify(AbstractValidatingReplyCallback.java:298) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.callback(AbstractValidatingReplyCallback.java:90) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.callback(AbstractValidatingReplyCallback.java:51) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.ReplyHandler.run(ReplyHandler.java:127) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.ReplyHandler.reply(ReplyHandler.java:96) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.reply(AbstractSocketConnection.java:632) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.doReceiveOne(AbstractSocketConnection.java:509) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.ReceiveRunnable.run(ReceiveRunnable.java:59) ~[mongodb-async-driver-2.0.1.jar:na]
	... 1 common frames omitted
17:19:04.806 [Thread-3] WARN  c.a.m.c.c.a.AuthenticatingConnection - Authentication failed: []
com.allanbank.mongodb.error.MongoDbAuthenticationException: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:123) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.ensureAuthenticated(AuthenticatingConnection.java:181) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.send(AuthenticatingConnection.java:133) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.sharded.ShardedConnectionFactory.findMongosServers(ShardedConnectionFactory.java:334) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.sharded.ShardedConnectionFactory.update(ShardedConnectionFactory.java:392) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.sharded.ShardedConnectionFactory.bootstrap(ShardedConnectionFactory.java:120) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.sharded.ShardedConnectionFactory.<init>(ShardedConnectionFactory.java:105) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.bootstrapSharded(BootstrapConnectionFactory.java:249) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.bootstrap(BootstrapConnectionFactory.java:192) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.createDelegate(BootstrapConnectionFactory.java:290) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getDelegate(BootstrapConnectionFactory.java:268) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getClusterStats(BootstrapConnectionFactory.java:114) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.ClientImpl.getClusterStats(ClientImpl.java:199) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.doInsertAsync(AbstractMongoOperations.java:1037) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.insertAsync(AbstractMongoOperations.java:583) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractAsyncMongoCollection.insertAsync(AbstractAsyncMongoCollection.java:1255) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:684) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:722) [mongodb-async-driver-2.0.1.jar:na]
	at site.ycsb.db.AsyncMongoDbClient.insert(AsyncMongoDbClient.java:272) [mongodb-binding-0.17.0.jar:na]
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221) [core-0.17.0.jar:na]
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601) [core-0.17.0.jar:na]
	at site.ycsb.ClientThread.run(ClientThread.java:135) [core-0.17.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.util.concurrent.ExecutionException: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.FutureCallback$Sync.getValue(FutureCallback.java:581) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback$Sync.get(FutureCallback.java:489) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback.get(FutureCallback.java:223) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:117) ~[mongodb-async-driver-2.0.1.jar:na]
	... 22 common frames omitted
Caused by: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:197) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:216) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:141) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:112) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.checkForError(AbstractValidatingReplyCallback.java:244) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.verify(AbstractValidatingReplyCallback.java:298) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.callback(AbstractValidatingReplyCallback.java:90) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.callback(AbstractValidatingReplyCallback.java:51) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.ReplyHandler.run(ReplyHandler.java:127) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.ReplyHandler.reply(ReplyHandler.java:96) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.reply(AbstractSocketConnection.java:632) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.doReceiveOne(AbstractSocketConnection.java:509) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.ReceiveRunnable.run(ReceiveRunnable.java:59) ~[mongodb-async-driver-2.0.1.jar:na]
	... 1 common frames omitted
17:19:04.835 [Thread-3] WARN  c.a.m.c.c.a.AuthenticatingConnection - Authentication failed: []
com.allanbank.mongodb.error.MongoDbAuthenticationException: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:123) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.ensureAuthenticated(AuthenticatingConnection.java:181) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.send(AuthenticatingConnection.java:133) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.state.ClusterPinger$Pinger.pingAsync(ClusterPinger.java:452) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.state.ClusterPinger.initialSweep(ClusterPinger.java:199) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.sharded.ShardedConnectionFactory.bootstrap(ShardedConnectionFactory.java:152) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.sharded.ShardedConnectionFactory.<init>(ShardedConnectionFactory.java:105) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.bootstrapSharded(BootstrapConnectionFactory.java:249) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.bootstrap(BootstrapConnectionFactory.java:192) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.createDelegate(BootstrapConnectionFactory.java:290) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getDelegate(BootstrapConnectionFactory.java:268) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getClusterStats(BootstrapConnectionFactory.java:114) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.ClientImpl.getClusterStats(ClientImpl.java:199) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.doInsertAsync(AbstractMongoOperations.java:1037) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.insertAsync(AbstractMongoOperations.java:583) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractAsyncMongoCollection.insertAsync(AbstractAsyncMongoCollection.java:1255) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:684) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:722) [mongodb-async-driver-2.0.1.jar:na]
	at site.ycsb.db.AsyncMongoDbClient.insert(AsyncMongoDbClient.java:272) [mongodb-binding-0.17.0.jar:na]
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221) [core-0.17.0.jar:na]
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601) [core-0.17.0.jar:na]
	at site.ycsb.ClientThread.run(ClientThread.java:135) [core-0.17.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.util.concurrent.ExecutionException: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.FutureCallback$Sync.getValue(FutureCallback.java:581) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback$Sync.get(FutureCallback.java:489) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback.get(FutureCallback.java:223) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:117) ~[mongodb-async-driver-2.0.1.jar:na]
	... 22 common frames omitted
Caused by: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:197) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:216) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:141) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:112) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.checkForError(AbstractValidatingReplyCallback.java:244) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.verify(AbstractValidatingReplyCallback.java:298) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.callback(AbstractValidatingReplyCallback.java:90) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.callback(AbstractValidatingReplyCallback.java:51) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.ReplyHandler.run(ReplyHandler.java:127) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.ReplyHandler.reply(ReplyHandler.java:96) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.reply(AbstractSocketConnection.java:632) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.doReceiveOne(AbstractSocketConnection.java:509) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.ReceiveRunnable.run(ReceiveRunnable.java:59) ~[mongodb-async-driver-2.0.1.jar:na]
	... 1 common frames omitted
17:19:04.870 [Thread-3] WARN  c.a.m.c.c.a.AuthenticatingConnection - Authentication failed: []
com.allanbank.mongodb.error.MongoDbAuthenticationException: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:123) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.ensureAuthenticated(AuthenticatingConnection.java:181) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.send(AuthenticatingConnection.java:133) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.proxy.AbstractProxyMultipleConnection.doSend(AbstractProxyMultipleConnection.java:450) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.proxy.AbstractProxyMultipleConnection.trySend(AbstractProxyMultipleConnection.java:625) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.proxy.AbstractProxyMultipleConnection.send(AbstractProxyMultipleConnection.java:287) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.proxy.AbstractProxyMultipleConnection.send(AbstractProxyMultipleConnection.java:305) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractClient.send(AbstractClient.java:93) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.BatchedWriteCallback.send(BatchedWriteCallback.java:222) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.doWriteAsync(AbstractMongoOperations.java:1099) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.doInsertAsync(AbstractMongoOperations.java:1043) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.insertAsync(AbstractMongoOperations.java:583) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractAsyncMongoCollection.insertAsync(AbstractAsyncMongoCollection.java:1255) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:684) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:722) [mongodb-async-driver-2.0.1.jar:na]
	at site.ycsb.db.AsyncMongoDbClient.insert(AsyncMongoDbClient.java:272) [mongodb-binding-0.17.0.jar:na]
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221) [core-0.17.0.jar:na]
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601) [core-0.17.0.jar:na]
	at site.ycsb.ClientThread.run(ClientThread.java:135) [core-0.17.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
Caused by: java.util.concurrent.ExecutionException: com.allanbank.mongodb.error.ReplyException: Auth mechanism not specified
	at com.allanbank.mongodb.client.FutureCallback$Sync.getValue(FutureCallback.java:581) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback$Sync.get(FutureCallback.java:489) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback.get(FutureCallback.java:223) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:117) ~[mongodb-async-driver-2.0.1.jar:na]
	... 19 common frames omitted
```

**Comment by busbey** [comment]
Try using the official mongodb client instead of the async one
