### ISSUE TITLE
memcached+YCSB occurs NullPointerException

### ISSUE THREAD

**Issue by mesunyyam** [brianfrankcooper/YCSB#1435]
Hello, I want to test memcached using YCSB.
I installed memcached from source and start it using following commands

$ /usr/local/memcached/bin/memcached -u root -d -l 127.0.0.1 -p 11211"

then, I load YCSB using following commands
(I got ycsb by "curl -O --location https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-0.17.0.tar.gz")

$ ./bin/ycsb load memcached -P workloads/workloada -p memcached.host=127.0.0.1

However, It occurs me error as followings

Loading workload...
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
site.ycsb.DBException: java.lang.NullPointerException
        at site.ycsb.db.MemcachedClient.init(MemcachedClient.java:133)
        at site.ycsb.DBWrapper.init(DBWrapper.java:86)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
        at site.ycsb.db.MemcachedClient.createMemcachedClient(MemcachedClient.java:165)
        at site.ycsb.db.MemcachedClient.init(MemcachedClient.java:122)
        ... 3 more
site.ycsb.DBException: java.lang.NullPointerException
        at site.ycsb.db.MemcachedClient.init(MemcachedClient.java:133)
        at site.ycsb.DBWrapper.init(DBWrapper.java:86)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
        at site.ycsb.db.MemcachedClient.createMemcachedClient(MemcachedClient.java:165)
        at site.ycsb.db.MemcachedClient.init(MemcachedClient.java:122)
        ... 3 more
[OVERALL], RunTime(ms), 7
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_G1_Young_Generation], Count, 0
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 0.0
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0

Is there any procedure that I missed?
I searched this error but I didn't get any solution.

Also, I thought this problem might be caused by pre-built ycsb, so I tried to build YCSB from source.
But, "mvn clean package" cause me errors even if I use maven version 3.6.0.

Is there any way that I can try to solve the problem (NullPointerException)?

**Comment by mesunyyam** [comment]
memcached with "-u memcached" worked well.

**Comment by mesunyyam** [comment]
I used "memcached -u memcached -d -l 127.0.0.1 -p 11211", but still got same error
