### ISSUE TITLE
OrientDB connection to docker not working

### ISSUE THREAD

**Issue by tgeis02** [brianfrankcooper/YCSB#1446]
Hi,

first of all thanks for your YCSB Benchmark and all your voluntary work. I am desperately trying to benchmark OrientDB with YCSB and came to a point where I need your help.

I set up OrientDB via docker container (docker compose), everything is working fine. I can access the server through localhost:2480, create databases, log in with them, change stuff, create stuff, etc.

```
orientdb:
    image: orientdb:latest
    environment:
      - ORIENTDB_ROOT_PASSWORD=root
    ports:
      - '2480:2480'
      - '2424:2424'
    volumes:
      - "orient-data:/orientdb/databases"
```

When executing YCSB, I use the following code to load data into OrientDB:

```
./bin/ycsb load orientdb -s -P workloads/workloada -p orientdb.url=remote:localhost:2424/ycsb -p orientdb.user=root -p orientdb.password=root -p orientdb.remote.storagetype=plocal -p orientdb.newdb=true
```

I can see in the OrientDB docker log, that a new ycsb database is created:

```
orientdb_1       | 2020-07-27 09:48:53:737 INFO  Dropped database 'ycsb' [OConnectionBinaryExecutor]
orientdb_1       | 2020-07-27 09:48:53:745 INFO  Direct IO for WAL located in /orientdb/databases/ycsb is allowed with block size 4096 bytes. [OCASDiskWriteAheadLog]
orientdb_1       | 2020-07-27 09:48:53:746 INFO  Page size for WAL located in /orientdb/databases/ycsb is set to 4096 bytes. [OCASDiskWriteAheadLog]
orientdb_1       | 2020-07-27 09:48:53:790 INFO  Storage 'plocal:/orientdb/databases/ycsb' is created under OrientDB distribution : 3.0.30 - Veloce (build eae50981ca31c79c85e4524fb376fced313acc23, branch UNKNOWN) [OLocalPaginatedStorage]
```

I can also see the newly created database in the GUI under localhost:2480. So there must be some connection to my database on the container. But nothing is inserted and there are several errors occuring.

```
2020-07-27 11:48:53 INFO  OrientDBClient:94 - OrientDB loading database url = remote:localhost:2424/ycsb
Warning: Nashorn engine is planned to be removed from a future JDK release
Juli 27, 2020 11:48:53 AM com.orientechnologies.common.log.OLogManager log
WARNING: The Client driver version is different than Server version: client=36, server=37. You could not use the full features of the newer version. Assure to have the same versions on both
2020-07-27 11:48:53 INFO  OrientDBClient:132 - OrientDB drop and recreate fresh db
2020-07-27 11:48:54 ERROR OrientDBClient:169 - Could not initialize OrientDB connection pool for Loader: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database url=remote:localhost:2424/ycsb
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database url=remote:localhost:2424/ycsb
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:295)
	at site.ycsb.db.OrientDBClient.init(OrientDBClient.java:153)
	at site.ycsb.DBWrapper.init(DBWrapper.java:86)
	at site.ycsb.ClientThread.run(ClientThread.java:91)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NumberFormatException: For input string: "nothing"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.fromStream(OStorageConfigurationImpl.java:517)
	at com.orientechnologies.orient.core.config.OStorageConfigurationImpl.load(OStorageConfigurationImpl.java:218)
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:369)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:259)
	... 4 more
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
java.lang.NullPointerException
	at site.ycsb.db.OrientDBClient.insert(OrientDBClient.java:199)
	at site.ycsb.DBWrapper.insert(DBWrapper.java:221)
	at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601)
	at site.ycsb.ClientThread.run(ClientThread.java:135)
	at java.base/java.lang.Thread.run(Thread.java:832)
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
Exception in thread "Thread-2" java.lang.NullPointerException
	at site.ycsb.db.OrientDBClient.cleanup(OrientDBClient.java:187)
	at site.ycsb.DBWrapper.cleanup(DBWrapper.java:114)
	at site.ycsb.ClientThread.run(ClientThread.java:152)
	at java.base/java.lang.Thread.run(Thread.java:832)
2020-07-27 11:48:54:583 1 sec: 0 operations; est completion in 106751991167300 days 15 hours [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=NaN, 90=0, 99=0, 99.9=0, 99.99=0] [INSERT-FAILED: Count=1, Max=1880, Min=1880, Avg=1880, 90=1880, 99=1880, 99.9=1880, 99.99=1880]
[OVERALL], RunTime(ms), 1333
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_G1_Young_Generation], Count, 1
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 3
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 0.22505626406601648
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 1
[TOTAL_GC_TIME], Time(ms), 3
[TOTAL_GC_TIME_%], Time(%), 0.22505626406601648
[INSERT], Operations, 0
[INSERT], AverageLatency(us), NaN
[INSERT], MinLatency(us), 9223372036854775807
[INSERT], MaxLatency(us), 0
[INSERT], 95thPercentileLatency(us), 0
[INSERT], 99thPercentileLatency(us), 0
[INSERT], Return=ERROR, 1
[INSERT-FAILED], Operations, 1
[INSERT-FAILED], AverageLatency(us), 1880.0
[INSERT-FAILED], MinLatency(us), 1880
[INSERT-FAILED], MaxLatency(us), 1880
[INSERT-FAILED], 95thPercentileLatency(us), 1880
[INSERT-FAILED], 99thPercentileLatency(us), 1880
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.orientechnologies.common.directmemory.OByteBufferPool (file:/Users/timgeisler/.m2/repository/com/orientechnologies/orientdb-core/2.2.37/orientdb-core-2.2.37.jar) to method sun.nio.ch.DirectBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.orientechnologies.common.directmemory.OByteBufferPool
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Similar docker setups were already done for ArangoDB, PostgreSQL, Oracle, MongoDB, Couchbase, Redis and Memcached. Everything is working fine with those databases, except OrientDB. I googled the problem for quite a while now and just can't help myself anymore. Can you help? Thanks in advance!

**Comment by busbey** [comment]
that failure is happening within the OrientDB client code, so it's going to be hard to track down. what version of the orientdb server are you using?

**Comment by tgeis02** [comment]
I am using the latest docker image, which is version 3.1.1
