### ISSUE TITLE
Runing YCSB against Redis cluster using 4 threads (works) and 8 threads (errors returned)

### ISSUE THREAD

**Issue by apaj** [brianfrankcooper/YCSB#1510]
Hi, thanks for putting YCSB together.

The environment is as follows: One Fedora 29 machine runs 32 Redis nodes (ports between 7001 and 7032), collected in a cluster - ip address of that Fedora is 172.16.0.2 Once CentOS 7 machine is supposed to run YCSB on that Redis cluster - ip address of that CentOS machine is 172.16.0.2. The CentOS machine lscpu says:
```
[centos@ip-192-168-4-205 YCSB]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
Stepping:              1
CPU MHz:               2700.366
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4600.02
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-7
```
Now, the load operation goes through without problems and the run goes fine as well, without using threads.
```
[centos@ip-192-168-4-205 YCSB]$ ./bin/ycsb run redis -s -P workloads/workloada -p operationcount=100000 -p "redis.host=172.16.0.2" -p "redis.port=7001" -p "redis.cluster=true" > outputRun.txt
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:redis-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
/usr/lib/jvm/jre-openjdk/bin/java -cp /home/centos/YCSB/redis/conf:/home/centos/YCSB/redis/target/redis-binding-0.18.0-SNAPSHOT.jar:/home/centos/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/centos/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/centos/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/centos/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar:/home/centos/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar:/home/centos/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/centos/YCSB/core/target/core-0.18.0-SNAPSHOT.jar site.ycsb.Client -db site.ycsb.db.RedisClient -s -P workloads/workloada -p operationcount=100000 -p redis.host=172.16.0.2 -p redis.port=7001 -p redis.cluster=true -t
Command line: -db site.ycsb.db.RedisClient -s -P workloads/workloada -p operationcount=100000 -p redis.host=172.16.0.2 -p redis.port=7001 -p redis.cluster=true -t
YCSB Client 0.18.0-SNAPSHOT

Loading workload...
Starting test.
2021-02-11 13:45:36:105 0 sec: 0 operations; est completion in 0 second 
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2021-02-11 13:45:46:083 10 sec: 668 operations; 66.8 current ops/sec; est completion in 24 minutes [READ: Count=330, Max=56255, Min=8808, Avg=11566.4, 90=11247, 99=43327, 99.9=56255, 99.99=56255] [UPDATE: Count=338, Max=42687, Min=11816, Avg=15771.62, 90=17215, 99=32415, 99.9=42687, 99.99=42687] 
```
etc...

When I add parameter threads 4, it still goes fine:
```
[centos@ip-192-168-4-205 YCSB]$ ./bin/ycsb run redis -s -P workloads/workloada -threads 4 -target 800 -p operationcount=100000 -p "redis.host=172.16.0.2" -p "redis.port=7001" -p "redis.cluster=true"  > outputRun.txt
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:redis-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
/usr/lib/jvm/jre-openjdk/bin/java -cp /home/centos/YCSB/redis/conf:/home/centos/YCSB/redis/target/redis-binding-0.18.0-SNAPSHOT.jar:/home/centos/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/centos/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/centos/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/centos/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar:/home/centos/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar:/home/centos/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/centos/YCSB/core/target/core-0.18.0-SNAPSHOT.jar site.ycsb.Client -db site.ycsb.db.RedisClient -s -P workloads/workloada -threads 4 -target 800 -p operationcount=100000 -p redis.host=172.16.0.2 -p redis.port=7001 -p redis.cluster=true -t
Command line: -db site.ycsb.db.RedisClient -s -P workloads/workloada -threads 4 -target 800 -p operationcount=100000 -p redis.host=172.16.0.2 -p redis.port=7001 -p redis.cluster=true -t
YCSB Client 0.18.0-SNAPSHOT

Loading workload...
Starting test.
2021-02-11 13:47:21:769 0 sec: 0 operations; est completion in 0 second 
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
2021-02-11 13:47:31:744 10 sec: 1547 operations; 154.7 current ops/sec; est completion in 10 minutes [READ: Count=792, Max=219903, Min=8744, Avg=16506.07, 90=25375, 99=65119, 99.9=187775, 99.99=219903] [UPDATE: Count=757, Max=232447, Min=13264, Avg=22111.15, 90=30719, 99=64031, 99.9=121151, 99.99=232447]
```
etc...

However, if I increase the number of threads to 8, I get the following errors:
```
[centos@ip-192-168-4-205 YCSB]$ ./bin/ycsb run redis -s -P workloads/workloada -threads 8 -target 800 -p operationcount=100000 -p "redis.host=172.16.0.2" -p "redis.port=7001" -p "redis.clust
er=true"  > outputRun.txt
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:redis-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
/usr/lib/jvm/jre-openjdk/bin/java -cp /home/centos/YCSB/redis/conf:/home/centos/YCSB/redis/target/redis-binding-0.18.0-SNAPSHOT.jar:/home/centos/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/centos/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/centos/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/centos/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar:/home/centos/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar:/home/centos/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/centos/YCSB/core/target/core-0.18.0-SNAPSHOT.jar site.ycsb.Client -db site.ycsb.db.RedisClient -s -P workloads/workloada -threads 8 -target 800 -p operationcount=100000 -p redis.host=172.16.0.2 -p redis.port=7001 -p redis.cluster=true -t
Command line: -db site.ycsb.db.RedisClient -s -P workloads/workloada -threads 8 -target 800 -p operationcount=100000 -p redis.host=172.16.0.2 -p redis.port=7001 -p redis.cluster=true -t
YCSB Client 0.18.0-SNAPSHOT

Loading workload...
Starting test.
2021-02-11 13:48:26:678 0 sec: 0 operations; est completion in 0 second
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:57)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:74)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:31)
        at redis.clients.jedis.JedisCluster.hmset(JedisCluster.java:424)
        at site.ycsb.db.RedisClient.update(RedisClient.java:162)
        at site.ycsb.DBWrapper.update(DBWrapper.java:204)
        at site.ycsb.workloads.CoreWorkload.doTransactionUpdate(CoreWorkload.java:834)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:667)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:57)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:74)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:31)
        at redis.clients.jedis.JedisCluster.hgetAll(JedisCluster.java:514)
        at site.ycsb.db.RedisClient.read(RedisClient.java:124)
        at site.ycsb.DBWrapper.read(DBWrapper.java:141)
        at site.ycsb.workloads.CoreWorkload.doTransactionRead(CoreWorkload.java:742)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:664)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:57)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:74)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:31)
        at redis.clients.jedis.JedisCluster.hmset(JedisCluster.java:424)
        at site.ycsb.db.RedisClient.update(RedisClient.java:162)
        at site.ycsb.DBWrapper.update(DBWrapper.java:204)
        at site.ycsb.workloads.CoreWorkload.doTransactionUpdate(CoreWorkload.java:834)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:667)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
[centos@ip-192-168-4-205 YCSB]$ 
```

The Fedora is running on top of FPGA simulation of a RISCV core, so delays are quite intensive - therefore, I thought that adding up the `redis.timeout` parameter would help - given that it complains: "**No reachable node in cluster**" (which, of course, makes no sense if the other run with 4 threads can reach it), but not really:
```
[centos@ip-192-168-4-205 YCSB]$ ./bin/ycsb run redis -s -P workloads/workloada -threads 8 -target 800 -p operationcount=100000 -p "redis.host=172.16.0.2" -p "redis.port=7001" -p "redis.clust
er=true" -p "redis.timeout=999999" > outputRun.txt
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:redis-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
/usr/lib/jvm/jre-openjdk/bin/java -cp /home/centos/YCSB/redis/conf:/home/centos/YCSB/redis/target/redis-binding-0.18.0-SNAPSHOT.jar:/home/centos/.m2/repository/org/apache/htrace/htrace-core4
/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/centos/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/centos/.m2/repository/org/codehaus/jackson/ja
ckson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/centos/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar:/home/centos/.m2/repository/org/apache/commons/commons-pool2/2.4.2/c
ommons-pool2-2.4.2.jar:/home/centos/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/centos/YCSB/core/target/core-0.18.0-SNAPSHOT.jar site.ycsb.Cli
ent -db site.ycsb.db.RedisClient -s -P workloads/workloada -threads 8 -target 800 -p operationcount=100000 -p redis.host=172.16.0.2 -p redis.port=7001 -p redis.cluster=true -p redis.timeout=
999999 -t
Command line: -db site.ycsb.db.RedisClient -s -P workloads/workloada -threads 8 -target 800 -p operationcount=100000 -p redis.host=172.16.0.2 -p redis.port=7001 -p redis.cluster=true -p redis.timeout=999999 -t
YCSB Client 0.18.0-SNAPSHOT

Loading workload...
Starting test.
2021-02-11 13:51:25:064 0 sec: 0 operations; est completion in 0 second 
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:57)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:74)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:31)
        at redis.clients.jedis.JedisCluster.hgetAll(JedisCluster.java:514)
        at site.ycsb.db.RedisClient.read(RedisClient.java:124)
        at site.ycsb.DBWrapper.read(DBWrapper.java:141)
        at site.ycsb.workloads.CoreWorkload.doTransactionRead(CoreWorkload.java:742)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:664)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:57)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:74)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:31)
        at redis.clients.jedis.JedisCluster.hmset(JedisCluster.java:424)
        at site.ycsb.db.RedisClient.update(RedisClient.java:162)
        at site.ycsb.DBWrapper.update(DBWrapper.java:204)
        at site.ycsb.workloads.CoreWorkload.doTransactionUpdate(CoreWorkload.java:834)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:667)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:57)
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:74)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116)
        at redis.clients.jedis.JedisClusterCommand.run(JedisClusterCommand.java:31)
        at redis.clients.jedis.JedisCluster.hgetAll(JedisCluster.java:514)
        at site.ycsb.db.RedisClient.read(RedisClient.java:124)
        at site.ycsb.DBWrapper.read(DBWrapper.java:141)
        at site.ycsb.workloads.CoreWorkload.doTransactionRead(CoreWorkload.java:742)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:664)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:57)[centos@ip-192-168-4-205 YCSB]$ 
```

I have to admit I am not really sure if I am using the timeout parameter correctly - I just assumed it's in ms, according to the load/run output for the runs that go through. 

Another thing to note is that I already did one experiment with the same hardware, I just had 16 Redis nodes instead of 32 now and in that experiment I was able to run YCSB workload using 8 threads... Actually, I tried setting to 10 first (from the example given [here](https://github.com/brianfrankcooper/YCSB/wiki/Running-a-Workload)), but that failed - looking at the `lscpu` output, I assumed it was because there are 8 cores available in that machine. Was that a correct assumption? 

What could be the reason for this strange behavior - how could I increase the number to 8 threads?

**Comment by busbey** [comment]
it smells like the redis cluster is overwhelmed and ycsb stops being able to get responses. if so, your options are to get more hardware or reduce how much you're asking the cluster to do. what does the redis log show during the failures?

**Comment by apaj** [comment]
Hm... I didn't look and those Fedoras are lost after the simulation ends - so I can't access them... but your response makes sense in the context of my previous experiment:

1. 16 redis shards running on the same node - responsive to YCSB working with 8 threads
2. 32 redis shards running on the same node - not responsive to YCSB working with 8 threads.

Thanks for the insight. Let me repeat with a few more different numbers of shards and I'll get back the information here, including the redis logs.

**Comment by apaj** [comment]
Hi @busbey , 
I've played a bit more with the redis cluster. Unfortunately, I wasn't able to locate the logs... they are not in /var/logs, nor anywhere within the install directory (I built from source)...
It also eludes me where exactly the "cluster" process is... I mean... there are 16 or whatever number of redis servers running, and then I run a redis-cli create cluster command to bind them all together, and that goes fine, but that process "redis-cli create cluster", if I can call it that, just does its thing and then it's over - each of the servers is on their own port...
So, to try and focus... am I actually correctly using YCSB when I say:
```
./bin/ycsb load redis -s -P workloads/workloada -p recordcount=10000  -p  "redis.host=172.16.0.2" -p "redis.port=7001" -p "redis.cluster=true" > outputLoadA.txt && ./bin/ycsb run redis -s -P workloads/workloada  -target 1600 -p operationcount=100000 -p "redis.host=172.16.0.2" -p "redis.port=7001" -p "redis.cluster=true"  > outputRunA.tx
```
Doesn't this way of using YCSB creates a kind of a bottleneck, since all the operations are still aimed at the redis-server listening at 7001 port?
Do I need to do anything else to make sure that the operations given by "operationcount" parameter are equally distributed across all 16 shards of redis cluster?

**Comment by apaj** [comment]
Hi @busbey ,
I made some progress in the meantime, so maybe just as a recap for future reference.
The way we pushed through, was to run multiple instances of YCSB, each with multiple threads. For example, as suggested above, we concluded that the hardware gets clogged at YCSB thread count of 4 at a given port (where port, say 7003, is tied to a particular redis shard). So, if I keep it at that, run only 4 threads per instance, i.e. per port, then I can run another YCSB instance, again with 4 threads, but give it a target on a different port of the redis cluster - hence, a different redis shard receives those 4 threads. If I have 16 redis shards, then I run 16 YCSB instances, each with 4 threads, that makes it 64 YCSB workers total running across this redis cluster. For now that works.
What is worrying me is that this does not resemble "proper" cluster behavior; namely, using SCAN and NODES, while connected to one of the shards, I realized that I can not ask for the data stored on a different shard. Basically, a redis client needs to be implemented, according to redis docs. Now... I'd still like to use YCSB workloads, so... it seems that this redis client would have to act as the middle man: YCSB targets this client, and then the client talks to all the shards on all the ports... 
Please @busbey is this a realistic scenario - is that how things should be done?
Thanks,
  Aleksandar
