### ISSUE TITLE
[ERROR] Could not find the selected project in the reactor:

### ISSUE THREAD

**Issue by ggyuchoe** [brianfrankcooper/YCSB#1552]
Hello!

I tried 
=======
mvn -pl site.ycsb:cassandra-binding -am clean package -e
=======
to proceed with building from cassandra source on CentOS 7.5, but the following log appears and ERROR occurs.

==========
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[ERROR] Could not find the selected project in the reactor: site.ycsb:cassandra-binding -> [Help 1]
org.apache.maven.MavenExecutionException: Could not find the selected project in the reactor: site.ycsb:cassandra-binding
        at org.apache.maven.DefaultMaven.trimSelectedProjects(DefaultMaven.java:749)
        at org.apache.maven.DefaultMaven.createDependencyGraph(DefaultMaven.java:703)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:290)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
========

The log that you commented on when using Maven version 2 and the result of the environment I ran seem to be similar.
So I checked the maven version, and it seems to be using maven version 3.
==========
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_292, vendor: Red Hat, Inc.
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.292.b10-1.el7_9.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.1.3.el7.x86_64", arch: "amd64", family: "unix"
==========

What more can I check to solve?

(To share an additional environment, cassandra is in an active state.)
=======
● cassandra.service - Apache Cassandra
   Loaded: loaded (/etc/systemd/system/cassandra.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-07-28 15:51:52 KST; 2h 32min ago
 Main PID: 7375 (java)
    Tasks: 154
   Memory: 8.4G
   CGroup: /system.slice/cassandra.service
           └─7375 java -ea -da:net.openhft... -XX:+UseThreadPriorities -XX:+HeapDumpOnOutOfMemoryError -Xss256k -XX:+AlwaysPreTouch -XX:-UseBiasedLocking -XX:+UseTLAB -XX:+...
========

**Comment by busbey** [comment]
please include what version of YCSB you were attempting to build.

Can you use the convenience binary directly instead of building from source?

https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-cassandra-binding-0.17.0.tar.gz
