### ISSUE TITLE
Issue regarding YCSB client and cassandra server

### ISSUE THREAD

**Issue by sneha1012** [brianfrankcooper/YCSB#159]
Hello myself sneha,am using data-serving benchamark...I ve placed YCSB on one machine and apache-cassandra on another machine....am getting the followiing error when i run the follwoing code on client machine..
[root@localhost YCSB]# java -cp build/ycsb.jar:db/cassandra-0.7/lib/* com.yahoo.ycsb.Client -load -s -db com.yahoo.ycsb.db.CassandraClient7 -P workloads/workloada -p hosts="192.168.2.109"
YCSB Client 0.1
Command line: -load -s -db com.yahoo.ycsb.db.CassandraClient7 -P workloads/workloada -p hosts=192.168.2.109
Loading workload...
Starting test.
 0 sec: 0 operations; 
 10 sec: 0 operations; 
 20 sec: 0 operations; 
 30 sec: 0 operations; 
 40 sec: 0 operations; 
 50 sec: 0 operations; 
 60 sec: 0 operations; 
 70 sec: 0 operations; 
 80 sec: 0 operations; 
 90 sec: 0 operations; 
 100 sec: 0 operations; 
 110 sec: 0 operations; 
 120 sec: 0 operations; 
 130 sec: 0 operations; 
 140 sec: 0 operations; 
 150 sec: 0 operations; 
 160 sec: 0 operations; 
 170 sec: 0 operations; 
 180 sec: 0 operations; 
 190 sec: 0 operations; 
 200 sec: 0 operations; 
 210 sec: 0 operations; 
 220 sec: 0 operations; 
 230 sec: 0 operations; 
 240 sec: 0 operations; 
 250 sec: 0 operations; 
 260 sec: 0 operations; 
 270 sec: 0 operations; 
 280 sec: 0 operations; 
 290 sec: 0 operations; 
 300 sec: 0 operations; 
Unable to connect to 192.168.2.109 after 300 tries
Unable to connect to 192.168.2.109 after 300 tries
com.yahoo.ycsb.DBException: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at com.yahoo.ycsb.db.CassandraClient7.init(Unknown Source)
	at com.yahoo.ycsb.DBWrapper.init(Unknown Source)
	at com.yahoo.ycsb.ClientThread.run(Unknown Source)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:185)
	at org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
	... 3 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
	... 4 more
com.yahoo.ycsb.DBException: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at com.yahoo.ycsb.db.CassandraClient7.init(Unknown Source)
	at com.yahoo.ycsb.DBWrapper.init(Unknown Source)
	at com.yahoo.ycsb.ClientThread.run(Unknown Source)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
	at org.apache.thrift.transport.TSocket.open(TSocket.java:185)
	at org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
	... 3 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
	... 4 more
[OVERALL], RunTime(ms), 300610.0
[OVERALL], Throughput(ops/sec), 0.0
 300 sec: 0 operations;

Could anybody tell me how to reslove this issue....
if i put hosts address under settings.dat file also same error am getting....

**Comment by busbey** [comment]
you will need to look at your logs on the cassandra side to see what shows up there. this sounds like a firewall issue.

**Comment by busbey** [comment]
Closing as stale. Please attempt to use the new CQL bindings and open an issue if you have problems.
