### ISSUE TITLE
Error while running ycsb with mongodb

### ISSUE THREAD

**Issue by srizvi6** [brianfrankcooper/YCSB#1608]
Hello,

I tried running mongodb with ycsb and got it to work, however I am trying to use 0.17.0 and I'm getting this error when I try to run the workload. 

java -cp /usr/local/ycsb-0.17.0/mongodb-binding/conf:/usr/local/ycsb-0.17.0/conf:/usr/local/ycsb-0.17.0/lib/htrace-core4-4.1.0-incubating.jar:/usr/local/ycsb-0.17.0/lib/jackson-mapper-asl-1.9.4.jar:/usr/local/ycsb-0.17.0/lib/core-0.17.0.jar:/usr/local/ycsb-0.17.0/lib/HdrHistogram-2.1.4.jar:/usr/local/ycsb-0.17.0/lib/jackson-core-asl-1.9.4.jar:/usr/local/ycsb-0.17.0/mongodb-binding/lib/mongodb-async-driver-2.0.1.jar:/usr/local/ycsb-0.17.0/mongodb-binding/lib/snappy-java-1.1.7.1.jar:/usr/local/ycsb-0.17.0/mongodb-binding/lib/logback-core-1.1.2.jar:/usr/local/ycsb-0.17.0/mongodb-binding/lib/mongodb-binding-0.17.0.jar:/usr/local/ycsb-0.17.0/mongodb-binding/lib/logback-classic-1.1.2.jar:/usr/local/ycsb-0.17.0/mongodb-binding/lib/slf4j-api-1.7.25.jar:/usr/local/ycsb-0.17.0/mongodb-binding/lib/mongo-java-driver-3.8.0.jar site.ycsb.Client -db site.ycsb.db.MongoDbClient -p mongodb.url=mongodb://130.127.134.13:27017/ycsb -s -P workload -threads 64 -target 2000 -t
Command line: -db site.ycsb.db.MongoDbClient -p mongodb.url=mongodb://130.127.134.13:27017/ycsb -s -P workload -threads 64 -target 2000 -t
YCSB Client 0.17.0

Loading workload...
java.lang.ClassNotFoundException: com.yahoo.ycsb.workloads.CoreWorkload
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at site.ycsb.Client.getWorkload(Client.java:517)
	at site.ycsb.Client.main(Client.java:302)
java.lang.ClassNotFoundException: com.yahoo.ycsb.workloads.CoreWorkload
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at site.ycsb.Client.getWorkload(Client.java:517)
	at site.ycsb.Client.main(Client.java:302)

Here's an ls of my ycsb dir

accumulo1.6-binding  azuretablestorage-binding  dynamodb-binding         griddb-binding      ignite-binding      maprjsondb-binding    rados-binding    solr-binding
accumulo1.7-binding  bin                        elasticsearch5-binding   hbase098-binding    infinispan-binding  memcached-binding     redis-binding    tablestore-binding
accumulo1.8-binding  cassandra-binding          elasticsearch-binding    hbase10-binding     jdbc-binding        mongodb-binding       rest-binding     tarantool-binding
aerospike-binding    cloudspanner-binding       foundationdb-binding     hbase12-binding     kudu-binding        nosqldb-binding       riak-binding     voltdb-binding
arangodb-binding     couchbase2-binding         geode-binding            hbase14-binding     lib                 NOTICE.txt            rocksdb-binding  workloads
asynchbase-binding   couchbase-binding          googlebigtable-binding   hbase20-binding     LICENSE.txt         orientdb-binding      s3-binding
azurecosmos-binding  crail-binding              googledatastore-binding  hypertable-binding  maprdb-binding      postgrenosql-binding  solr6-binding

Any help would be appreciated. Thanks!

**Comment by stutiredboy** [comment]
check your mongodb workload configuration, update ^workload line to:

> workload=site.ycsb.workloads.CoreWorkload
