### ISSUE TITLE
show exception in thread "Thread-6" java.lang.AssertionError: oops. should not get here  when runin

### ISSUE THREAD

**Issue by matthewxuda** [brianfrankcooper/YCSB#1614]
config

![image](https://user-images.githubusercontent.com/5927005/169701266-4f2c1d34-13a3-442d-b7b0-0c8055fd98dc.png)

and run:

./bin/ycsb.sh run  jdbc   -P workloads/mysql/workload.mysql -P workloads/mysql/mysql-db.properties

show error: see in attachment 

[exception.txt](https://github.com/brianfrankcooper/YCSB/files/8749655/exception.txt)

DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-59" Exception in thread "Thread-22" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-92" Exception in thread "Thread-91" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-10" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-55" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-104" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-65" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
java.lang.AssertionError: oops. should not get here.
Using shards: 1, batchSize:1000, fetchSize: 10
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-88" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-6" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)Using shards: 1, batchSize:1000, fetchSize: 10

        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-64" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Using shards: 1, batchSize:1000, fetchSize: 10Exception in thread "Thread-20" 
java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Using shards: 1, batchSize:1000, fetchSize: 10DBWrapper: report latency for each error is false and specific error codes to track for latency are: []

DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Using shards: 1, batchSize:1000, fetchSize: 10
Exception in thread "Thread-4" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Using shards: 1, batchSize:1000, fetchSize: 10
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-7" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-114" Using shards: 1, batchSize:1000, fetchSize: 10java.lang.AssertionError: oops. should not get here.

        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)Using shards: 1, batchSize:1000, fetchSize: 10

        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-117" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-9" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Using shards: 1, batchSize:1000, fetchSize: 10
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-68" java.lang.AssertionError: oops. should not get here.
Using shards: 1, batchSize:1000, fetchSize: 10
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
Using shards: 1, batchSize:1000, fetchSize: 10  at site.ycsb.generator.Generator.nextString(Generator.java:38)

        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-5" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-33" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-102" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-41" Exception in thread "Thread-79" Exception in thread "Thread-82" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []Using shards: 1, batchSize:1000, fetchSize: 10

DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-54" Using shards: 1, batchSize:1000, fetchSize: 10
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Using shards: 1, batchSize:1000, fetchSize: 10Exception in thread "Thread-89" 
java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Using shards: 1, batchSize:1000, fetchSize: 10Exception in thread "Thread-81" 
java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-25" Exception in thread "Thread-118" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Using shards: 1, batchSize:1000, fetchSize: 10
Using shards: 1, batchSize:1000, fetchSize: 10Exception in thread "Thread-35" 
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []Using shards: 1, batchSize:1000, fetchSize: 10

DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Using shards: 1, batchSize:1000, fetchSize: 10
Exception in thread "Thread-8" DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-120" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Using shards: 1, batchSize:1000, fetchSize: 10
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []Using shards: 1, batchSize:1000, fetchSize: 10

Using shards: 1, batchSize:1000, fetchSize: 10
Exception in thread "Thread-16" Using shards: 1, batchSize:1000, fetchSize: 10java.lang.AssertionError: oops. should not get here.

        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
Using shards: 1, batchSize:1000, fetchSize: 10  at site.ycsb.ClientThread.run(ClientThread.java:122)

        at java.lang.Thread.run(Thread.java:748)
java.lang.AssertionError: oops. should not get here.Using shards: 1, batchSize:1000, fetchSize: 10

Using shards: 1, batchSize:1000, fetchSize: 10  at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)

        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Using shards: 1, batchSize:1000, fetchSize: 10
Using shards: 1, batchSize:1000, fetchSize: 10DBWrapper: report latency for each error is false and specific error codes to track for latency are: []

DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-87" Using shards: 1, batchSize:1000, fetchSize: 10
java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)Using shards: 1, batchSize:1000, fetchSize: 10

        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)Using shards: 1, batchSize:1000, fetchSize: 10
        at site.ycsb.ClientThread.run(ClientThread.java:122)

        at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-60" java.lang.AssertionError: oops. should not get here.
Using shards: 1, batchSize:1000, fetchSize: 10
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-77" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-27" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-17" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []Using shards: 1, batchSize:1000, fetchSize: 10

DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-48" Exception in thread "Thread-45" Exception in thread "Thread-67" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-15" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-73" java.lang.AssertionError: oops. should not get here.
Using shards: 1, batchSize:1000, fetchSize: 10
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Exception in thread "Thread-14" java.lang.AssertionError: oops. should not get here.
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:69)
        at site.ycsb.generator.DiscreteGenerator.nextValue(DiscreteGenerator.java:29)
        at site.ycsb.generator.Generator.nextString(Generator.java:38)
        at site.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:637)
        at site.ycsb.ClientThread.run(ClientThread.java:122)
        at java.lang.Thread.run(Thread.java:748)

**Comment by busbey** [comment]
what version are you using?

**Comment by matthewxuda** [comment]
i use  ycsb-0.17.0
