### ISSUE TITLE
Error .DBException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/ycsb

### ISSUE THREAD

**Issue by ticianacapris** [brianfrankcooper/YCSB#1619]
I am trying to use jdbc to parse my mysql database. However when running

` ./bin/ycsb load jdbc -s -P workloads/workloada -p jdbc.driver=com.mysql.jdbc.Driver -p db.url=jdbc:mysql://localhost:3306/ycsb -p db.user=root -p db-passwd=bitnani`
 I get this error
`Loading workload...
Starting test.
Adding shard node URL: jdbc:mysql://localhost:3306/ycsb
Error in database operation: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/ycsb
site.ycsb.DBException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/ycsb
        at site.ycsb.db.JdbcDBClient.init(JdbcDBClient.java:248)
        at site.ycsb.DBWrapper.init(DBWrapper.java:90)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/ycsb
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at site.ycsb.db.JdbcDBClient.init(JdbcDBClient.java:226)
        ... 3 more
site.ycsb.DBException: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/ycsb
        at site.ycsb.db.JdbcDBClient.init(JdbcDBClient.java:248)
        at site.ycsb.DBWrapper.init(DBWrapper.java:90)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: No suitable driver found for jdbc:mysql://localhost:3306/ycsb
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at site.ycsb.db.JdbcDBClient.init(JdbcDBClient.java:226)
        ... 3 more
2022-06-23 09:40:49:665 0 sec: 0 operations; est completion in 0 second 
2022-06-23 09:40:49:667 0 sec: 0 operations; est completion in 106751991167300 days 15 hours
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 0
[TOTAL_GC_TIME], Time(ms), 0
[TOTAL_GC_TIME_%], Time(%), 0.0
PS C:\Users\tcapr\Downloads\YCSB-master\YCSB-master>`

**Comment by busbey** [comment]
You need the MySQL jdbc driver.

**Comment by desibandhu** [comment]
Where should I place the `mysql-connector.java` file?

For me, this same thing appears when I try to do this,
```lang=shell
python2 bin/ycsb shell jdbc -cp ~/ycsb/mysql-connector-java.jar
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:jdbc-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
java -cp /home/admin_klrajkotia_altostrat_com/ycsb/mysql-connector-java.jar:/home/admin_klrajkotia_altostrat_com/ycsb/jdbc/conf:/home/admin_klrajkotia_altostrat_com/ycsb/jdbc/target/jdbc-binding-0.18.0-SNAPSHOT.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/org/apache/geronimo/specs/geronimo-jta_1.1_spec/1.1.1/geronimo-jta_1.1_spec-1.1.1.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/net/sourceforge/serp/serp/1.13.1/serp-1.13.1.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/org/apache/openjpa/openjpa-jdbc/2.1.1/openjpa-jdbc-2.1.1.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1.1/geronimo-jms_1.1_spec-1.1.1.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/org/apache/openjpa/openjpa-kernel/2.1.1/openjpa-kernel-2.1.1.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/home/admin_klrajkotia_altostrat_com/ycsb/core/target/core-0.18.0-SNAPSHOT.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/org/apache/openjpa/openjpa-lib/2.1.1/openjpa-lib-2.1.1.jar:/home/admin_klrajkotia_altostrat_com/.m2/repository/commons-pool/commons-pool/1.5.4/commons-pool-1.5.4.jar site.ycsb.CommandLine -db site.ycsb.db.JdbcDBClient
YCSB Command Line client
Type "help" for command line help
Start with "-help" for usage info
Adding shard node URL: 
Error in database operation: java.sql.SQLException: No suitable driver found for 
site.ycsb.DBException: java.sql.SQLException: No suitable driver found for 
	at site.ycsb.db.JdbcDBClient.init(JdbcDBClient.java:248)
	at site.ycsb.CommandLine.main(CommandLine.java:99)
Caused by: java.sql.SQLException: No suitable driver found for 
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at site.ycsb.db.JdbcDBClient.init(JdbcDBClient.java:226)
	... 1 more
```

**Comment by busbey** [comment]
that looks correct. Please try from a release binary and a load/run command so we can figure out if it's something funky with the shell command.
