### ISSUE TITLE
YCSB and MongoDB 6

### ISSUE THREAD

**Issue by dewongway** [brianfrankcooper/YCSB#1631]
Hi,

Has anyone used ycsb with MongoDB 6.x? The latest ycsb failed to make connection to the database with the following error. It seems like the mongodb java driver bundled in ycsb is not updated to the version 6? Has anyone run into it and how do you resolve this? I’m thinking I can just install the latest mongodb java driver but have no experience in java development and I’m looking for some guidance/suggestions.

com.allanbank.mongodb.error.ReplyException: Unsupported OP_QUERY command: insert. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
at com.allanbank.mongodb.util.FutureUtils.unwrap(FutureUtils.java:57)
at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:687)
at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:722)
at site.ycsb.db.AsyncMongoDbClient.insert(AsyncMongoDbClient.java:272)
at site.ycsb.DBWrapper.insert(DBWrapper.java:221)
at site.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:601)
at site.ycsb.ClientThread.run(ClientThread.java:135)
at java.lang.Thread.run(Thread.java:750)

Thanks

**Comment by busbey** [comment]
that error looks like it is from mongodb-async. try using the vanilla mongodb client instead.

**Comment by anlowee** [comment]
> that error looks like it is from mongodb-async. try using the vanilla mongodb client instead.

i have a same issue... could you provide more instructions in detail? (i.e a command) :)

**Comment by busbey** [comment]
as the error message states, it looks like a client upgrade is needed. If there is a more recent version of the async mongodb client available, you could try updating it in a local build.
