### ISSUE TITLE
elasticsearch5: NoNodeAvailableException

### ISSUE THREAD

**Issue by RuifMaxx** [brianfrankcooper/YCSB#1644]
Hi,

Good day to you.

I deployed a elasticsearch 5.0.2 on kubernetes. With command: `curl 10.68.140.245:9200 ` , I got: 

```
{
  "name" : "_Klq3Ir",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "eP4vholxT-2KeiieP2iRDw",
  "version" : {
    "number" : "5.0.2",
    "build_hash" : "f6b4951",
    "build_date" : "2016-11-24T10:07:18.101Z",
    "build_snapshot" : false,
    "lucene_version" : "6.2.1"
  },
  "tagline" : "You Know, for Search"
}

```

However, when  I try to run the ycsb tool on this cluster using the command given below, I get the following error:

Command used:

`./bin/ycsb load elasticsearch5 -s -P workloads/workloada -p es.hosts.list=10.68.140.245:9300`

Output:

```
Command line: -db site.ycsb.db.elasticsearch5.ElasticsearchClient -s -P workloads/workloada -p es.hosts.list=10.68.140.245:9300 -load
YCSB Client 0.17.0

Loading workload...
Starting test.
2022-10-13 20:14:27:260 0 sec: 0 operations; est completion in 0 second 
2022-10-13 20:14:27,695 Thread-2 ERROR Console contains an invalid element or attribute "targetStr"
[2022-10-13T20:14:27,897][INFO ][o.e.p.PluginsService     ] [_client_] no modules loaded
[2022-10-13T20:14:27,899][INFO ][o.e.p.PluginsService     ] [_client_] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[2022-10-13T20:14:27,899][INFO ][o.e.p.PluginsService     ] [_client_] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
[2022-10-13T20:14:27,899][INFO ][o.e.p.PluginsService     ] [_client_] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
[2022-10-13T20:14:27,900][INFO ][o.e.p.PluginsService     ] [_client_] loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
[2022-10-13T20:14:27,900][INFO ][o.e.p.PluginsService     ] [_client_] loaded plugin [org.elasticsearch.transport.Netty3Plugin]
[2022-10-13T20:14:27,900][INFO ][o.e.p.PluginsService     ] [_client_] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[2022-10-13T20:14:28,908][WARN ][o.e.t.TransportService   ] [_client_] Transport response handler not found of id [1]
[2022-10-13T20:14:28,985][WARN ][o.e.c.t.TransportClientNodesService] [_client_] node null not part of the cluster Cluster [es.ycsb.cluster], ignoring...
Exception in thread "Thread-2" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{rsh_ceyuT6G7EvEZO9J9bA}{10.68.140.245}{10.68.140.245:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:397)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1250)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.exists(AbstractClient.java:1272)
	at site.ycsb.db.elasticsearch5.ElasticsearchClient.init(ElasticsearchClient.java:124)
	at site.ycsb.DBWrapper.init(DBWrapper.java:86)
	at site.ycsb.ClientThread.run(ClientThread.java:91)
	at java.base/java.lang.Thread.run(Thread.java:829)
2022-10-13 20:14:28:988 1 sec: 0 operations; est completion in 106751991167300 days 15 hours 
[OVERALL], RunTime(ms), 1798
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_G1_Young_Generation], Count, 6
[TOTAL_GC_TIME_G1_Young_Generation], Time(ms), 48
[TOTAL_GC_TIME_%_G1_Young_Generation], Time(%), 2.6696329254727478
[TOTAL_GCS_G1_Old_Generation], Count, 0
[TOTAL_GC_TIME_G1_Old_Generation], Time(ms), 0
[TOTAL_GC_TIME_%_G1_Old_Generation], Time(%), 0.0
[TOTAL_GCs], Count, 6
[TOTAL_GC_TIME], Time(ms), 48
[TOTAL_GC_TIME_%], Time(%), 2.6696329254727478

```

I tried with other ports as well (9200, 9300)- just to make sure - but it still gives the same exception. Could you please look into this?

Thank you

Ruifma

**Comment by matte21** [comment]
I'm also experiencing this.
