### ISSUE TITLE
`core/` dependencies not being installed

### ISSUE THREAD

**Issue by seankimkdy** [brianfrankcooper/YCSB#1684]
When I run `mvn clean package` then `./bin/ycsb.sh load basic -P workloads/workloada`, I get an error

```
/usr/bin/java  -classpath /users/seankim/scratch/ycsb/conf:/users/seankim/scratch/ycsb/core/target/core-0.18.0-SNAPSHOT.jar:/users/seankim/scratch/ycsb/core/target/core-0.18.0-SNAPSHOT.jar site.ycsb.Client -t -db site.ycsb.BasicDB -P workloads/workloada
Command line: -t -db site.ycsb.BasicDB -P workloads/workloada
YCSB Client 0.18.0-SNAPSHOT

Loading workload...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/htrace/core/Tracer$Builder
	at site.ycsb.Client.getTracer(Client.java:458)
	at site.ycsb.Client.main(Client.java:304)
Caused by: java.lang.ClassNotFoundException: org.apache.htrace.core.Tracer$Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 2 more
 (might take a few minutes for large data sets)
```

However, if I run `mvn clean package -Psource-run`, everything works. Any reason why?

Version information in case they are relevant.
```
$ mvn --version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.20.1, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.14.0-rc5", arch: "amd64", family: "unix"
$ java -version
openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.20.1+1-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

**Comment by jsyqrt** [comment]
Got same error with master branch

**Comment by ZhouXing19** [comment]
Same error, any update on this?
