### ISSUE TITLE
Could not test memcached db

### ISSUE THREAD

**Issue by summitsoul** [brianfrankcooper/YCSB#1686]
hello
I use wsl to run YCSB.
I follow [https://github.com/brianfrankcooper/YCSB/blob/master/memcached/README.md#5-memcached-connection-parameters](url) . The previous steps went on well. But when I in step 4 `./bin/ycsb load memcached -s -P workloads/workloada > outputLoad.txt`.It will have the following message.
`[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl site.ycsb:memcached-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
java -cp /mnt/d/YCSB/memcached/conf:/mnt/d/YCSB/memcached/target/memcached-binding-0.18.0-SNAPSHOT.jar:/home/summitsoul/.m2/repository/org/apache/htrace/htrace-core4/4.1.0-incubating/htrace-core4-4.1.0-incubating.jar:/home/summitsoul/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/home/summitsoul/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/summitsoul/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar:/home/summitsoul/.m2/repository/net/spy/spymemcached/2.11.4/spymemcached-2.11.4.jar:/home/summitsoul/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/mnt/d/YCSB/core/target/core-0.18.0-SNAPSHOT.jar site.ycsb.Client -db site.ycsb.db.MemcachedClient -s -P workloads/workloada -load
Command line: -db site.ycsb.db.MemcachedClient -s -P workloads/workloada -load
YCSB Client 0.18.0-SNAPSHOT

Loading workload...
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
2023-10-22 11:46:30:775 0 sec: 0 operations; est completion in 0 second
site.ycsb.DBException: java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "java.util.Properties.getProperty(String)" is null
        at site.ycsb.db.MemcachedClient.init(MemcachedClient.java:133)
        at site.ycsb.DBWrapper.init(DBWrapper.java:90)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "java.util.Properties.getProperty(String)" is null
        at site.ycsb.db.MemcachedClient.createMemcachedClient(MemcachedClient.java:165)
        at site.ycsb.db.MemcachedClient.init(MemcachedClient.java:122)
        ... 3 more
2023-10-22 11:46:30:816 0 sec: 0 operations; est completion in 106751991167300 days 15 hours`
I don't understand how to figure out this question. 
Could you please give me some help?
Thanks.

**Comment by summitsoul** [comment]
Hi,
i found that if i scanf `./bin/ycsb load memcached -s -P workloads/workloada -p 'locolhosts=127.0.0.1' > outputLoad.txt`. it will be ok. so i add `locolhosts=127.0.0.1` in /YCSB/memcached/conf/memcached.properties. but it still not work. i want to know how to solve it.
Thanks.
