### ISSUE TITLE
The file properties doesn't exist java.lang.NullPointerException: inStream parameter is null

### ISSUE THREAD

**Issue by DhyaneshNaik** [brianfrankcooper/YCSB#1688]
I am trying to connect to s3 with the specified parameters but it is giving us below errors.

The file properties doesn't exist java.lang.NullPointerException: inStream parameter is null
java.lang.NullPointerException: inStream parameter is null
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at java.base/java.util.Properties.load(Properties.java:406)
        at site.ycsb.db.S3Client.init(S3Client.java:164)
        at site.ycsb.DBWrapper.init(DBWrapper.java:90)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.base/java.lang.Thread.run(Thread.java:829)
Inizializing the S3 connection
Could not connect to S3 storage: java.lang.IllegalArgumentException: Access key cannot be null.
java.lang.IllegalArgumentException: Access key cannot be null.
        at com.amazonaws.auth.BasicAWSCredentials.<init>(BasicAWSCredentials.java:37)
        at site.ycsb.db.S3Client.init(S3Client.java:213)
        at site.ycsb.DBWrapper.init(DBWrapper.java:90)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.base/java.lang.Thread.run(Thread.java:829)
site.ycsb.DBException: java.lang.IllegalArgumentException: Access key cannot be null.
        at site.ycsb.db.S3Client.init(S3Client.java:231)
        at site.ycsb.DBWrapper.init(DBWrapper.java:90)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Access key cannot be null.
        at com.amazonaws.auth.BasicAWSCredentials.<init>(BasicAWSCredentials.java:37)
        at site.ycsb.db.S3Client.init(S3Client.java:213)
        ... 3 more
site.ycsb.DBException: java.lang.IllegalArgumentException: Access key cannot be null.
        at site.ycsb.db.S3Client.init(S3Client.java:231)
        at site.ycsb.DBWrapper.init(DBWrapper.java:90)
        at site.ycsb.ClientThread.run(ClientThread.java:91)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Access key cannot be null.
        at com.amazonaws.auth.BasicAWSCredentials.<init>(BasicAWSCredentials.java:37)
        at site.ycsb.db.S3Client.init(S3Client.java:213)

I am using below command to load the data

./bin/ycsb load s3 -p table=Bucket_name -p s3.region=region_name -p s3.endPoint=s3.amazonaws.com -p s3.accessKeyId=access_key -p s3.secretKey=secrete_key -p fieldlength=10 -p fieldcount=20 -P workloads/workloada

**Comment by Filipe-Costa22** [comment]
Hi,
Were you able to fix this?
Thanks

**Comment by Filipe-Costa22** [comment]
To fix this error create a `resources` directory under `src/main` and move `s3.properties` into it.
