### ISSUE TITLE
Do not support mongodb 4

### ISSUE THREAD

**Issue by 937447974** [brianfrankcooper/YCSB#1737]
Loading workload...
Starting test.
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: com/mongodb/MongoClientURI
	at site.ycsb.db.MongoDbClient.init(MongoDbClient.java:206)
	at site.ycsb.DBWrapper.init(DBWrapper.java:86)
	at site.ycsb.ClientThread.run(ClientThread.java:91)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: com.mongodb.MongoClientURI
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 4 more
2024-11-21 13:40:00:594 0 sec: 0 operations; est completion in 0 second 
2024-11-21 13:40:00:596 0 sec: 0 operations; est completion in 106751991167300 days 15 hours

**Comment by anish-palakurthi** [comment]
Has this been resolved? Did you find a workaround?

**Comment by anish-palakurthi** [comment]
If anyone is having this issue, I found that building from source with maven was the issue. The pre-built version works for mongodb.
