### ISSUE TITLE
YCSB needs to output error correct when running into OutofMemory errors

### ISSUE THREAD

**Issue by Derek-Chen** [brianfrankcooper/YCSB#176]
I'm using YCSB to benchmark against several databases. 
there are a few times, one of the databases got into a weird state, then almost all threads start to throw out of memory error:

BUT the problem is somehow all operations still come back as successful from YCSB point of view. which is definitely masking a big problem.

part of YCSB output:
[READ], Operations, 1100839  <------------------------
[READ], AverageLatency(us), 2667.7355371675603
[READ], MinLatency(us), 553
[READ], MaxLatency(us), 763484
[READ], 95thPercentileLatency(ms), 7
[READ], 99thPercentileLatency(ms), 12
[READ], Return=0, 1100839   <-------------------------

stderr:

Example:"
Exception in thread "Thread-3" java.lang.OutOfMemoryError: Java heap space
        at com.mysql.jdbc.Buffer.<init>(Buffer.java:57)
        at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:2087)
        at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3549)
        at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:489)
        at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3240)
        at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2411)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2834)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2838)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2212)
        at com.yahoo.ycsb.db.JdbcDBClient.scan(JdbcDBClient.java:348)
        at com.yahoo.ycsb.DBWrapper.scan(DBWrapper.java:107)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:605)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:491)
        at com.yahoo.ycsb.ClientThread.run(Client.java:233)
Exception in thread "Thread-13" java.lang.OutOfMemoryError: Java heap space
        at com.mysql.jdbc.Buffer.<init>(Buffer.java:57)
        at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:2087)
        at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3549)
        at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:489)
        at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3240)
        at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2411)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2834)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2838)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
        at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2212)
        at com.yahoo.ycsb.db.JdbcDBClient.scan(JdbcDBClient.java:348)
        at com.yahoo.ycsb.DBWrapper.scan(DBWrapper.java:107)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:605)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:491)
        at com.yahoo.ycsb.ClientThread.run(Client.java:233)

**Comment by busbey** [comment]
better if we kill the jvm process out OOM?

**Comment by kruthar** [comment]
Stacktrace says you're hitting OOM on Scan operations and I see you have a small proportion of scan on your workload.

OOM with the JDBC binding on scan operations seems to be a known issue: #171

**Comment by kruthar** [comment]
@Derek-Chen - #171 was fixed in #468. Does that fix your issue?

**Comment by Derek-Chen** [comment]
Sorry to say that I’ve left the job last year.

**Comment by busbey** [comment]
Closing as stale.
