### ISSUE TITLE
Get error message during benchmark cassandra v2.1.1 using YCSB 0.1.4

### ISSUE THREAD

**Issue by yeh928** [brianfrankcooper/YCSB#198]
I want to benchmark cassandra v2.1.1 using YCSB 0.1.4
I try to benchmark cassandra with following command, I got the error as below: 

[root@localhost YCSB]# ./bin/ycsb load cassandra-10 -P workloads/workloada -p hosts=192.168.117.121 -p columnfamily=data > tese_ca.txt
Loading workload...
Starting test.
InvalidRequestException(why:Keyspace 'usertable' does not exist)
        at org.apache.cassandra.thrift.Cassandra$set_keyspace_result.read(Cassandra.java:4816)
        at org.apache.cassandra.thrift.Cassandra$Client.recv_set_keyspace(Cassandra.java:451)
        at org.apache.cassandra.thrift.Cassandra$Client.set_keyspace(Cassandra.java:426)
        at com.yahoo.ycsb.db.CassandraClient10.insert(CassandraClient10.java:437)
        at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:148)
        at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:461)
        at com.yahoo.ycsb.ClientThread.run(Client.java:277)

Please assist me to solve issue.
Thanks!

**Comment by mukundrv** [comment]
Hi,

I used cqlsh to run the below 3 statements.

create Keyspace usertable;   --> Executed successfully
use usertable;   --> Executed successfully
create column family data;    --> Execution failed.

Any idea what this column family or how to run through cqlsh

**Comment by busbey** [comment]
Please attempt ot use the new [CQL bindings](https://github.com/brianfrankcooper/YCSB/blob/master/cassandra/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java#L35)

**Comment by busbey** [comment]
We now know the new CQL bindings don't work with 2.1+. If you have time to help troubleshoot, let us know. Otherwise please follow #293 for updates.
