### ISSUE TITLE
Get error message during benchmark mongodb v 2.4.12 using YCSB 0.1.4

### ISSUE THREAD

**Issue by yeh928** [brianfrankcooper/YCSB#199]
I want to benchmark mongodb v 2.4.12  using YCSB 0.1.4
Then i try to benchmark mongodb with following command, I got the error as below:

[root@localhost YCSB]# bin/ycsb load mongodb -P workloads/workloada -p mongodb.url=192.168.117.121:27017 -p mongodb.database=91db -s > cassload_test.dat
Loading workload...
Starting test.
2014-12-05 19:01:39:615 0 sec: 0 operations; 
com.mongodb.MongoException$DuplicateKey: { "serverUsed" : "/192.168.117.121:27017/91db" , "lastOp" : { "$ts" : 0 , "$inc" : 0} , "connectionId" : 118 , "err" : "insertDocument :: caused by :: 11000 E11000 duplicate key error index: 91db.usertable.$_id_  dup key: { : \"user6284781860667377211\" }" , "code" : 11000 , "n" : 0 , "ok" : 1.0}
        at com.mongodb.CommandResult.getException(CommandResult.java:74)
        at com.mongodb.CommandResult.throwOnError(CommandResult.java:110)
        at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:102)
        at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:142)
        at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:115)
        at com.mongodb.DBApiLayer$MyCollection.insert(DBApiLayer.java:248)
        at com.mongodb.DBApiLayer$MyCollection.insert(DBApiLayer.java:204)
        at com.mongodb.DBCollection.insert(DBCollection.java:148)
        at com.mongodb.DBCollection.insert(DBCollection.java:91)
        at com.yahoo.ycsb.db.MongoDbClient.insert(MongoDbClient.java:205)
        at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:148)
        at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:461)
        at com.yahoo.ycsb.ClientThread.run(Client.java:277)
2014-12-05 19:01:39:743 0 sec: 0 operations; [INSERT AverageLatency(us)=36803] [CLEANUP AverageLatency(us)=683] 

Please assist me to solve issue.
Thanks!

**Comment by busbey** [comment]
@yeh928 are you still attempting to solve this issue? did you ensure the load was on a fresh table?

**Comment by busbey** [comment]
closing as stale. if you are still having this issue please reopen.

**Comment by anchal-agrawal** [comment]
I faced the duplicate key problem while running YCSB workload D with MongoDB version 3.2.6 and found this issue while searching for it.

For someone facing this problem, remember to include the `mongodb.upsert=true` parameter in the YCSB `run` command. This performs the insert operation as an update, as documented [here](https://github.com/brianfrankcooper/YCSB/tree/master/mongodb).
