### ISSUE TITLE
Unconfigured Column Family data - Cassandra

### ISSUE THREAD

**Issue by mukundrv** [brianfrankcooper/YCSB#204]
Hi 

 ./bin/ycsb load cassandra-10 -p hosts=<IPAddress>  -P workloads/workloada 
when I ran the above command, I received an exception

Loading workload...
Starting test.
InvalidRequestException(why:unconfigured columnfamily data)

I have created usertable workspace inside cassandra.

I referred the website http://www.programering.com/a/MzM4kDMwATE.html to created the column family, which ideally failed.
After reading various documenation, I understood that both column family and table are same.

Assuming my understanding is right, is there any create script for the 'data' table ?

**Comment by cmatser** [comment]
If you would like to use a more current version of Cassandra, I created an updated Cassandra adapter for YCSB.  It's a CQL client that I tested with Cassandra 1.2 & 2.0.  It's in pull request #145 .

With that, the instructions for creating the keyspace are:
 cqlsh> create keyspace ycsb
     WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor': 1 };
 cqlsh> create table usertable (
     y_id varchar primary key,
     field0 varchar,
     field1 varchar,
     field2 varchar,
     field3 varchar,
     field4 varchar,
     field5 varchar,
     field6 varchar,
     field7 varchar,
     field8 varchar,
     field9 varchar);

Good luck.

Chrisjan

**Comment by mukundrv** [comment]
the cql client gives me the following error:

com.yahoo.ycsb.DBException: java.lang.IllegalArgumentException: replicate_on_write is not a column defined in this metadata
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:158)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:189)
Caused by: java.lang.IllegalArgumentException: replicate_on_write is not a column defined in this metadata
	at com.datastax.driver.core.ColumnDefinitions.getIdx(ColumnDefinitions.java:268)
	at com.datastax.driver.core.Row.getBool(Row.java:119)
	at com.datastax.driver.core.TableMetadata$Options.<init>(TableMetadata.java:442)
	at com.datastax.driver.core.TableMetadata.build(TableMetadata.java:113)
	at com.datastax.driver.core.Metadata.buildTableMetadata(Metadata.java:124)
	at com.datastax.driver.core.Metadata.rebuildSchema(Metadata.java:88)
	at com.datastax.driver.core.ControlConnection.refreshSchema(ControlConnection.java:265)
	at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:220)
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:168)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:644)
	at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:586)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:69)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:96)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:567)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:133)

**Comment by mukundrv** [comment]
It seems to be a problem with the cassandra driver 

I updated the driver version from 1.0.3 to 2.0.2 in the pom.xml and the compilation failed in CassandraCQLClient.java:170

The cluster.shutdown()  seems to have been removed. Correcting with cluster.close() resolved the compilation issues. 

./bin/ycsb load cassandra-cql -p host="ip1 ip2 ip3" -p port=9042 -p debug=true  -P workloads/workloada  -s

executed successfully.

thanks for your help  Chrisjan

**Comment by cgara** [comment]
Oi,
Estou exatamente com o mesmo problema, não sei o que fazer.
S.O.: Debian 7.8
Cassandra: 2.1.2
YCSB: https://github.com/brianfrankcooper/YCSB/tree/master/ ultima versão
erro:
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -p host=ip -p port=9042 -p cassandra.username=user-p cassandra.password=pass-P workloads/workloada -s -load -load
com.yahoo.ycsb.DBException: java.lang.IllegalArgumentException: replicate_on_write is not a column defined in this metadata
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:158)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:192)
Caused by: java.lang.IllegalArgumentException: replicate_on_write is not a column defined in this metadata
	at com.datastax.driver.core.ColumnDefinitions.getIdx(ColumnDefinitions.java:268)
	at com.datastax.driver.core.Row.getBool(Row.java:119)
	at com.datastax.driver.core.TableMetadata$Options.<init>(TableMetadata.java:442)
	at com.datastax.driver.core.TableMetadata.build(TableMetadata.java:113)
	at com.datastax.driver.core.Metadata.buildTableMetadata(Metadata.java:124)
	at com.datastax.driver.core.Metadata.rebuildSchema(Metadata.java:88)
	at com.datastax.driver.core.ControlConnection.refreshSchema(ControlConnection.java:265)
	at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:220)
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:168)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:644)
	at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:586)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:69)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:96)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:567)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:125)
	... 2 more
[OVERALL], RunTime(ms), 5616.0
[OVERALL], Throughput(ops/sec), 0.0

Thank you!

**Comment by busbey** [comment]
Hi @cgara this particular issue has already been closed. Could you please open a new one with your issue?

**Comment by cgara** [comment]
Okay
