### ISSUE TITLE
Get error message during benchmark hbase v 0.94 using YCSB 0.1.4

### ISSUE THREAD

**Issue by skambc** [brianfrankcooper/YCSB#208]
I use ycsb 0.1.4 with hbase 0.94,but it not work,here is the error info .By the way ,which hbase veresion can work with ycsb.
Exception in thread "Thread-1" java.lang.NoSuchMethodError: org.apache.hadoop.net.NetUtils.getInputStream(Ljava/net/Socket;)Lorg/apache/hadoop/net/SocketInputWrapper;
	at org.apache.hadoop.hbase.ipc.HBaseClient$Connection.setupIOstreams(HBaseClient.java:437)
	at org.apache.hadoop.hbase.ipc.HBaseClient.getConnection(HBaseClient.java:1127)
	at org.apache.hadoop.hbase.ipc.HBaseClient.call(HBaseClient.java:974)
	at org.apache.hadoop.hbase.ipc.WritableRpcEngine$Invoker.invoke(WritableRpcEngine.java:86)
	at com.sun.proxy.$Proxy5.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.hbase.ipc.WritableRpcEngine.getProxy(WritableRpcEngine.java:138)
	at org.apache.hadoop.hbase.ipc.HBaseRPC.waitForProxy(HBaseRPC.java:208)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getHRegionConnection(HConnectionManager.java:1498)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getHRegionConnection(HConnectionManager.java:1457)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getHRegionConnection(HConnectionManager.java:1444)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:1127)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1022)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegionInMeta(HConnectionManager.java:1124)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:1026)
	at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.locateRegion(HConnectionManager.java:983)
	at org.apache.hadoop.hbase.client.HTable.finishSetup(HTable.java:227)
	at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:170)
	at org.apache.hadoop.hbase.client.HTable.<init>(HTable.java:129)
	at com.yahoo.ycsb.db.HBaseClient.getHTable(HBaseClient.java:111)
	at com.yahoo.ycsb.db.HBaseClient.update(HBaseClient.java:295)
	at com.yahoo.ycsb.db.HBaseClient.insert(HBaseClient.java:350)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:145)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:461)
	at com.yahoo.ycsb.ClientThread.run(Client.java:269)
 0 sec: 0 operations;

**Comment by zhao777ying** [comment]
please show the directory about ../ycsb/hbase/lib

**Comment by skambc** [comment]
I have already solve thi problem. I copy the hbase's lib to this dirtory, In deed, the exist jar is already include the hbase jar,so delete them ,the problem go.
thank you


skambc@gmail.com
 
From: zhao777ying
Date: 2015-02-04 16:51
To: brianfrankcooper/YCSB
CC: skambc
Subject: Re: [YCSB] Get error message during benchmark hbase v 0.94 using YCSB 0.1.4 (#208)
please show the directory about ../ycsb/hbase/lib
