### ISSUE TITLE
Read a negative frame size (-2097152000)

### ISSUE THREAD

**Issue by bcaceiro** [brianfrankcooper/YCSB#218]
I'm trying to benchmark Cassandra with YCSB, but got this error when connecting. I have Cassandra running on a  Virtual Machine and YCSB running locally.

$ bin/ycsb load cassandra-10 -p hosts="10.17.0.36" -p port=9160 -P workloads/workloadb > test
Loading workload...
Starting test.
org.apache.thrift.transport.TTransportException: Read a negative frame size (-2097152000)!
	at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:133)
	at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
	at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378)
	at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:297)
	at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:204)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_set_keyspace(Cassandra.java:441)
	at org.apache.cassandra.thrift.Cassandra$Client.set_keyspace(Cassandra.java:426)
	at com.yahoo.ycsb.db.CassandraClient10.insert(CassandraClient10.java:439)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:148)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:461)
	at com.yahoo.ycsb.ClientThread.run(Client.java:277)

Any ideas how to solve this?

**Comment by busbey** [comment]
what version of cassandra are you running against? this looks like an RPC incompatibility.

**Comment by busbey** [comment]
please try the new CQL client support.

**Comment by busbey** [comment]
Closing as stale. If you are still experiencing this problem, please try the cassandra2 binding and then reopen.
