### ISSUE TITLE
YCSB issue to load / run

### ISSUE THREAD

**Issue by bharathstpi** [brianfrankcooper/YCSB#230]
I just downloaded YCSB and installed it. Here is the error I receive.
$]/opt/ycsb-0.1.4% bin/ycsb load basic -P workloads/workloada
Traceback (most recent call last):
  File "bin/ycsb", line 100, in <module>
    subprocess.call(ycsb_command)
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by cmatser** [comment]
You might try upgrading python to 2.7.3.

I can't tell from this output if the error is from python or from ycsb.  You can also try calling the ycsb code directly without the python script.  Something like:

java -cp "./conf:./core/target/core-0.1.4.jar" com.yahoo.ycsb.Client -db com.yahoo.ycsb.BasicDB -P workloads/workloada -s -load

I think that will give you the equivalent of what you were trying to accomplish.  Good luck.

**Comment by bharathstpi** [comment]
Hello Cmaster,

Thanks. I am trying to run a benchmark on couchbase 3.0 database and I have added the folder couchbase-binding/lib under ycsb-0.1.4 with the couchbase jar file couchbase-binding-0.1.4.jar. When I ran the test I got the below error.
]/opt/ycsb-0.1.4% bin/ycsb load couchbase -p hosts="172.22.225.79" -p bucket=benckmark -P workloads/workloadb
-p (No such file or directory)
[bhsingh@blrrnddbsm05]/opt/ycsb-0.1.4% bin/ycsb load couchbase -P workloads/workloadb
-P (No such file or directory)
[bhsingh@blrrnddbsm05]/opt/ycsb-0.1.4% bin/ycsb load couchbase workloads/workloadb
YCSB Client 0.1
Command line: -load -db com.yahoo.ycsb.db.CouchbaseClient -P workloads/workloadb
Loading workload...
Starting test.
Apr 28, 2015 6:07:20 AM com.couchbase.client.core.CouchbaseCore <init>
INFO: CoreEnvironment: {sslEnabled=false, sslKeystoreFile='null', sslKeystorePassword='null', queryEnabled=false, queryPort=8093, bootstrapHttpEnabled=true, bootstrapCarrierEnabled=true, bootstrapHttpDirectPort=8091, bootstrapHttpSslPort=18091, bootstrapCarrierDirectPort=11210, bootstrapCarrierSslPort=11207, ioPoolSize=4, computationPoolSize=4, responseBufferSize=16384, requestBufferSize=16384, kvServiceEndpoints=1, viewServiceEndpoints=1, queryServiceEndpoints=1, ioPool=NioEventLoopGroup, coreScheduler=CoreScheduler, eventBus=DefaultEventBus, packageNameAndVersion=couchbase-java-client/2.1.0 (git: 2.1.0), dcpEnabled=false, retryStrategy=BestEffort, maxRequestLifetime=75000, retryDelay=com.couchbase.client.core.time.ExponentialDelay@1e5043d6, reconnectDelay=com.couchbase.client.core.time.ExponentialDelay@2795a626, observeIntervalDelay=com.couchbase.client.core.time.ExponentialDelay@51cf1d17, keepAliveInterval=30000}
Exception in thread "Thread-1" com.couchbase.client.core.config.ConfigurationException: Unknown host null in bootstrap list.
        at com.couchbase.client.core.message.cluster.SeedNodesRequest.<init>(SeedNodesRequest.java:89)
        at com.couchbase.client.java.CouchbaseAsyncCluster.<init>(CouchbaseAsyncCluster.java:101)
        at com.couchbase.client.java.CouchbaseCluster.<init>(CouchbaseCluster.java:62)
        at com.couchbase.client.java.CouchbaseCluster.create(CouchbaseCluster.java:42)
        at com.couchbase.client.java.CouchbaseCluster.create(CouchbaseCluster.java:38)
        at com.yahoo.ycsb.db.CouchbaseClient.init(CouchbaseClient.java:27)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
        at com.yahoo.ycsb.ClientThread.run(Client.java:189)
Caused by: java.net.UnknownHostException: null
        at java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1295)
        at java.net.InetAddress.getAllByName0(InetAddress.java:1248)
        at java.net.InetAddress.getAllByName(InetAddress.java:1164)
        at java.net.InetAddress.getAllByName(InetAddress.java:1098)
        at java.net.InetAddress.getByName(InetAddress.java:1048)
        at com.couchbase.client.core.message.cluster.SeedNodesRequest.<init>(SeedNodesRequest.java:87)
        ... 7 more
[OVERALL], RunTime(ms), 1066.0
[OVERALL], Throughput(ops/sec), 0.0


Can you help me here ?

Regards,
Bharath

**Comment by cmatser** [comment]
Well, obviously the hosts information isn't getting passed in, but I can't tell why.  You have some strange things going on with python perhaps.  The "No such file or directory" errors are something I haven't encountered.  You'll need to fix those to pass the host information and other properties.  My suggestion is to figure out the python problems or ditch it and run it directly with the java command I mentioned previously.

**Comment by busbey** [comment]
@bharathstpi are you still attempting to do this? Have you tried running the java command directly? which couchbase binding are you using? is it the one from #136 by any chance?

**Comment by bharathstpi** [comment]
Hello Sean,

Thanks for your reply. The issue was java not being installed. I installed java and it is working fine now.

Thanks,
Bharath
