### ISSUE TITLE
YCSB cassandra-cql client 

### ISSUE THREAD

**Issue by nitendragautam** [brianfrankcooper/YCSB#232]
Hi,

I am trying to run cassandra-cql client for YCSB test cross three nodes  and i am getting this error .For the same three nodes cassandra-10 client is working fine and giving proper results  .I am using Cassandra 2.0.11.83 and also i am not using default token but using num_tokens =6 in my case. Is this the reason the cassandra-cql client is not working .

YCSB Client 0.1
Command line: -load cassandra-cql threads 2 -p hosts=XX.XX.XXX.XX2,XX.XX.XXX.XX3,XX.XX.XXX.XX4 -p port=9042 -P workloads/workloada -s -load
Loading workload...
Starting test.
 0 sec: 0 operations;
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.SystemProperties).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /XX.XX.XXX.XX2:9042 (com.datastax.driver.core.TransportException: [/1XX.XX.XXX.XX2:9042] Connection has been closed), /XX.XX.XXX.XX3:9042 (com.datastax.driver.core.TransportException: [/XX.XX.XXX.XX3:9042] Connection has been closed), /XX.XX.XXX.XX4:9042 (com.datastax.driver.core.TransportException: [/XX.XX.XXX.XX4:9042] Connection has been closed))
        at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:155)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:78)
        at com.yahoo.ycsb.ClientThread.run(Client.java:319)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /XX.XX.XXX.XX2:9042 (com.datastax.driver.core.TransportException: [/XX.XX.XXX.XX2:9042] Connection has been closed), /XX.XX.XXX.XX3:9042 (com.datastax.driver.core.TransportException: [/XX.XX.XXX.XX2] Connection has been closed), /XX.XX.XXX.XX4:9042 (com.datastax.driver.core.TransportException: [/XX.XX.XXX.XX4:9042] Connection has been closed))
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:223)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1236)
        at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:333)
        at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:138)
        ... 2 more

[OVERALL], Reconnections, 0.0
[OVERALL], RunTime(ms), 0.0
[OVERALL], Operations, 0.0
[OVERALL], Throughput(ops/sec), NaN

I created an yscb Kespace and "usertable" using cqlsh .
I am trying to figure out why cassandra-10 client is workings and Cassandra-CQL client is not working  

Please help me on this guys .

**Comment by cmatser** [comment]
When I implemented the Cassandra CQL client, I originally had it for a single server.  Later, I expanded it to test with multiple.  I decided to interpret the "host" property to be delimited with spaces (not commas).  Note there is no 's' just "host", not "hosts" as you have written.   I usually kept the property in a workload file.

If you specify on the command line, you'll have to use quotes like:

-p host="XX.XX.XXX.XX2 XX.XX.XXX.XX3 XX.XX.XXX.XX4"
or
-p "host=XX.XX.XXX.XX2 XX.XX.XXX.XX3 XX.XX.XXX.XX4"

One of those should work.  I tested with Cassandra 2.0.

Chrisjan

**Comment by nitendragautam** [comment]
Hello Chrisjan ,

Thanks for the quick reply .I followed your advice and fired up the test in my both local VM{Laptop} and my development cluster .
I think when we  use multiple ip  we have to give "hosts" as property .
When i used only  host="XX.XX.XXX.XX2 XX.XX.XXX.XX3 XX.XX.XXX.XX4" and ran the test i got following error
 com.yahoo.ycsb.DBException: com.yahoo.ycsb.DBException: Required property "hosts" missing for CassandraClient

So tried CQL client in my development  cluster 
/ycsb load cassandra-cql -s -threads 2 -p hosts="XX.XX.XXX.XX2 XX.XX.XXX.XX3 XX.XX.XXX.XX4" -p port=9042 -P workloads/workloadb 

And i got the same error as mentioned in my original post .

But when i  tested the same CQL client in my local VM { Cassandra 2.0.14},it is working .

So my question is "Is It datastax core driver related issue ?"  as cassandra -10 client is working fine .
now my next step is updating the pom.xml file of ycsb with latest version of cassandra jar files,rebuilding it and trying out again .
Let me know if i am moving in right direction .

Thanks
Nitendra

**Comment by nitendragautam** [comment]
Thanks for the help .I finally solved the problem .
I did not add the guava-17.0  dependency  as mentioned in 
https://github.com/joshwilliams/YCSB/commit/d478097b2cdd658956457675d96df4c4ff5fe3a2.
After adding this manually i could run the test with cassandra-cql client .

**Comment by cmatser** [comment]
Okay great.  I haven't had time to look into this further.  It could be that the changes I initially put in were updated.  I'm glad you got a solution.

Chrisjan

**Comment by busbey** [comment]
So do we need to add guava as a dependendcy for the cql client?

**Comment by nitendragautam** [comment]
If you look at ycsb script at {https://github.com/nitendragautam/YCSB/blob/master/bin/ycsb} and go to bottom of it you can find the dependency defined
if database == "cassandra-cql":
    classpath_additional = ["/home/ubuntu/ycsb/guava-17.0.jar"]

So i added the guava dependency manually and the client worked

**Comment by busbey** [comment]
oh... that is unfortunate. Okay, I'll file an issue about improving how we do deployment of optional dependencies to solve this generally.

thanks for thanks for following up!

**Comment by 13o6** [comment]
Hi @nitendragautam I've added both Guavan 17.0 and 18.0 dependencies in the pom.xml under YCSB/ but I still get the following exception (which I think it's similar to yours): 

<pre><code>com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.20.0.52 ([/10.20.0.52] Cannot connect))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:158)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:189)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.20.0.52 ([/10.20.0.52] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:186)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:644)
	at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:586)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:69)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:96)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:567)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:133)
	... 2 more
</code></pre>

Note: I tried with <code>-p host="localhost"</code> but with the same unfortunate result.

Also, not sure whether @busbey 's work on #250 affects this in any way..

**Comment by busbey** [comment]
please open a different ticket, as this one is closed. (#250 means that if you need guava as a dependency of the cql driver you should add it in just that binding, though I believe it already has all the dependencies)

**Comment by phemoski** [comment]
hi pls help cassandra-cql server cannot start, when ever it start it stop immediately, what should i do
