### ISSUE TITLE
MongoDB IllegalArgumentException: Invalid BSON field name _id - Mongo synchronous driver

### ISSUE THREAD

**Issue by betotorres** [brianfrankcooper/YCSB#277]
I followed all the instructions to install YCSB. I did the tests in mysql successfully, however When I try to use the synchronous Mongodb driver I get an error.

The error happens only with the synchronous driver, since I can execute successfully the commands "./bin/ycsb load mongodb-async -s -P workloads/workloads" and "./ben/ycsb run mongodb-async -s -P workloads/workloada".

The error that happen when I try to execute "./bin/ycsb load mongodb -s -P workloads/workloada" is the following:

Loading workload...
Starting test.
2015-06-04 20:35:59:911 0 sec: 0 operations;
java.lang.IllegalArgumentException: Invalid BSON field name _id
        at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:494)
        at org.bson.codecs.DocumentCodec.writeMap(DocumentCodec.java:188)
        at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:131)
        at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:45)
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
        at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
        at com.mongodb.connection.UpdateCommandMessage.writeTheWrites(UpdateCommandMessage.java:85)
        at com.mongodb.connection.UpdateCommandMessage.writeTheWrites(UpdateCommandMessage.java:42)
        at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:112)
        at com.mongodb.connection.BaseWriteCommandMessage.encodeMessageBody(BaseWriteCommandMessage.java:35)
        at com.mongodb.connection.RequestMessage.encode(RequestMessage.java:132)
        at com.mongodb.connection.BaseWriteCommandMessage.encode(BaseWriteCommandMessage.java:89)
        at com.mongodb.connection.WriteCommandProtocol.sendMessage(WriteCommandProtocol.java:170)
        at com.mongodb.connection.WriteCommandProtocol.execute(WriteCommandProtocol.java:73)
        at com.mongodb.connection.UpdateCommandProtocol.execute(UpdateCommandProtocol.java:63)
        at com.mongodb.connection.UpdateCommandProtocol.execute(UpdateCommandProtocol.java:37)
        at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:155)
        at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:219)
        at com.mongodb.connection.DefaultServerConnection.updateCommand(DefaultServerConnection.java:120)
        at com.mongodb.operation.MixedBulkWriteOperation$Run$3.executeWriteCommandProtocol(MixedBulkWriteOperation.java:440)
        at com.mongodb.operation.MixedBulkWriteOperation$Run$RunExecutor.execute(MixedBulkWriteOperation.java:604)
        at com.mongodb.operation.MixedBulkWriteOperation$Run.execute(MixedBulkWriteOperation.java:361)
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:148)
        at com.mongodb.operation.MixedBulkWriteOperation$1.call(MixedBulkWriteOperation.java:141)
        at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:186)
        at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:177)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:141)
        at com.mongodb.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:72)
        at com.mongodb.Mongo.execute(Mongo.java:745)
        at com.mongodb.Mongo$2.execute(Mongo.java:728)
        at com.mongodb.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:482)
        at com.mongodb.MongoCollectionImpl.update(MongoCollectionImpl.java:474)
        at com.mongodb.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:325)
        at com.yahoo.ycsb.db.MongoDbClient.insert(MongoDbClient.java:253)
        at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:148)
        at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:543)
        at com.yahoo.ycsb.ClientThread.run(Client.java:277)
2015-06-04 20:36:00:843 1 sec: 0 operations; [INSERT AverageLatency(us)=93170] [CLEANUP AverageLatency(us)=1996]

**Comment by busbey** [comment]
ping @allanbank

**Comment by allanbank** [comment]
@busbey  - Thanks for the ping. I think I see the problem.  I will submit a pull request once I verify.
