### ISSUE TITLE
Cannot reference non-existing region attributes named "PARTITION"

### ISSUE THREAD

**Issue by GaikwadPurwa** [brianfrankcooper/YCSB#295]
After executing this command:
 ./bin/ycsb load gemfire -p gemfire.serverhost=localhost -p gemfire.serverport=1527 -s -P workloads/workloada > outputLoad.txt

I get the following error:
Exception in thread "Thread-1" java.lang.IllegalStateException: You must use client-cache in the cache.xml when ClientCacheFactory is used.
	at com.gemstone.gemfire.internal.cache.xmlcache.CacheCreation.create(CacheCreation.java:379)
	at com.gemstone.gemfire.internal.cache.xmlcache.CacheXmlParser.create(CacheXmlParser.java:320)
	at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.loadCacheXml(GemFireCacheImpl.java:4248)
	at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.initializeDeclarativeCache(GemFireCacheImpl.java:1174)
	at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.init(GemFireCacheImpl.java:1018)
	at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.create(GemFireCacheImpl.java:678)
	at com.gemstone.gemfire.cache.client.ClientCacheFactory.basicCreate(ClientCacheFactory.java:207)
	at com.gemstone.gemfire.cache.client.ClientCacheFactory.create(ClientCacheFactory.java:162)
	at com.yahoo.ycsb.db.GemFireClient.init(GemFireClient.java:125)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:197)
2015-06-12 17:31:20:405 3 sec: 0 operations; 

So I changed the xml as following:
`<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE client-cache PUBLIC
    "-//GemStone Systems, Inc.//GemFire Declarative Caching 7.0//EN"
    "http://www.gemstone.com/dtd/cache7_0.dtd">
<client-cache copy-on-read="false" >
    <region name="usertable" refid="PARTITION"/> 
</client-cache>`

Now I am getting the following error:
Exception in thread "Thread-1" com.gemstone.gemfire.cache.CacheXmlException: While reading Cache XML file:/home/ubuntu/YCSB/gemfire/src/main/conf/cache.xml. While parsing XML, caused by java.lang.IllegalStateException: Cannot reference non-existing region attributes named "PARTITION"
	at com.gemstone.gemfire.internal.cache.xmlcache.CacheXmlParser.parse(CacheXmlParser.java:241)
	at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.loadCacheXml(GemFireCacheImpl.java:4244)
	at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.initializeDeclarativeCache(GemFireCacheImpl.java:1174)
	at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.init(GemFireCacheImpl.java:1018)
	at com.gemstone.gemfire.internal.cache.GemFireCacheImpl.create(GemFireCacheImpl.java:678)
	at com.gemstone.gemfire.cache.client.ClientCacheFactory.basicCreate(ClientCacheFactory.java:207)
	at com.gemstone.gemfire.cache.client.ClientCacheFactory.create(ClientCacheFactory.java:162)
	at com.yahoo.ycsb.db.GemFireClient.init(GemFireClient.java:125)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:197)
Caused by: java.lang.IllegalStateException: Cannot reference non-existing region attributes named "PARTITION"
	at com.gemstone.gemfire.internal.cache.xmlcache.RegionAttributesCreation.inheritAttributes(RegionAttributesCreation.java:1096)
	at com.gemstone.gemfire.internal.cache.xmlcache.RegionAttributesCreation.inheritAttributes(RegionAttributesCreation.java:1071)
	at com.gemstone.gemfire.internal.cache.xmlcache.RegionCreation.<init>(RegionCreation.java:129)
	at com.gemstone.gemfire.internal.cache.xmlcache.RegionCreation.<init>(RegionCreation.java:134)
	at com.gemstone.gemfire.internal.cache.xmlcache.CacheXmlParser.startRegion(CacheXmlParser.java:1112)
	at com.gemstone.gemfire.internal.cache.xmlcache.CacheXmlParser.startElement(CacheXmlParser.java:2862)
	at com.gemstone.gemfire.internal.cache.xmlcache.CacheXmlParser$DefaultHandlerDelegate.startElement(CacheXmlParser.java:3766)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(XMLDTDValidator.java:766)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:356)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2786)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:332)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
	at com.gemstone.gemfire.internal.cache.xmlcache.CacheXmlParser.parse(CacheXmlParser.java:203)
	... 9 more
2015-06-12 17:38:34:245 3 sec: 0 operations;

**Comment by busbey** [comment]
What version of gemfire are you taking to?

**Comment by GaikwadPurwa** [comment]
gfxd 1.4.1
