### ISSUE TITLE
improve error message when java isn't found

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#345]
right now if there's no JAVA_HOME and java isn't in the path we get:

```
Traceback (most recent call last):
  File "./bin/ycsb", line 209, in <module>
    sys.exit(main())
  File "./bin/ycsb", line 205, in main
    return subprocess.call(ycsb_command)
  File "/usr/lib64/python2.6/subprocess.py", line 478, in call
    p = Popen(*popenargs, **kwargs)
  File "/usr/lib64/python2.6/subprocess.py", line 642, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.6/subprocess.py", line 1234, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Which is pretty terrible. If there's no JAVA_HOME, do a test for the java command and give a better message. Probably the same thing should be done for where we call maven.

**Comment by gkamat** [comment]
I'll pick this one up and fix next week.

**Comment by busbey** [comment]
ugh. ran into this again today.

**Comment by kashif12** [comment]
Found the same issue in ycsb , thanks to the author for pointing out solution.
