### ISSUE TITLE
CassandraCQLClient ClassNotFoundException

### ISSUE THREAD

**Issue by 13o6** [brianfrankcooper/YCSB#386]
I built the latest Cassandra and YCSB source-code, then downloaded ycsb-0.1.4.tar.gz unziped, copied the YCSB binaries to ycsb-0.1.4/bin (according to [1]) but trying to run the following command: 

<pre><code> $>bin/ycsb load cassandra-cql -p host="localhost" -p port=9042 -P workloads/workloada</code></pre>

but I'm getting the following exception: 

<pre><code>java.lang.ClassNotFoundException: com.yahoo.ycsb.db.CassandraCQLClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
	at com.yahoo.ycsb.Client.main(Client.java:713)
Exception in thread "Thread-1" java.lang.NullPointerException
	at com.yahoo.ycsb.ClientThread.run(Client.java:189)
</code></pre>

Any ideas what may be causing this? Any hints or indications are apreciated.

[1] - http://gureya.blogspot.se/2014/09/integrating-ycsb-with-cassandra.html

**Comment by busbey** [comment]
you should work off of the latest release ([0.3.0](https://github.com/brianfrankcooper/YCSB/releases/tag/0.3.0)), which incorporates the changes from @cmatser.

Unfortunately, that code currently has known problems with Cassandra 2.1+ (ref #293 ) If you have the time and inclination to figure out our incompatibility with the latest Cassandra release, I'm sure we can give help on hte YCSB side.

**Comment by 13o6** [comment]
Solution: 
I was using <code>cassandra-3.2</code> which seems to have been the main problem. I downgraded to <code>cassandra-2.1</code>, changed some [code](https://github.com/brianfrankcooper/YCSB/issues/204#issuecomment-68693026) and also the dependencies - see [comment](https://github.com/brianfrankcooper/YCSB/issues/263#issuecomment-120937321) in #263 and it now works.
