### ISSUE TITLE
NoHostAvailableException in 0.3.0 for cassandra-3.2

### ISSUE THREAD

**Issue by 13o6** [brianfrankcooper/YCSB#387]
Following @busbey suggestion in #386 I built the latest release and tried to run it but resulted in a <code>com.yahoo.ycsb.DBException</code> exception:
<pre><code>com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.20.0.52 ([/10.20.0.52] Cannot connect))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:158)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.20.0.52 ([/10.20.0.52] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:186)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:644)
	at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:586)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:69)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:96)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:567)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:133)
	... 2 more
</code></pre>

I tried with localhost as well as the machine's private IP address, but the result is the same. 

I also manually included the Guava dependencies (as proposed in #232 ) for both 17.0 and 18.0 with no improvements..

**Comment by busbey** [comment]
Is that the correct IP address for your Cassandra instance? Can cqlsh connect to the Cassandra instance from the node where you're running the YCSB client?

**Comment by busbey** [comment]
Also what version of Cassandra is the cluster running?

**Comment by 13o6** [comment]
Follow-up with some debugging/troubleshooting steps I took: 
1) After setting debug flags across <code>CassandraCQLClient.java</code> I found that the culprit are lines 131-133 
2) <code>nodetool status </code> output: 
<pre><code>Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  154.85 KB  256          ?       a5172c1b-f2b7-4582-b61f-125209019287  rack1
</code></pre>
3) <code>cqlsh</code> output upon connection: 
<pre><code>Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.0-alpha1-SNAPSHOT | CQL spec 3.3.0 | Native protocol v4]
Use HELP for help.
</code></pre>
4) Port and host used in <code>Cluster.builder()</code> Port:9042	Hosts:127.0.0.1

Note: I'm running my own build of Cassandra after having forked the repo.
PS: Thanks for your reply @busbey

**Comment by 13o6** [comment]
@busbey I'm running the YCSB client on the same host as the single-node Cassandra cluster for now. I've tried localhost, 127.0.0.1 and its private IP address but the same exception is thrown. <code>cqlsh</code> appears to be connecting just fine as I've shown in the comment above

**Comment by busbey** [comment]
well, we have #293 has things broken on 2.1+, but the errors never look like this IIRC.

shouldn't num 4 above be correct? it looks like cqlsh is also connecting to host 127.0.0.1 and port 9042?

Is there more of a stacktrace that shows why the connection attempt failed? Maybe this is a client/server protocol mismatch since the Cassandra version is at 3.0, which I think became 2.2?

**Comment by 13o6** [comment]
*(Partially)* **Solved!**
I stumbled across this [stackoverflow answer](https://stackoverflow.com/questions/31824537/error-unable-to-connect-to-cassandra-server-unconfigured-table/31837438#31837438) which suggested a downgrade. 
Downgraded cassandra to 2.1, then changed the source-code from <code>cluster.shutdown()</code> to <code>cluster.close()</code> as done in #204 but now throws another exception which I think it's not that relevant to the title: 
<pre><code>
23:39:36.774 [Thread-1] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetectionLevel: simple
23:39:36.914 [Thread-1] DEBUG c.d.driver.core.SystemProperties - com.datastax.driver.DISABLE_COALESCING is undefined, using default value false
Exception in thread "Thread-1" java.lang.NoSuchMethodError: io.netty.util.UniqueName.<init>(Ljava/lang/String;)V
	at io.netty.channel.ChannelOption.<init>(ChannelOption.java:136)
	at io.netty.channel.ChannelOption.valueOf(ChannelOption.java:99)
	at io.netty.channel.ChannelOption.<clinit>(ChannelOption.java:42)
	at com.datastax.driver.core.Connection$Factory.newBootstrap(Connection.java:793)
	at com.datastax.driver.core.Connection$Factory.access$100(Connection.java:666)
	at com.datastax.driver.core.Connection.initAsync(Connection.java:129)
	at com.datastax.driver.core.Connection$Factory.open(Connection.java:721)
	at com.datastax.driver.core.ControlConnection.tryConnect(ControlConnection.java:248)
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:194)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:82)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1307)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:339)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:158)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
</code></pre>

**Comment by 13o6** [comment]
And finally *solved!*. 
The above exception: 
<code>Exception in thread "Thread-1" java.lang.NoSuchMethodError: io.netty.util.UniqueName.(Ljava/lang/String;)V </code> 
has also been encountered in #263 and it's been solved by changing the root <code>pom.xml</code> dependencies to an earlier version of cassandra, like <code>2.0.16</code>

**Comment by pranavhonrao9** [comment]
I am trying to connectcom.datastax.driver.core.exceptions.**NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042  single node cassandra cluster through zipplin but I am getting error** like this. 
I have changed cassandra.yaml but still unable to solve that issue.Please help

**Comment by kruthar** [comment]
@pranavhonrao9 - can you start your own issue with the problem you are having thoroughly described with:
- the command you are running
- any YCSB configuration files you are referencing
- the full output you are seeing

**Comment by pranavhonrao9** [comment]
@kruthar The problem was solved. I had made changes in conf-env.sh file.

**Comment by rosstex** [comment]
What were the changes?

**Comment by ankitaa89** [comment]
Connecting to IP Address 192.168.100.4:9042...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.100.4:9042 (com.datastax.driver.core.exceptions.TransportException: [/192.168.100.4] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:231)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:77)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1414)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:393)
	at com.home.caspackage.CassaCluster.connect(CassaCluster.java:24)
	at com.home.caspackage.CassaCluster.main(CassaCluster.java:52)



I am getting this exception. I have tried a lot of options but none worked. Please suggest
