### ISSUE TITLE
Maven Build Error when compiling YCSB: "Error reading assemblies"

### ISSUE THREAD

**Issue by maxkra** [brianfrankcooper/YCSB#406]
I am trying to compile the YCSB Project with the `clean package` command as suggested in the Getting Started pages. The project is downloaded from the github site as a .zip, got unzipped and no changes have been made. I get an Build Error when compiling that says:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Error reading assemblies: Descriptor with ID 'datastore-specific-assembly' not found
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error reading assemblies: Descriptor with ID 'datastore-specific-assembly' not found
    at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:453)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    ... 17 more
Caused by: org.apache.maven.plugin.assembly.io.AssemblyReadException: Descriptor with ID 'datastore-specific-assembly' not found
    at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.addAssemblyForDescriptorReference(DefaultAssemblyReader.java:213)
    at org.apache.maven.plugin.assembly.io.DefaultAssemblyReader.readAssemblies(DefaultAssemblyReader.java:133)
    at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:449)
    ... 19 more
```
I hope someone can help me. Thanks.

**Comment by busbey** [comment]
Please copy/paste the output of "mvn --version".

What platform are you on? (Windows, centos, Ubuntu, etc)

**Comment by maxkra** [comment]
Here is the requested information.
Version of OS:
```
$ ~/YCSB/git/YCSB$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
NAME="Ubuntu"
VERSION="14.04.2 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.2 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
```

Version of Maven and JDK
```
$ ~/YCSB/git/YCSB$ mvn -version
Apache Maven 2.2.1 (rdebian-14)
Java version: 1.7.0_79
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux" version: "3.13.0-49-generic" arch: "amd64" Family: "unix"```

**Comment by busbey** [comment]
Your maven version is too old; we require maven 3.

Do you need to compile some local changes? If not, you could download one of the convenience binaries and run ycsb without updating your maven install.

**Comment by maxkra** [comment]
Ok thank you so much! That was the Problem.
I have to compile local changes as i have to develop some own workloads.

**Comment by mj-jadhav** [comment]
I have updated maven but I am still getting this error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (default) on project dynamodb-binding: Execution default of goal org.apache.maven.plugins:maven-assembly[17/1865$
.5.5:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.5.5 or one of its dependencies could not be resolved: Could not find artifact com.yahoo.ycsb:datastore-specific-descriptor:jar:0
.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (default) on project dynamodb-binding: Execution default of goal
org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.5.5 or one of its dependencies could not be resolved: Could not find artifact co
m.yahoo.ycsb:datastore-specific-descriptor:jar:0.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.5.5 or one of its dependencies could not be resolved: Could not find artifact com.yahoo.ycsb:datastore-specific-descriptor:jar:0.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:82)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.5.5 or one of its dependencies could not be resolved: Could not find artifact com.yahoo.ycsb:datastore-specific-descriptor:jar:0.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:215)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:353)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:321)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:175)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:78)
        ... 20 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact com.yahoo.ycsb:datastore-specific-descriptor:jar:0.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:207)
        ... 24 more
```

OS version:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"
```

Version of Maven and JDK:
```
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.2.0-68-virtual", arch: "amd64", family: "unix"
```

**Comment by busbey** [comment]
Please open a new issue; closed issues don't notify folks the same way.

**Comment by WXxxHui** [comment]
![微信截图_20240813161843](https://github.com/user-attachments/assets/af054c06-7849-42ed-95e6-28313ef94ce2)
![微信截图_20240813161849](https://github.com/user-attachments/assets/a1ea2ae6-ba39-4e3a-a43b-a49dfbdcad82)
This is why？
