### ISSUE TITLE
NoHostAvailableException testing Cassandra 2.0.15 with YCSB 0.4.0-RC1

### ISSUE THREAD

**Issue by Thomas-Yang** [brianfrankcooper/YCSB#418]
I am testing YCSB 0.4.0-RC1 with Cassandra 2.0.15. By performing the load operation, it gives me the following errors:

com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1 ([localhost/127.0.0.1] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [localhost/127.0.0.1] Channel has been closed)))
at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:158)
at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
at com.yahoo.ycsb.ClientThread.run(Client.java:289)

I also tried to change the root pom.xml to match the cassandra version (1.29-->2.0.15 and cql 1.0.3-->2.0.11), then it gives me "cannot find symbol method shutdown() in CassandraCQLClient.java". I found one closed issue in #387 and changed the shutdown() to close(). Then it passed the compilation but still gave NoHostAvailableException. Any ideas? 

Do we maintain any documentation to list the compatible backend datastores for a particular YCSB version?

**Comment by cmccoy** [comment]
Unless there's been a regression, at least the Thrift bindings (`cassandra-10`) should work.  Could you share your command line? 
You might also try setting the port explicitly: it looks like it [defaults to 9160](https://github.com/brianfrankcooper/YCSB/blob/master/cassandra/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java#L110) for the CQL binding, but I think the CQL default is 9042 ([source](https://github.com/apache/cassandra/blob/trunk/conf/cassandra.yaml#L491)).

**Comment by Thomas-Yang** [comment]
Thank you for pointing it out. I think that is the reason for the NoHostAvailableException. Here is my command line for the CQL binding:
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloadb -P settings_load_cql.dat -s -load
The parameters within settings_load_cql.dat:
host=localhost
recordcount=500000
operationcount=500000
threadcount=8
port=9042

So the difference between CQL binding and Cassandra-10 binding is the following (correct me if I am wrong):
1. the default port for CQL is 9042, while 9160 for Cassandra-10 (thrift port);
2. the host property for CQL is "host", while "hosts" for Cassandra-10;
3. the default keyspace for CQL is "ycsb", while "usertable" for Cassandra-10;

The CQL binding works fine with workloadb, however, the Cassandra-10 binding never finishes for the load operation.
Command line: -db com.yahoo.ycsb.db.CassandraClient10 -P workloads/workloadb -P settings_load_10.dat -s -load
The parameters within settings_load_10.dat:
hosts=localhost
recordcount=500000
operationcount=500000
threadcount=8
2015-09-28 14:17:23:690 0 sec: 0 operations; est completion in 0 seconds 
2015-09-28 14:17:33:663 10 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:17:43:663 20 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:17:53:663 30 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:18:03:663 40 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:18:13:663 50 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:18:23:663 60 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:18:33:663 70 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:18:43:663 80 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:18:53:663 90 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:19:03:663 100 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:19:13:663 110 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:19:23:663 120 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:19:33:663 130 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:19:43:663 140 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2015-09-28 14:19:53:663 150 sec: 0 operations; est completion in 106751991167300 days 15 hours 
InvalidRequestException(why:Not enough bytes to read value of component 0)
	at org.apache.cassandra.thrift.Cassandra$batch_mutate_result.read(Cassandra.java:20833)
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_batch_mutate(Cassandra.java:964)
	at org.apache.cassandra.thrift.Cassandra$Client.batch_mutate(Cassandra.java:950)
	at com.yahoo.ycsb.db.CassandraClient10.insert(CassandraClient10.java:477)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:158)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:549)

Any ideas?

**Comment by cmccoy** [comment]
Sorry, I haven't seen that before.  Are you creating the keyspace with `cassandra-cli`?

Thanks for bringing up these inconsistencies - I opened #419 to track making the CQL and Thrift bindings consistent.

**Comment by Thomas-Yang** [comment]
Not really, I am using the ```cqlsh``` to create the keyspace. Why do we end up with separate keyspaces for the two bindings (ycsb for CQL and usertable for cassandra-10)?

**Comment by cmccoy** [comment]
If using the Thrift binding is important to you, could you try with `cassandra-cli`? That's worked for me in the past; I haven't tested creating the table via CQL, but accessing via Thrift.

> Why do we end up with separate keyspaces for the two bindings (ycsb for CQL and usertable for cassandra-10)?

No reason I know of, other than that database bindings have been contributed by individual volunteers at various times. I think pull requests improving consistency would be warmly received :).

**Comment by Thomas-Yang** [comment]
```cassandra-cli``` solves the problem. It seems the keyspace and table generated by ```cassandra-cli``` and ```cqlsh``` is not totally compatible. The commands I tried out are listed as follows:

 | cassandra-10 | cqlsh
------------ | ------------- | -------------
create keyspace | create keyspace **usertable** with placement_strategy = 'org.apache.cassandra.locator.SimpleStrategy' and strategy_options = {replication_factor:1}; | create keyspace **ycsb** with replication = {'class' : 'SimpleStrategy', 'replication_factor': 1 };
create table | create column family **data** with column_type = 'Standard' and comparator = 'UTF8Type'; | create table **usertable** (y_id text primary key,field0 varchar,field1 varchar,field2 varchar,field3 varchar,field4 varchar,field5 varchar,field6 varchar,field7 varchar,field8 varchar,field9 varchar);

Since the ```cassandra-cli``` (the Thrift API) will be removed soon (from v3.0 I guess), I am not sure it worths the effort to improve the consistency. Anyway, I do hope the above commands are useful for people still want to try out both bindings.

**Comment by cmccoy** [comment]
Thanks for documenting this, and for bringing up the inconsistencies.
