### ISSUE TITLE
Cassandra - Issues running Scans in Cassandra

### ISSUE THREAD

**Issue by swaminatha** [brianfrankcooper/YCSB#429]
When i run, Scan operations in Cassandra, i find an abnormal behavior in the output. I periodically get  a InvalidRequestException(why:maxRows must be positive) after 15 scan requests.
 maxscanlength is set to 100 in my case.  
The cassandra is a standalone setup, and i am running 100 scan operations on 1000 records. with scanproportion=1
I am pasting the trace from my terminal for reference
Please help me identify, is there any steps i am missing or any mistakes in my configuration to be corrected.

Thanks

```
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.CassandraClient10 -p hosts=127.0.0.1 -p recordcount=1000 -p fieldcount=10 -p fieldlength=100 -p operationcount=100 -p workload=com.yahoo.ycsb.workloads.CoreWorkload -p readallfields=true -p readproportion=0 -p updateproportion=0 -p scanproportion=1 -p insertproportion=0 -p maxscanlength=100 -p requestdistribution=zipfian -p scanlengthdistribution=zipfian -sLoading workload...
 -t
Starting test.
2015-10-08 01:16:08:009 0 sec: 0 operations; 
2015-10-08 01:16:18:011 10 sec: 11 operations; 1.1 current ops/sec; [SCAN AverageLatency(us)=23054.27] 
2015-10-08 01:16:28:013 20 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:16:38:014 30 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:16:48:015 40 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:16:58:016 50 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:17:08:018 60 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:17:18:019 70 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:17:28:020 80 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:17:38:021 90 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:17:48:023 100 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:17:58:023 110 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:18:08:025 120 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:18:18:026 130 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:18:28:028 140 sec: 11 operations; 0 current ops/sec;  
2015-10-08 01:18:38:029 150 sec: 11 operations; 0 current ops/sec;  
InvalidRequestException(why:maxRows must be positive)
	at org.apache.cassandra.thrift.Cassandra$get_range_slices_result.read(Cassandra.java:12088)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_get_range_slices(Cassandra.java:732)
	at org.apache.cassandra.thrift.Cassandra$Client.get_range_slices(Cassandra.java:704)
	at com.yahoo.ycsb.db.CassandraClient10.scan(CassandraClient10.java:347)
	at com.yahoo.ycsb.DBWrapper.scan(DBWrapper.java:110)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:605)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:491)
	at com.yahoo.ycsb.ClientThread.run(Client.java:241)
InvalidRequestException(why:maxRows must be positive)
	at org.apache.cassandra.thrift.Cassandra$get_range_slices_result.read(Cassandra.java:12088)
	at org.apache.cassandra.thrift.Cassandra$Client.recv_get_range_slices(Cassandra.java:732)
	at org.apache.cassandra.thrift.Cassandra$Client.get_range_slices(Cassandra.java:704)
	at com.yahoo.ycsb.db.CassandraClient10.scan(CassandraClient10.java:347)
	at com.yahoo.ycsb.DBWrapper.scan(DBWrapper.java:110)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:605)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:491)
	at com.yahoo.ycsb.ClientThread.run(Client.java:241)
2015-10-08 01:18:48:030 160 sec: 32 operations; 2.1 current ops/sec; [SCAN AverageLatency(us)=7170681.67]
```

**Comment by kruthar** [comment]
Hi @swaminatha 

What version of Cassandra are you working with? Do other workload configurations and operations work as expected?

**Comment by swaminatha** [comment]
Yes , it does.
Version of Cassandra 2.0.16

**Comment by kruthar** [comment]
OK - The Cassandra documentation advises using CQL based connection methods rather than Thrift based with more modern versions of Cassandra. We have ```cassandra-cql``` for Cassandra 2.0 and ```cassandra2-cql``` for Cassandra 2.1+.

Can you try using the ```cassandra-cql``` binding?

**Comment by kruthar** [comment]
@swaminatha - are you still seeing issues? Did the newer CQL clients help?

**Comment by swaminatha** [comment]
Andy,

Plz gimme sometime. I will send a detailed mail on my observation.

Thanks,
Surya

**Comment by busbey** [comment]
any update here?

**Comment by swaminatha** [comment]
The issue got resolved after setting the scandistribution to earlier. With Cassandra, scan distribution as zipfian i faced the issue mentioned in the trace.
