### ISSUE TITLE
Error with hbase 1.1.2, failed to identify hdfs

### ISSUE THREAD

**Issue by jorgealvarezcopo** [brianfrankcooper/YCSB#446]
I downloaded ycsb 0.4.0 and execute:
ycsb load hbase10 -P workloads/workloada -cp /etc/hbase/conf -p table=usertable -p columnfamily=family
It works but before the results throw the warning. Why?

2015-10-23 12:38:26,694 WARN  [Thread-3] util.DynamicClassLoader: Failed to identify the fs of dir hdfs://bbvoophdfs:8020/hbase/lib, ignored
java.io.IOException: No FileSystem for scheme: hdfs
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2644)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2651)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.hadoop.hbase.util.DynamicClassLoader.<init>(DynamicClassLoader.java:104)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.<clinit>(ProtobufUtil.java:241)
        at org.apache.hadoop.hbase.ClusterId.parseFrom(ClusterId.java:64)
        at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:75)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:879)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:635)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:116)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
        at com.yahoo.ycsb.ClientThread.run(Client.java:289)

I have the correct hbase jars.

**Comment by busbey** [comment]
Hi!

that's a harmless message that can be ignored. What's happening is that hbase has a feature where additional classes get loaded from HDFS. The client does not need any such classes, but in most client deployments (like yours) the HDFS jars are not present so the client can't even figure out where the jars might be.

If you'd like to remedy the issue, you can ensure hbase.dynamic.jars.dir isn't set.

If you'd like to suppress the message, you'll need to set the log level for the logger `org.apache.hadoop.hbase.util.DynamicClassLoader` to ERROR.

**Comment by Manoj-Gandikota** [comment]
Hi,

I am also getting the above error while trying to run "YCSB" from one of the client machines in my cluster. I am using Cloudera's CDH 5.8.0. As suggested above, I have changed the log level for `org.apache.hadoop.hbase.util.DynamicClassLoader` to ERROR. But still I am getting this message. Please let me know how to get rid of this message.  Below is the sysout while running the ycsb benchmarking.

`16/10/02 22:50:48 INFO zookeeper.ZooKeeper: Initiating client connection, connectString=node1:2181 sessionTimeout=60000 watcher=hconnection-0x7a02586a0x0, quorum=node1:2181, baseZNode=/hbase
16/10/02 22:50:48 INFO zookeeper.ClientCnxn: Opening socket connection to server node1/10.50.152.128:2181. Will not attempt to authenticate using SASL (unknown error)
16/10/02 22:50:48 INFO zookeeper.ClientCnxn: Socket connection established to node1/10.50.152.128:2181, initiating session
16/10/02 22:50:48 INFO zookeeper.ClientCnxn: Session establishment complete on server node1/10.50.152.128:2181, sessionid = 0x15779e36ae33f92, negotiated timeout = 60000
16/10/02 22:50:49 WARN util.DynamicClassLoader: Failed to identify the fs of dir hdfs://node1:8020/hbase/lib, ignored
java.io.IOException: No FileSystem for scheme: hdfs
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2579)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2586)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:89)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2625)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2607)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:368)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
        at org.apache.hadoop.hbase.util.DynamicClassLoader.<init>(DynamicClassLoader.java:104)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.<clinit>(ProtobufUtil.java:232)
        at org.apache.hadoop.hbase.ClusterId.parseFrom(ClusterId.java:64)
        at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:75)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:86)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:833)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:623)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:149)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:99)
        at com.yahoo.ycsb.ClientThread.run(Client.java:418)
        at java.lang.Thread.run(Thread.java:745)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
16/10/02 22:50:53 INFO client.ConnectionManager$HConnectionImplementation: Closing master protocol: MasterService
16/10/02 22:50:53 INFO client.ConnectionManager$HConnectionImplementation: Closing zookeeper sessionid=0x15779e36ae33f92
16/10/02 22:50:53 INFO zookeeper.ZooKeeper: Session: 0x15779e36ae33f92 closed`
