### ISSUE TITLE
how to build a specific Database on YCSB

### ISSUE THREAD

**Issue by Hadi14** [brianfrankcooper/YCSB#538]
Hi
if i want build a specific database on YCSB , can i do it for like OrientDB?

**Comment by kruthar** [comment]
YCSB already has an OrientDB client: https://github.com/brianfrankcooper/YCSB/tree/master/orientdb.

**Comment by Hadi14** [comment]
yes i have seen it but i want use "mvn clean package" only for OrientDB 

if i build it already on Win platform , can i copy Src and target Folder to My current YCSB folder on ubuntu?

**Comment by kruthar** [comment]
If you are not developing in YCSB (meaning not changing any code), and just running workloads only, I would suggest not dealing with building at all. Just download a release. And if you are just downloading a release, then just download the release onto each machine.

**Comment by Hadi14** [comment]
very excusme i'm not understand fully , i want benckmark OrientDB on YCSB released 0.5.0  , i according to following link i should build it("mvn clean package") , since may no success for all binding , now  i want build it only  for OrienteDB , is it possible?
https://github.com/brianfrankcooper/YCSB/tree/master/orientdb

this command will download only OrienteDB ? or all YCSB?
git clone git://github.com/nuvolabase/YCSB.git

**Comment by busbey** [comment]
Our apologies, not all of the datastore bindings have been cleaned up yet to point folks to our common use documentation. I've filed #539 to correct the README, it should not be telling you to grab a third party git repo.

if you want to test against OrientDB you can grab the binary for release 0.5.0 over here:

https://github.com/brianfrankcooper/YCSB/releases/tag/0.5.0

OrientDB is not yet in our list of "tested and supported" datastores, so there isn't an orientdb specific convenience binary.

The release binary that covers all datastores is:

https://github.com/brianfrankcooper/YCSB/releases/download/0.5.0/ycsb-0.5.0.tar.gz

The primary difference between this release artifact and one of the per-datastore artifacts is size, because this one comes with the needed bits to run against *any* of the datastores we have active in the build tree.

You will have to set up an instance of OrientDB yourself, but given such an instance and the above release artifact you should be able to run ycsb against OrientDB without compiling anything from YCSB.

**Comment by kruthar** [comment]
Take a look at the main README: https://github.com/brianfrankcooper/YCSB, there is a Getting Started guide there that is exactly what you want. Just replace ```basic``` with whatever client you want to use.

**Comment by Hadi14** [comment]
so , if i use current binding of OrientDB that there are YCSB-0.5.0 released , i can benchmark it like other Databases.

**Comment by busbey** [comment]
yep.

**Comment by Hadi14** [comment]
other question : for benchmark cassandra we create keyspace and usertable. for OrientDB not necessary?

**Comment by busbey** [comment]
Sorry, I haven't tried to use OrientDB yet. The lack of clear guidance in the README for that datastore binding is part of why it isn't in the tested/supported list. :person_frowning: 

Does it fail when you try to run loading?

**Comment by Hadi14** [comment]
when runing it got this :
-OrientDB database not found, create fresh db
-Could not initialize OrientDB connection pool for Loader: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database ....
-exception.ODatabaseException: Cannot create database
-Location passed in WAL does not exist, or IO error was happened. DB can not work in durable mode in such case.
<code><pre>
Loading workload...
Starting test.
OrientDB loading database url = plocal:/temp/databases/ycsb
2015-12-18 05:29:23:869 0 sec: 0 operations; est completion in 0 seconds 
OrientDB database not found, create fresh db
Could not initialize OrientDB connection pool for Loader: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.create(ODatabaseRecordAbstract.java:384)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.create(ODatabaseWrapperAbstract.java:55)
	at com.orientechnologies.orient.core.db.ODatabaseRecordWrapperAbstract.create(ODatabaseRecordWrapperAbstract.java:64)
	at com.yahoo.ycsb.db.OrientDBClient.init(OrientDBClient.java:97)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:63)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.create(ODatabaseRaw.java:139)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.create(ODatabaseWrapperAbstract.java:55)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.create(ODatabaseRecordAbstract.java:338)
	... 5 more
Caused by: java.lang.IllegalStateException: Location passed in WAL does not exist, or IO error was happened. DB can not work in durable mode in such case.
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWriteAheadLog.<init>(OWriteAheadLog.java:614)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWriteAheadLog.<init>(OWriteAheadLog.java:590)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.initWal(OLocalPaginatedStorage.java:1538)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:295)
	at com.orientechnologies.orient.core.db.raw.ODatabaseRaw.create(ODatabaseRaw.java:135)
	... 7 more
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/temp/databases/ycsb' is closed
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.checkOpeness(ODatabaseRecordAbstract.java:1552)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.getMetadata(ODatabaseRecordAbstract.java:839)
	at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.getMetadata(ODatabaseRecordAbstract.java:91)
	at com.orientechnologies.orient.core.record.ORecordSchemaAwareAbstract.setClassName(ORecordSchemaAwareAbstract.java:395)
	at com.orientechnologies.orient.core.record.impl.ODocument.<init>(ODocument.java:194)
	at com.yahoo.ycsb.db.OrientDBClient.insert(OrientDBClient.java:136)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:158)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:549)
	at com.yahoo.ycsb.ClientThread.run(Client.java:346)
2015-12-18 05:29:26:000 3 sec: 0 operations; est completion in 106751991167300 days 15 hours [CLEANUP: Count=1, Max=251, Min=251, Avg=251, 90=251, 99=251, 99.9=251, 99.99=251] [INSERT: Count=1, Max=7223, Min=7220, Avg=7222, 90=7223, 99=7223, 99.9=7223, 99.99=7223] 
[OVERALL], RunTime(ms), 3528.0
[OVERALL], Throughput(ops/sec), 0.0
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 251.0
[CLEANUP], MinLatency(us), 251.0
[CLEANUP], MaxLatency(us), 251.0
[CLEANUP], 95thPercentileLatency(us), 251.0
[CLEANUP], 99thPercentileLatency(us), 251.0
[INSERT], Operations, 1.0
[INSERT], AverageLatency(us), 7222.0
[INSERT], MinLatency(us), 7220.0
[INSERT], MaxLatency(us), 7223.0
[INSERT], 95thPercentileLatency(us), 7223.0
[INSERT], 99thPercentileLatency(us), 7223.0
[INSERT], Return=ERROR, 1
Dec 18, 2015 5:29:26 AM com.orientechnologies.common.log.OLogManager log
INFO: - storage: ycsb...
Dec 18, 2015 5:29:26 AM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB Engine shutdown complete</pre></code>

**Comment by kruthar** [comment]
As @busbey said, the ```orientdb``` client is not among the tested clients list. I tried playing around with it for the first time last night and found that it is far from bulletproof and may need some work.

I apologize I can't help you at the moment, but will get back to you when I know a little more about this binding.

**Comment by Hadi14** [comment]
@kruthar thankyou very much for these replys 
i'm hopeful i found a solution for this, but , so  why i got this result? (like RunTime(ms), 3528.0 ,...)

**Comment by kruthar** [comment]
Why did you get that result? The results print out shows that it tried one insert action, and failed. This likely stopped the whole process. The cause seems to be some issue creating the database. Since you used the default url it is likely because of permissions on that directory or something similar.

At this point I don't want to go too deeply on it with you, I plan on updating this binding and the README so usage should be easier and more straightforward.

>RunTime(ms), 3528.0

Means it took 3.5 seconds to try one operation and fail.

**Comment by Hadi14** [comment]
ok, i wil install an run orientDB and try again.
orientDB is a Multi Model Database (Document , key-value and graph base) , there is a ambiguity , have we option to select a Model? i dont think it is , so how to use only one model ? 
for example for crate table we should create CLASS ?

**Comment by Hadi14** [comment]
i install OrientDB and runt it and i do Load wokload but i got above message!!

**Comment by Hadi14** [comment]
can i use this on YCSB?
http://orientdb.com/docs/2.1/Performance-Tuning.html

**Comment by busbey** [comment]
Hi @Hadi14! Did you get a test against OrientDB working?

@kruthar recently updated the README for the OrientDB binding to cover basic set up and some possible client side optimization options.

**Comment by risdenk** [comment]
@Hadi14 Any update here? Can this issue be closed?

**Comment by Hadi14** [comment]
Hi @risdenk ok.
