### ISSUE TITLE
When we're not tracking any individual error latencies, say so directly

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#546]
right now when we aren't tracking any individual latencies, we give this message:

> DBWrapper: report latency for each error is false and specific error codes to track for latency are: []

instead we should say something like "report latency for all errors as a group rather than individually".

**Comment by subrata4096** [comment]
My OS details:
(TOSS) Linux 2.6.32-573.8.1.2chaos.ch5.4.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux
-----------------------------------------------------------------------------------------------------------------
I installed YCSB as follows:
    git clone https://github.com/brianfrankcooper/YCSB.git
    cd YCSB
    mvn -pl com.yahoo.ycsb:memcached-binding -am clean package
----------------------------------------------------------------------------------------
Installed Memcached as follows:
    wget http://memcached.org/files/memcached-1.4.25.tar.gz
    tar xvzf memcached-1.4.25.tar.gz
    cd memcached-1.4.25
   ./configure --prefix=$MEMCACHED_DIR
    make
    make install
-------------------------------------------
Command to run memcached:
  ${MEMCACHED_DIR}/bin/memcached -d -m 1024 -u root -l 127.0.0.1 -p 11211
-------------------------------------------
Running YCSB "load" command:
${YCSB_DIR}/bin/ycsb load memcached -s -P "${YCSB_DIR}/workloadsworkloada" -p recordcount=500000 -p operationcount=5000000 -p "memcached.hosts=127.0.0.1"
-----------------------------------------------------------------------------------------------------------
Running YCSB "run" command:
${YCSB_DIR}/bin/ycsb run memcached -s -threads 8 -P "${YCSB_DIR}/workloada" -p recordcount=500000 -p operationcount=5000000 -p "memcached.hosts=127.0.0.1"
---------------------------------------------------------------------
Full output with errors while "load":
--------------------------------------------------------------------
2015-12-20 22:05:02:000 0 sec: 0 operations; est completion in 0 seconds 
2015-12-20 22:05:02.058 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2015-12-20 22:05:02.058 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2015-12-20 22:05:02.058 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2015-12-20 22:05:02.058 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2015-12-20 22:05:02.058 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2015-12-20 22:05:02.058 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2015-12-20 22:05:02.059 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2015-12-20 22:05:02.060 INFO net.spy.memcached.MemcachedConnection:  Added {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
Error inserting, not retrying any more. number of attempts: 1Insertion Retry Limit: 0
2015-12-20 22:05:02.156 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2015-12-20 22:05:02.156 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
	at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:722)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:683)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:436)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1445)
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
	at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:722)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:683)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:436)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1445)
2015-12-20 22:05:02.157 INFO net.spy.memcached.MemcachedConnection:  Shut down memcached client
2015-12-20 22:05:02.157 INFO net.spy.memcached.MemcachedConnection:  Shut down memcached client
2015-12-20 22:05:02.158 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2015-12-20 22:05:02.158 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
	at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:722)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:683)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:436)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1445)
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
	at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:722)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:683)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:436)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1445)
2015-12-20 22:05:02.159 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2015-12-20 22:05:02.159 INFO net.spy.memcached.MemcachedConnection:  Shut down memcached client
2015-12-20 22:05:02.158 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
	at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:722)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:683)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:436)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1445)
2015-12-20 22:05:02.159 INFO net.spy.memcached.MemcachedConnection:  Shut down memcached client
2015-12-20 22:05:02.160 INFO net.spy.memcached.MemcachedConnection:  Shut down memcached client
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
	at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:722)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:683)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:436)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1445)
2015-12-20 22:05:02.160 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
2015-12-20 22:05:02.161 INFO net.spy.memcached.MemcachedConnection:  Shut down memcached client
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
	at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:722)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:683)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:436)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1445)
2015-12-20 22:05:02.161 INFO net.spy.memcached.MemcachedConnection:  Shut down memcached client
2015-12-20 22:05:02.162 INFO net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA sa=/127.0.0.1:11211, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0}
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
	at java.nio.channels.SelectionKey.isWritable(SelectionKey.java:312)
	at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:722)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:683)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:436)
	at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1445)
2015-12-20 22:05:02.162 INFO net.spy.memcached.MemcachedConnection:  Shut down memcached client
2015-12-20 22:05:02:164 0 sec: 0 operations; est completion in 106751991167300 days 15 hours [CLEANUP: Count=8, Max=4375, Min=1916, Avg=3589.62, 90=4303, 99=4375, 99.9=4375, 99.99=4375] [INSERT-FAILED: Count=8, Max=76799, Min=73472, Avg=75552, 90=76799, 99=76799, 99.9=76799, 99.99=76799] [INSERT: Count=0, Max=0, Min=9223372036854775807, Avg=?, 90=0, 99=0, 99.9=0, 99.99=0] 
[OVERALL], RunTime(ms), 166.0
[OVERALL], Throughput(ops/sec), 0.0
[CLEANUP], Operations, 8.0
[CLEANUP], AverageLatency(us), 3589.625
[CLEANUP], MinLatency(us), 1916.0
[CLEANUP], MaxLatency(us), 4375.0
[CLEANUP], 95thPercentileLatency(us), 4375.0
[CLEANUP], 99thPercentileLatency(us), 4375.0
[INSERT-FAILED], Operations, 8.0
[INSERT-FAILED], AverageLatency(us), 75552.0
[INSERT-FAILED], MinLatency(us), 73472.0
[INSERT-FAILED], MaxLatency(us), 76799.0
[INSERT-FAILED], 95thPercentileLatency(us), 76799.0
[INSERT-FAILED], 99thPercentileLatency(us), 76799.0
[INSERT], Operations, 0.0
[INSERT], AverageLatency(us), NaN
[INSERT], MinLatency(us), 9.223372036854776E18
[INSERT], MaxLatency(us), 0.0
[INSERT], 95thPercentileLatency(us), 0.0
[INSERT], 99thPercentileLatency(us), 0.0
[INSERT], Return=ERROR, 8
