### ISSUE TITLE
[orientdb] fails with multiple threads when database does not already exists

### ISSUE THREAD

**Issue by kruthar** [brianfrankcooper/YCSB#571]
I tested with:

```bin/ycsb load orientdb -P workloads/workloada -p orientdb.url=plocal:ycsb -threads 2```

my database did not already exists and I recieived this:

```
OrientDB database not found, create fresh db
OrientDB database not found, create fresh db
Could not initialize OrientDB connection pool for Loader: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'ycsb'
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot create database 'ycsb'
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:452)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:361)
	at com.yahoo.ycsb.db.OrientDBClient.init(OrientDBClient.java:98)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot create new storage 'plocal:ycsb' because it is not closed
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:263)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:113)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:383)
	... 4 more
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:ycsb' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2930)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:793)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.getMetadata(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.setClassName(ODocument.java:1958)
	at com.orientechnologies.orient.core.record.impl.ODocument.<init>(ODocument.java:184)
	at com.yahoo.ycsb.db.OrientDBClient.insert(OrientDBClient.java:140)
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:208)
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:578)
	at com.yahoo.ycsb.ClientThread.run(Client.java:346)
```

Looks like the ```init()``` on both threads are trying to create the database. Subsequent runs of the same load command are successful because the database was created.

**Comment by busbey** [comment]
Still an issue?

**Comment by kruthar** [comment]
Thanks for the bump, I assume it is. I haven't done anything to fix it yet.
