### ISSUE TITLE
Maven Build Error when compiling YCSB: "Error reading assemblies"

### ISSUE THREAD

**Issue by mj-jadhav** [brianfrankcooper/YCSB#580]
I have updated maven but I am still getting this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (default) on project dynamodb-binding: Execution default of goal org.apache.maven.plugins:maven-assembly[17/1865$
.5.5:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.5.5 or one of its dependencies could not be resolved: Could not find artifact com.yahoo.ycsb:datastore-specific-descriptor:jar:0
.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single (default) on project dynamodb-binding: Execution default of goal
org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.5.5 or one of its dependencies could not be resolved: Could not find artifact co
m.yahoo.ycsb:datastore-specific-descriptor:jar:0.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.apache.maven.plugins:maven-assembly-plugin:2.5.5:single failed: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.5.5 or one of its dependencies could not be resolved: Could not find artifact com.yahoo.ycsb:datastore-specific-descriptor:jar:0.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:82)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.apache.maven.plugins:maven-assembly-plugin:2.5.5 or one of its dependencies could not be resolved: Could not find artifact com.yahoo.ycsb:datastore-specific-descriptor:jar:0.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:215)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:353)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:321)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:175)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:78)
        ... 20 more
Caused by: org.sonatype.aether.resolution.ArtifactResolutionException: Could not find artifact com.yahoo.ycsb:datastore-specific-descriptor:jar:0.7.0-SNAPSHOT in apache.snapshots (http://repository.apache.org/snapshots)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:538)
        at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
        at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:207)
        ... 24 more
```

OS version:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.5 LTS"
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"
```

Version of Maven and JDK:
```
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.2.0-68-virtual", arch: "amd64", family: "unix"
```

**Comment by risdenk** [comment]
@mj-jadhav What was the exact maven command that you ran? Also what directory did you run it in (ie: did you run it from the top level directory or from a subdirectory like dynamodb)?

**Comment by mj-jadhav** [comment]
@risdenk I ran following command from the top level directory of YCSB:
```
mvn -X clean package -U
```

**Comment by risdenk** [comment]
I just ran the following and it worked without issue:

```
docker run --rm -it ubuntu:12.04 /bin/bash -c "apt-get update && apt-get -y install maven openjdk-7-jdk git --no-install-recommends && git clone https://github.com/brianfrankcooper/YCSB.git /opt/YCSB && cd /opt/YCSB && mvn -X clean package -U"
```

This breaks down to the following:
```
root@cf5b1e555288:/# apt-get update
...
root@cf5b1e555288:/# apt-get -y install maven openjdk-7-jdk git
...
root@cf5b1e555288:/# git clone https://github.com/brianfrankcooper/YCSB.git /opt/YCSB
...
root@cf5b1e555288:/# cd /opt/YCSB
root@cf5b1e555288:/opt/YCSB# mvn -X clean package -U
Apache Maven 3.0.4
Maven home: /usr/share/maven
Java version: 1.7.0_91, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.1.13-boot2docker", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /root/.m2/settings.xml
[DEBUG] Using local repository at /root/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /root/.m2/repository
[INFO] Scanning for projects...
[DEBUG] Extension realms for project com.yahoo.ycsb:root:pom:0.7.0-SNAPSHOT: (none)
...
[INFO] Building tar: /opt/YCSB/distribution/target/ycsb-0.7.0-SNAPSHOT.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] YCSB Root ......................................... SUCCESS [1:01.024s]
[INFO] Core YCSB ......................................... SUCCESS [52.551s]
[INFO] Per Datastore Binding descriptor .................. SUCCESS [1.506s]
[INFO] YCSB Datastore Binding Parent ..................... SUCCESS [8.626s]
[INFO] Accumulo DB Binding ............................... SUCCESS [50.477s]
[INFO] Aerospike DB Binding .............................. SUCCESS [2.759s]
[INFO] Cassandra DB Binding .............................. SUCCESS [21.029s]
[INFO] Cassandra 2.1+ DB Binding ......................... SUCCESS [40.828s]
[INFO] Couchbase Binding ................................. SUCCESS [8.717s]
[INFO] DynamoDB DB Binding ............................... SUCCESS [11.672s]
[INFO] ElasticSearch Binding ............................. SUCCESS [58.327s]
[INFO] Gemfire DB Binding ................................ SUCCESS [14.287s]
[INFO] Google Cloud Datastore Binding .................... SUCCESS [6.208s]
[INFO] HBase 0.98.x DB Binding ........................... SUCCESS [19.587s]
[INFO] HBase 0.94.x DB Binding ........................... SUCCESS [27.827s]
[INFO] HBase 1.0 DB Binding .............................. SUCCESS [56.630s]
[INFO] Hypertable DB Binding ............................. SUCCESS [3.494s]
[INFO] Infinispan DB Binding ............................. SUCCESS [9.878s]
[INFO] JDBC DB Binding ................................... SUCCESS [7.194s]
[INFO] Kudu DB Binding ................................... SUCCESS [8.126s]
[INFO] memcached binding ................................. SUCCESS [3.188s]
[INFO] MongoDB Binding ................................... SUCCESS [6.324s]
[INFO] OrientDB Binding .................................. SUCCESS [7.772s]
[INFO] Redis DB Binding .................................. SUCCESS [1.604s]
[INFO] S3 Storage Binding ................................ SUCCESS [6.636s]
[INFO] Tarantool DB Binding .............................. SUCCESS [1.464s]
[INFO] YCSB Release Distribution Builder ................. SUCCESS [12.040s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8:30.239s
[INFO] Finished at: Mon Jan 11 22:17:52 UTC 2016
[INFO] Final Memory: 94M/369M
[INFO] ------------------------------------------------------------------------
```

@mj-jadhav Did you change any of the YCSB code before trying to package? Did you add/change any Maven repositories?

**Comment by kruthar** [comment]
Hi @mj-jadhav - you removed some of the necessary modules. It looks like you only care about dynamodb and mongodb correct? You can see what dependency modules you need with the ```-am``` flag for Maven. Please try putting your pom.xml back to the state it was, then run this:

```
mvn clean package -pl dynamodb,mongodb -am
```

At the end should be a list of all the modules you need to keep to build mongodb and dynamodb bindings, you can remove the rest.

**Comment by mj-jadhav** [comment]
Thanks @risdenk @kruthar for the solution. It worked on fresh system. I followed this http://highscalability.com/blog/2013/4/3/5-steps-to-benchmarking-managed-nosql-dynamodb-vs-cassandra.html for setting up YCSB but I think it's old and uses maven2 and after looking at the solutions I updated to maven3, I think this is where I messed up something. Anyways thanks a ton! :)
