### ISSUE TITLE
Accumulo tests fail on windows

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#617]
Fails during initialization. Very little information given. Attaching maven output. The referenced junit temp directory does not exist after failure.
[ycsb_accumulo_mvn_on_windows.log.txt](https://github.com/brianfrankcooper/YCSB/files/120566/ycsb_accumulo_mvn_on_windows.log.txt)

**Comment by risdenk** [comment]
@busbey - Is there a known Accumulo JIRA for this problem?

**Comment by busbey** [comment]
nope, we don't know what the root issue is. (unless @joshelser has some idea)

**Comment by joshelser** [comment]
Ack, sorry, I never commented:

Per the error message: `java.lang.RuntimeException: Initialize process returned -1. Check the logs in C:\Users\Clabey\AppData\Local\Temp\junit4393306788991733647\accumulo\logs`, if we can get the contents of that directory, we can figure out what the real issue is and get a fix in Accumulo (if necessary, ofc).

**Comment by busbey** [comment]
hurm. I'll have to mess with how we do set up, I think. IIRC, that directory did not exist after the test was done. I presume JUnit deleted it.

**Comment by joshelser** [comment]
> I presume JUnit deleted it.

Been there, fell prey to that one before. I know some of the JUnit-provided temp-directory-creating utilities often `deleteOnExit()` them which makes it a bit less useful for deferred analysis. Sorry, I also don't have a windows box/vm set up to try to run this on my own.

**Comment by risdenk** [comment]
Reopening since this isn't resolved really. Temporary workaround with #628 by disabling tests on Windows.

**Comment by risdenk** [comment]
@busbey @joshelser This looks like https://issues.apache.org/jira/browse/ACCUMULO-3293. I was able to run the Accumulo unit tests on windows and capture the error logs:

```
2016/02/23 10:31:56 WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016/02/23 10:31:57 ERROR org.apache.hadoop.util.Shell  - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable C:\Users\Kevin\AppData\Local\Temp\junit8384078410817105720\accumulo\bin\winutils.exe in the Hadoop binaries.
	at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:278)
	at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:300)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:293)
	at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:639)
	at org.apache.hadoop.fs.FilterFileSystem.setPermission(FilterFileSystem.java:468)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:456)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:424)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:905)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:886)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:848)
	at org.apache.hadoop.fs.FileSystem.createNewFile(FileSystem.java:1148)
	at org.apache.accumulo.server.fs.VolumeManagerImpl.createNewFile(VolumeManagerImpl.java:164)
	at org.apache.accumulo.server.init.Initialize.initDirs(Initialize.java:292)
	at org.apache.accumulo.server.init.Initialize.initFileSystem(Initialize.java:303)
	at org.apache.accumulo.server.init.Initialize.initialize(Initialize.java:238)
	at org.apache.accumulo.server.init.Initialize.doInit(Initialize.java:220)
	at org.apache.accumulo.server.init.Initialize.main(Initialize.java:630)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.accumulo.start.Main$1.run(Main.java:141)
	at java.lang.Thread.run(Thread.java:745)
2016/02/23 10:31:57 FATAL org.apache.accumulo.server.init.Initialize  - Failed to initialize filesystem
java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:404)
	at org.apache.hadoop.util.Shell.run(Shell.java:379)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:589)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:678)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:661)
	at org.apache.hadoop.fs.RawLocalFileSystem.setPermission(RawLocalFileSystem.java:639)
	at org.apache.hadoop.fs.FilterFileSystem.setPermission(FilterFileSystem.java:468)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:456)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:424)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:905)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:886)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:848)
	at org.apache.hadoop.fs.FileSystem.createNewFile(FileSystem.java:1148)
	at org.apache.accumulo.server.fs.VolumeManagerImpl.createNewFile(VolumeManagerImpl.java:164)
	at org.apache.accumulo.server.init.Initialize.initDirs(Initialize.java:292)
	at org.apache.accumulo.server.init.Initialize.initFileSystem(Initialize.java:303)
	at org.apache.accumulo.server.init.Initialize.initialize(Initialize.java:238)
	at org.apache.accumulo.server.init.Initialize.doInit(Initialize.java:220)
	at org.apache.accumulo.server.init.Initialize.main(Initialize.java:630)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.accumulo.start.Main$1.run(Main.java:141)
	at java.lang.Thread.run(Thread.java:745)
2016/02/23 10:31:57 INFO  org.apache.hadoop.conf.Configuration.deprecation  - fs.default.name is deprecated. Instead, use fs.defaultFS
2016/02/23 10:31:57 FATAL org.apache.accumulo.server.init.Initialize  - Default filesystem value ('fs.defaultFS' or 'fs.default.name') was found in the Hadoop configuration
2016/02/23 10:31:57 FATAL org.apache.accumulo.server.init.Initialize  - Please ensure that the Hadoop core-site.xml is on the classpath using 'general.classpaths' in accumulo-site.xml
```

**Comment by busbey** [comment]
oh perfect! we already disable HBase tests on windows for the same reason. So I think we're fine to either

1) resolve this now, since we don't want to bring the hadoop win utilities stuff with us

2) change this and the hbase JUnit Assume checks to look for the win utilities binary rather than "not on windows"

**Comment by risdenk** [comment]
I'm all for resolving this since skipping the tests on Windows is easier. I think it would be hard to find win utils since it could be in a bunch of different places. It would be duplicating the check that Accumulo/HBase does.

**Comment by busbey** [comment]
well, one way to do it indirectly is to attempt to do the minicluster init in set up, then have a JUnit Assume check on wether the cluster came up.

**Comment by busbey** [comment]
My concerns with this approach: someone would have to get hadoop on windows working, which I've never succeeded at.

**Comment by risdenk** [comment]
I've fought w/ the winutils before for HBase and getting tests to work. It wasn't that much fun. I think we just skip running the HBase/Accumulo tests on Windows for now.

**Comment by joshelser** [comment]
> I think we just skip running the HBase/Accumulo tests on Windows for now. 

:+1: We haven't done the due-diligence in Accumulo itself to vet it running on Windows, so I'd feel bad trying to make this one thing work just to have it fail one or two steps down the road.

**Comment by busbey** [comment]
given consensus, closing. if anyone wants to verify things working on windows in a new PR that'd be swell.
