### ISSUE TITLE
Error when running against HBase 1.1.2

### ISSUE THREAD

**Issue by hu174** [brianfrankcooper/YCSB#622]
HBase version is 1.1.2, Hadoop version is 2.7.1.
When running ycsb getting the following exception:

```
com.yahoo.ycsb.DBException: java.io.IOException: java.lang.reflect.InvocationTargetException
	at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:140)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: java.io.IOException: java.lang.reflect.InvocationTargetException
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:240)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
	at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:137)
	... 2 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
	... 5 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.protobuf.ProtobufUtil
	at org.apache.hadoop.hbase.ClusterId.parseFrom(ClusterId.java:64)
	at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:75)
	at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:105)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:879)
	at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:635)
	... 10 more
```

My classpath is 

```
-cp conf \
    :/Users/yingkai/YCSB/hbase10/conf \
    :/Users/yingkai/YCSB/hbase10/target/hbase10-binding-0.7.0-SNAPSHOT.jar \
    :/Users/yingkai/.m2/repository/org/apache/hbase/hbase-protocol/1.1.2/hbase-protocol-1.1.2.jar \
    :/Users/yingkai/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar \
    :/Users/yingkai/.m2/repository/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.jar \
    :/Users/yingkai/.m2/repository/org/apache/hadoop/hadoop-yarn-api/2.7.1/hadoop-yarn-api-2.7.1.jar \
    :/Users/yingkai/.m2/repository/org/apache/hadoop/hadoop-annotations/2.7.1/hadoop-annotations-2.7.1.jar \
    :/Users/yingkai/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar \
    :/Users/yingkai/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar \
    :/Users/yingkai/.m2/repository/org/codehaus/jackson/jackson-xc/1.8.3/jackson-xc-1.8.3.jar \
    :/Users/yingkai/.m2/repository/org/jruby/joni/joni/2.1.2/joni-2.1.2.jar \
    :/Users/yingkai/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar \
    :/Users/yingkai/.m2/repository/org/tukaani/xz/1.0/xz-1.0.jar \
    :/Users/yingkai/.m2/repository/org/apache/httpcomponents/httpclient/4.1.2/httpclient-4.1.2.jar \
    :/Users/yingkai/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar \
    :/Users/yingkai/.m2/repository/org/jruby/jcodings/jcodings/1.0.8/jcodings-1.0.8.jar \
    :/Users/yingkai/.m2/repository/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar \
    :/Users/yingkai/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar \
    :/Users/yingkai/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar \
    :/Users/yingkai/.m2/repository/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar \
    :/Users/yingkai/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar \
    :/Users/yingkai/.m2/repository/org/apache/hadoop/hadoop-common/2.7.1/hadoop-common-2.7.1.jar \
    :/Users/yingkai/.m2/repository/com/google/guava/guava/11.0.2/guava-11.0.2.jar \
    :/Users/yingkai/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar \
    :/Users/yingkai/.m2/repository/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.jar \
    :/Users/yingkai/.m2/repository/com/jcraft/jsch/0.1.42/jsch-0.1.42.jar \
    :/Users/yingkai/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar \
    :/Users/yingkai/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar \
    :/Users/yingkai/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar \
    :/Users/yingkai/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar \
    :/Users/yingkai/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar \
    :/Users/yingkai/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar \
    :/Users/yingkai/.m2/repository/xmlenc/xmlenc/0.52/xmlenc-0.52.jar \
    :/Users/yingkai/.m2/repository/com/google/inject/extensions/guice-servlet/3.0/guice-servlet-3.0.jar \
    :/Users/yingkai/.m2/repository/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar \
    :/Users/yingkai/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar \
    :/Users/yingkai/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-core/2.7.1/hadoop-mapreduce-client-core-2.7.1.jar \
    :/Users/yingkai/.m2/repository/org/apache/curator/curator-recipes/2.7.1/curator-recipes-2.7.1.jar \
    :/Users/yingkai/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar \
    :/Users/yingkai/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar \
    :/Users/yingkai/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar \
    :/Users/yingkai/.m2/repository/org/apache/hbase/hbase-common/1.1.2/hbase-common-1.1.2.jar \
    :/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/jre/../lib/tools.jar \
    :/Users/yingkai/.m2/repository/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar \
    :/Users/yingkai/.m2/repository/org/apache/avro/avro/1.7.4/avro-1.7.4.jar \
    :/Users/yingkai/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar \
    :/Users/yingkai/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar \
    :/Users/yingkai/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar \
    :/Users/yingkai/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.8.3/jackson-jaxrs-1.8.3.jar \
    :/Users/yingkai/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar \
    :/Users/yingkai/.m2/repository/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar \
    :/Users/yingkai/.m2/repository/io/netty/netty-all/4.0.23.Final/netty-all-4.0.23.Final.jar \
    :/Users/yingkai/.m2/repository/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar \
    :/Users/yingkai/.m2/repository/commons-codec/commons-codec/1.4/commons-codec-1.4.jar \
    :/Users/yingkai/.m2/repository/org/apache/hbase/hbase-client/1.1.2/hbase-client-1.1.2.jar \
    :/Users/yingkai/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar \
    :/Users/yingkai/.m2/repository/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.jar \
    :/Users/yingkai/.m2/repository/org/apache/hadoop/hadoop-auth/2.7.1/hadoop-auth-2.7.1.jar \
    :/Users/yingkai/.m2/repository/org/apache/curator/curator-framework/2.7.1/curator-framework-2.7.1.jar \
    :/Users/yingkai/.m2/repository/org/apache/commons/commons-math3/3.1.1/commons-math3-3.1.1.jar \
    :/Users/yingkai/.m2/repository/org/apache/hadoop/hadoop-yarn-common/2.7.1/hadoop-yarn-common-2.7.1.jar \
    :/Users/yingkai/.m2/repository/org/apache/curator/curator-client/2.7.1/curator-client-2.7.1.jar \
    :/Users/yingkai/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar \
    :/Users/yingkai/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar \
    :/Users/yingkai/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar \
    :/Users/yingkai/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar \
    :/Users/yingkai/.m2/repository/org/apache/hbase/hbase-annotations/1.1.2/hbase-annotations-1.1.2.jar \
    :/Users/yingkai/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.jar \
    :/Users/yingkai/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar \
    :/Users/yingkai/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar \
    :/Users/yingkai/.m2/repository/net/java/dev/jets3t/jets3t/0.9.0/jets3t-0.9.0.jar \
    :/Users/yingkai/YCSB/core/target/core-0.7.0-SNAPSHOT.jar \
    :/Users/yingkai/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar \
    :/Users/yingkai/.m2/repository/org/apache/httpcomponents/httpcore/4.1.2/httpcore-4.1.2.jar \
    :/Users/yingkai/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar \
    :/Users/yingkai/.m2/repository/com/github/stephenc/findbugs/findbugs-annotations/1.3.9-1/findbugs-annotations-1.3.9-1.jar \
    :/Users/yingkai/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.jar \
    :/Users/yingkai/.m2/repository/asm/asm/3.1/asm-3.1.jar \
    :/Users/yingkai/.m2/repository/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar \
    :/Users/yingkai/.m2/repository/com/jamesmurty/utils/java-xmlbuilder/0.4/java-xmlbuilder-0.4.jar \
    :/Users/yingkai/.m2/repository/org/apache/htrace/htrace-core/3.1.0-incubating/htrace-core-3.1.0-incubating.jar \
    :/Users/yingkai/.m2/repository/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.jar

```

Would you please advice? Thanks.

**Comment by busbey** [comment]
What version of YCSB are you using?

What's the command line invocation?

**Comment by hu174** [comment]
I pulled source from master branch, changed hbase10.version of root/pom.xml from 1.0.2 to 1.1.2, then build the project. (1.0.2 has same exception)
command: bin/ycsb load hbase10 -P workloads/workloada -cp conf -p table=usertable -p columnfamily=family

**Comment by busbey** [comment]
could you please try running from the hbase-specific binary package from the [0.6.0 release](https://github.com/brianfrankcooper/YCSB/releases/tag/0.6.0)?

https://github.com/brianfrankcooper/YCSB/releases/download/0.6.0/ycsb-hbase10-binding-0.6.0.tar.gz

**Comment by hu174** [comment]
The binary package works fine with HBase 1.1.x, thank you!
