### ISSUE TITLE
How to connect to remote HBASE via YCSB for benchmarking

### ISSUE THREAD

**Issue by duck-tape** [brianfrankcooper/YCSB#634]
I am trying to benchmark HBASE via YCSB using 2 servers, one running YCSB and the other running HBASE.

Is it possible to run YCSB on one machine and connect to a remote HBASE instance?
I did not find any config parameter for host, port, etc. Any pointers on how I can accomplish this would be greatly appreciated.

-AA

**Comment by cmccoy** [comment]
This is definitely possilbe. You need to have a  `hbase-site.xml` file on your CLASSPATH pointing to your HBase server, with the `hbase.zookeeper.quorum` property set.

See:
https://hbase.apache.org/book.html#fully_dist

**Comment by raunaqmathur** [comment]
@cmccoy: hi, can u please explain the command that should be used for running it.
I tried:
/usr/bin/java -Xmx2048m -cp /home/hbase/ycsb-0.1.4/core/lib/core-0.1.4.jar:/home/hbase/ycsb-0.1.4/hbase-binding/lib212/hbase-binding-0.1.4.jar:$MYCLASSPATH  com.yahoo.ycsb.Client -load -db com.yahoo.ycsb.db.HBaseClient -P /home/hbase/ycsb-0.1.4/workloads/workloada -p columnfamily=family -p recordcount=10 -threads 1 -s > load_a.out


where $MYCLASSPATH contains the hbase-site.xml path on current remote machine

**Comment by cmccoy** [comment]
First, could you try a more recent [release](https://github.com/brianfrankcooper/YCSB/releases) of YCSB? The latest is v0.7.0.

If you have an hbase-site.xml is in `$MYCLASSPATH`, try something like:

```
bin/ycsb  load hbase098 -cp $MYCLASSPATH -P workloads/workloada -p columnfamily=family -p recordcount=10 -threads 1 -s
```

**Comment by raunaqmathur** [comment]
I ran:
/usr/bin/java -Xmx2048m -cp /home/hbase/YCSB-master0.7.0/YCSB-master/core/target/core-0.8.0-SNAPSHOT.jar:/home/hbase/YCSB-master0.7.0/YCSB-master/hbase10/target/hbase10-binding-0.8.0-SNAPSHOT.jar:$MYCLASSPATH:$CLASSPATH  com.yahoo.ycsb.Client -load -db com.yahoo.ycsb.db.HBaseClient -P /home/hbase/YCSB-master0.7.0/YCSB-master/workloads/workloada -p columnfamily=family -p recordcount=10 -threads 1 -s > load_a.out

My $CLASSPATH contains the path to hbase-site.xml
It throws below error:
Loading workload...
Starting test.
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.HBaseClient
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
        at com.yahoo.ycsb.Client.main(Client.java:868)
Exception in thread "Thread-1" java.lang.NullPointerException
        at com.yahoo.ycsb.ClientThread.run(Client.java:289)
2016-03-02 15:15:34:277 0 sec: 0 operations; est completion in 0 seconds
2016-03-02 15:15:34:278 0 sec: 0 operations; est completion in 106751991167300 days 15 hours

**Comment by cmccoy** [comment]
It looks like you have both v0.7.0 and the latest snapshot version in your directory?
Could you try one of the pre-built versions? You shouldn't need to compile anything.

Have you tried using the included Python runner (the script in `bin/ycsb`) instead of constructing your own command?

**Comment by raunaqmathur** [comment]
the script (bin/ycsb) throws following error:
^[[C^[[Dcom.yahoo.ycsb.DBException: org.apache.hadoop.hbase.MasterNotRunningException: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
        at com.yahoo.ycsb.db.HBaseClient.init(HBaseClient.java:146)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
        at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1737)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1763)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1970)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getHTableDescriptor(HConnectionManager.java:2783)
        at org.apache.hadoop.hbase.client.HTable.getTableDescriptor(HTable.java:593)
        at com.yahoo.ycsb.db.HBaseClient.init(HBaseClient.java:142)
        ... 2 more
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:939)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:601)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1663)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1709)
        ... 7 more
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:221)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:480)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:928)
        ... 10 more
com.yahoo.ycsb.DBException: org.apache.hadoop.hbase.MasterNotRunningException: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
        at com.yahoo.ycsb.db.HBaseClient.init(HBaseClient.java:146)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
        at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1737)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$MasterServiceStubMaker.makeStub(HConnectionManager.java:1763)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getKeepAliveMasterService(HConnectionManager.java:1970)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.getHTableDescriptor(HConnectionManager.java:2783)
        at org.apache.hadoop.hbase.client.HTable.getTableDescriptor(HTable.java:593)
        at com.yahoo.ycsb.db.HBaseClient.init(HBaseClient.java:142)
        ... 2 more
Caused by: org.apache.hadoop.hbase.MasterNotRunningException: Can't get connection to ZooKeeper: KeeperErrorCode = ConnectionLoss for /hbase
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:939)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.access$600(HConnectionManager.java:601)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStubNoRetries(HConnectionManager.java:1663)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation$StubMaker.makeStub(HConnectionManager.java:1709)
        ... 7 more
Caused by: org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /hbase
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
        at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
        at org.apache.zookeeper.ZooKeeper.exists(ZooKeeper.java:1045)
        at org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper.exists(RecoverableZooKeeper.java:221)
        at org.apache.hadoop.hbase.zookeeper.ZKUtil.checkExists(ZKUtil.java:480)
        at org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation.checkIfBaseNodeAvailable(HConnectionManager.java:928)
        ... 10 more
[OVERALL], RunTime(ms), 1132827.0
[OVERALL], Throughput(ops/sec), 0.0

**Comment by cmccoy** [comment]
OK, so YCSB isn't able to communicate with your HBase cluster
Can you otherwise access your HBase cluster from the same client machine? (does an HBase shell work)? If you can't, you might check in with the HBase docs / mailing lists for assistance getting a distributed cluster running.

**Comment by raunaqmathur** [comment]
only user "abc" has access to hbase cluster , how to specify in ycsb which user to use for accessing HBASE cluster

**Comment by risdenk** [comment]
Is this a Kerberized cluster or are you using ACLs against the username?

**Comment by raunaqmathur** [comment]
it is kerberized

**Comment by risdenk** [comment]
You either need to:
1. kinit as the user before running YCSB
2. Add the principal and keytab as described here https://github.com/brianfrankcooper/YCSB/tree/master/hbase098

**Comment by raunaqmathur** [comment]
I've added the keytab and principal information, it says "Keytab file is not readable or not found"
com.yahoo.ycsb.DBException: java.io.IOException: Login failure for test@example.com from keytab /etc/security/keytabs/hbase.headless.keytab

**Comment by raunaqmathur** [comment]
guess it is searching for keypad file on local machine, how to specify hbase master (for kerberos authentication) host in ycsb command?

**Comment by risdenk** [comment]
A keytab file is basically like an encrypted password file. It must be local to where YCSB is running if you are using the principal and keytab properties. The other option I think is the kinit as the user before running YCSB.

**Comment by risdenk** [comment]
@raunaqmathur Any update here? Were you able to resolve your issue?

**Comment by busbey** [comment]
closed as stale. if you're still having this issue please reopen.
