### ISSUE TITLE
Orientdb error

### ISSUE THREAD

**Issue by amirjuve** [brianfrankcooper/YCSB#660]
Command line: -db com.yahoo.ycsb.db.OrientDBClient -s -P workloads/workloada -load
Loading workload...
Starting test.
2016-03-19 22:52:29:308 0 sec: 0 operations; est completion in 0 seconds 
com.yahoo.ycsb.DBException: Required property "orientdb.url" missing for OrientDBClient
	at com.yahoo.ycsb.db.OrientDBClient.initDB(OrientDBClient.java:105)
	at com.yahoo.ycsb.db.OrientDBClient.init(OrientDBClient.java:169)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
com.yahoo.ycsb.DBException: Required property "orientdb.url" missing for OrientDBClient
	at com.yahoo.ycsb.db.OrientDBClient.initDB(OrientDBClient.java:105)
	at com.yahoo.ycsb.db.OrientDBClient.init(OrientDBClient.java:169)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
2016-03-19 22:52:29:312 0 sec: 0 operations; est completion in 106751991167300 days 15 hours 
[OVERALL], RunTime(ms), 4.0
[OVERALL], Throughput(ops/sec), 0.0

**Comment by busbey** [comment]
The relevant error text is thus but here:

```
com.yahoo.ycsb.DBException: Required property "orientdb.url" missing for OrientDBClient
```

Please follow the README associated with the OrientDB binding to properly let YCSB know how to talk to your deployment.

**Comment by amirjuve** [comment]
@busbey  i changed orientdb.url variable in OrientDBClient.java : 

**  private static final String URL_PROPERTY = "remote:localhost/ycsb";**

still got the same error.

**Comment by busbey** [comment]
You should not be altering the source code. The different configuration parameters in the r
README should be specified as needed on the command line.

**Comment by amirjuve** [comment]
would you to past here the command lines @busbey

**Comment by busbey** [comment]
@kruthar might have a better idea of what's missing in a typical OrientDB set up.

when you say it works "normally" can you describe what you're doing to verify thing are working?

**Comment by amirjuve** [comment]
localhost:2480 is running normally, i can deal with Orientdb databeses from localhost or console.sh

**Comment by amirjuve** [comment]
i added orentdb.url="path/to/db" and it works
