### ISSUE TITLE
com.yahoo.ycsb.ClientThread.run(Client.java:289) error with memcached

### ISSUE THREAD

**Issue by cimballihw** [brianfrankcooper/YCSB#667]
Hello,

I am currently installing YCSB to benchmark memcached DBMS. 
I followed the instructions in the README of YCSB, but so far I can not execute the load instructions.
I have installed memcached, JDK and Maven both on a native AMD64 server and on QEMU.
Because python is not working properly, I bypass the ycsb script, and execute the java command as follows:

 ```
java -cp core/target/core-0.8.0-SNAPSHOT.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.MemcachedClient -P workloads/workloada -load -s -p memcached.hosts=
 "127.0.0.1"
```

I get the same errors for both systems:
```
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.MemcachedClient -P workloads/workloada -load -s -p memcached.hosts=127.0.0.1
Loading workload...
Starting test.
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.MemcachedClient
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:36)
	at com.yahoo.ycsb.Client.main(Client.java:868)
Exception in thread "Thread-1" java.lang.NullPointerException
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
2016-03-24 01:04:00:950 0 sec: 0 operations; est completion in 0 seconds 
2016-03-24 01:04:00:950 0 sec: 0 operations; est completion in 106751991167300 days 15 hours 
[OVERALL], RunTime(ms), 0.0
[OVERALL], Throughput(ops/sec), NaN
```

I would be grateful if anyone could give me a hint where to look for this bug, and potentially help me solve it. I have looked at the previous threads, some reporting the same NullPointerException error, but all for different DBMS like Cassandra or else.
Regards,
Florian

**Comment by risdenk** [comment]
> Because python is not working properly, I bypass the ycsb script

This is causing the problem you are having. The python script sets up the proper classpath.

> `java -cp core/target/core-0.8.0-SNAPSHOT.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.MemcachedClient -P workloads/workloada -load -s -p memcached.hosts="127.0.0.1"`

This command doesn't have the full classpath required. It only has the core jar and not the other jars like the one that has the MemcachedClient.

**Comment by cimballihw** [comment]
Hi risdenk,
Thanks a lot for your feeback. I have indeed included the missing classpaths this morning, and YCSB can load and run all workloads.

**Comment by risdenk** [comment]
great. I'm going to close this issue. Please open a new issue if you have other questions.
