### ISSUE TITLE
Problem running a base test

### ISSUE THREAD

**Issue by petroniocg** [brianfrankcooper/YCSB#680]
Hi everybody,

I'm new with YCSB. I'm trying to run a simply command and I got an error. I searched in the issues for something similar, but just saw the same problem for Windows []((https://github.com/brianfrankcooper/YCSB/issues/655) ) and I'm using Linux.
Does anyone can help me?

OS: Ubuntu 14.04 / Cassandra 3.3 / YCSB 0.7.0

The error:
client@ubuntu:~/ycsb-0.7.0$ **./bin/ycsb shell basic**
/usr/lib/jvm/java-8-oracle/jre/bin/java/bin/java -cp /home/client/ycsb-0.7.0/basic-binding/conf:/home/client/ycsb-0.7.0/conf:/home/client/ycsb-0.7.0/lib/HdrHistogram-2.1.4.jar:/home/client/ycsb-0.7.0/lib/core-0.7.0.jar:/home/client/ycsb-0.7.0/lib/jackson-mapper-asl-1.9.4.jar:/home/client/ycsb-0.7.0/lib/jackson-core-asl-1.9.4.jar com.yahoo.ycsb.CommandLine -db com.yahoo.ycsb.BasicDB
Traceback (most recent call last):
  File "./bin/ycsb", line 259, in <module>
    sys.exit(main())
  File "./bin/ycsb", line 250, in main
    return subprocess.call(ycsb_command)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory
client@ubuntu:~/ycsb-0.7.0$ 

The same error occurs when connecting with the base Cassandra:

client@ubuntu:~/ycsb-0.7.0$ **./bin/ycsb load basic -p hosts="192.168.80.129" -P workloads/workloada**
/usr/lib/jvm/java-8-oracle/jre/bin/java/bin/java -cp /home/client/ycsb-0.7.0/basic-binding/conf:/home/client/ycsb-0.7.0/conf:/home/client/ycsb-0.7.0/lib/HdrHistogram-2.1.4.jar:/home/client/ycsb-0.7.0/lib/core-0.7.0.jar:/home/client/ycsb-0.7.0/lib/jackson-mapper-asl-1.9.4.jar:/home/client/ycsb-0.7.0/lib/jackson-core-asl-1.9.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.BasicDB -p hosts=192.168.80.129 -P workloads/workloada -load
Traceback (most recent call last):
  File "./bin/ycsb", line 259, in <module>
    sys.exit(main())
  File "./bin/ycsb", line 250, in main
    return subprocess.call(ycsb_command)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 20] Not a directory
client@ubuntu:~/ycsb-0.7.0$

**Comment by petroniocg** [comment]
Guys, I resolved the last issue. But, now, I'm with other problem.

I'm trying to connect to my Cassandra DB and it does not work. My DB is in another machine (machine A), different from the machine with YCSB (machine B). In the DB, the command: /bin/cqlsh <IP> it works, and inform the port 9042. One telnet in that port from B works. 

The error is:
client@ubuntu:~/ycsb-0.7.0$ **./bin/ycsb load cassandra2-cql -p hosts="192.168.80.129" -P workloads/workloada**
...
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=192.168.80.129 -P workloads/workloada -load
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.80.129:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:193)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.80.129:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:227)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1409)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:382)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:180)
	... 2 more
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.80.129:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:193)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /192.168.80.129:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:227)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1409)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:382)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:180)
	... 2 more
[OVERALL], RunTime(ms), 575.0
[OVERALL], Throughput(ops/sec), 0.0

==========================================
About the beginning of the error, I followed the instruction:
If you see the following errors
    SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
    SLF4J: Defaulting to no-operation (NOP) logger implementation
    SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

    You are missing a few jars. Download the latest slf and copy slf4j-simple-1.7.7.jar and slf4j-api-1.7.7.jar to the ycsb dir

The version is with the number 1.7.21, I copied to that dir, but the error is the same.

**Comment by risdenk** [comment]
> Guys, I resolved the last issue. But, now, I'm with other problem.

In the future, please keep it to one problem per issue. Can you specify what was the solution?

> Cassandra 3.3 

Cassandra 3.3 isn't supported in release 0.7.0. There is some support on master. Try compiling from source and see if you can use Cassandra 3.3. YCSB 0.8.0 isn't out yet should also contain support for Cassandra 3.3.

> About the beginning of the error, I followed the instruction:

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

This is just a warning and isn't important.

**Comment by risdenk** [comment]
The relevant issue for Cassandra 3+ support is #612

**Comment by petroniocg** [comment]
Hi risdenk. Thanks for your attencion.

I'm not sure about what was causing the problem in the first issue. I reinstalled the OS, java and ycsb. That solved the problem.

Could you please tell me wich version of cassandra can I run the ycsb test cassandra-10?
Against what version of the cassandra db should I run ycsb 0.7.0 cassandra-10 test to have no errors?

Thank you again.

**Comment by risdenk** [comment]
The release notes for a given release note which databases were tested and which ones were not. For YCSB 0.7.0 the release notes are here: https://github.com/brianfrankcooper/YCSB/releases/tag/0.7.0

**Comment by petroniocg** [comment]
Thank you so much for this help.
For me, this issue can be closed.
