### ISSUE TITLE
[hbase10] Still too many threads 

### ISSUE THREAD

**Issue by saintstack** [brianfrankcooper/YCSB#691]
#662  and #651 addressed one of causes of too-many-threads by checking if the static Connection instance were null or not. They helped.

For case where many threads starting up at the same time, the concurrency 'protection' around the Connection check is broke so we'll spin up many more connections than were asked for.

Here is total threads when I specify a thread count of 200:

stack@ve0524:~$ jstack 114968 |grep tid=|wc -l
1144

Adding a lock around the Connection check gets me this total on start.

stack@ve0524:~$ jstack 118574|grep tid=|wc -l
476

Instrumenting the ConnectionFactory used by the 1.0.2 hbaseclient10, I can see us making more than a single instance of the cluster connection Connection object:

```
   6 2016-04-08 15:51:07:313 0 sec: 0 operations; est completion in 0 seconds
   7 Maximum execution time specified as: 3600 secs
   8 2016-04-08 15:51:07,435 WARN  [Thread-4] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
   9 2016-04-08 15:51:07,705 INFO  [Thread-16] client.ConnectionFactory: Created connection with class class org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation, user=stack (auth:SIMPLE), managed=false, pool=null
  10 java.lang.RuntimeException: Exception just to show where we are called form!
  11   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:241)
  12   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:221)
  13   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:122)
  14   at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:139)
  15   at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
  16   at com.yahoo.ycsb.ClientThread.run(Client.java:289)
  17 2016-04-08 15:51:07,717 INFO  [Thread-135] client.ConnectionFactory: Created connection with class class org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation, user=stack (auth:SIMPLE), managed=false, pool=null
  18 java.lang.RuntimeException: Exception just to show where we are called form!
  19   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:241)
  20   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:221)
  21   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:122)
  22   at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:139)
  23   at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
  24   at com.yahoo.ycsb.ClientThread.run(Client.java:289)
  25 2016-04-08 15:51:07,717 INFO  [Thread-115] client.ConnectionFactory: Created connection with class class org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation, user=stack (auth:SIMPLE), managed=false, pool=null
  26 java.lang.RuntimeException: Exception just to show where we are called form!
  27   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:241)
  28   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:221)
  29   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:122)
  30   at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:139)
  31   at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
  32   at com.yahoo.ycsb.ClientThread.run(Client.java:289)
  33 2016-04-08 15:51:07,717 INFO  [Thread-53] client.ConnectionFactory: Created connection with class class org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation, user=stack (auth:SIMPLE), managed=false, pool=null
  34 java.lang.RuntimeException: Exception just to show where we are called form!
  35   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:241)
  36   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:221)
  37   at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:122)
  38   at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:139)
  39   at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
  40   at com.yahoo.ycsb.ClientThread.run(Client.java:289)
...
```

And so on.

Gets extra interesting if each cluster Connection instance is configured to use more than one connection to each server in a cluster.

**Comment by risdenk** [comment]
Closing since PR #692 was merged.
