### ISSUE TITLE
Syntax error while loading workload

### ISSUE THREAD

**Issue by fizwhiz** [brianfrankcooper/YCSB#700]
As noted in a few other issues ([679](https://github.com/brianfrankcooper/YCSB/issues/679), [397](https://github.com/brianfrankcooper/YCSB/issues/397), [337](https://github.com/brianfrankcooper/YCSB/issues/337)) I'm able to successfully compile YCSB but run into the following issue while running the following command: `bin/ycsb load elasticsearch -s -P workloads/workloada`:

```
Traceback (most recent call last):
  File "bin/ycsb", line 261, in <module>
    sys.exit(main())
  File "bin/ycsb", line 234, in main
    maven_says = get_classpath_from_maven(project)
  File "bin/ycsb", line 180, in get_classpath_from_maven
    + err.output)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
Here are my system versions.
```
OS: Ubuntu 14.04
Java version:   1.8.0_77
Maven version:  3.0.5
Python version: 2.7.6
```
Unfortunately, despite having python's version as a 2.7.x, I'm still running into issues. Any recommendations?

**Comment by busbey** [comment]
can you attach a log with all of the output?

Are you attempting to run from the source checkout? Or are you building a binary tarball and then running from that?

**Comment by fizwhiz** [comment]
@busbey I'm running from the source checkout. I'll attach the output shortly.

**Comment by fizwhiz** [comment]
@busbey here's how I got YCSB in case it provides any clues:

```
git clone git://github.com/brianfrankcooper/YCSB.git
cd YCSB
mvn clean package
```
followed by whichever command(s). I noticed that I'm on version 0.9.0 snapshot since I'm building everything from the master branch.

**Comment by busbey** [comment]
what happens when you run the "give me the classpath" command manually?

it's this bit from the log:

```bash
mvn -pl com.yahoo.ycsb:core -am package -DskipTests dependency:build-classpath \
    -DincludeScope=compile -Dmdep.outputFilterFile=true
```

**Comment by fizwhiz** [comment]
@busbey looks like a build failure:

```
root@XYZ:~/YCSB# mvn -pl com.yahoo.ycsb:core -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.yahoo.ycsb:hbase094-binding:jar:0.9.0-SNAPSHOT
[WARNING] 'dependencies.dependency.exclusions.exclusion.groupId' for com.yahoo.ycsb:hbase098-binding:jar with value '*' does not match a valid id pattern. @ line 51, column 20
[WARNING] 'dependencies.dependency.exclusions.exclusion.artifactId' for com.yahoo.ycsb:hbase098-binding:jar with value '*' does not match a valid id pattern. @ line 52, column 23
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] YCSB Root
[INFO] Core YCSB
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building YCSB Root 0.9.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.15:check (validate) @ root ---
[INFO] 
[INFO] --- maven-dependency-plugin:2.1:build-classpath (default-cli) @ root ---
Downloading: http://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-core/1.0-alpha-7/doxia-core-1.0-alpha-7.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] YCSB Root ......................................... FAILURE [2.220s]
[INFO] Core YCSB ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.897s
[INFO] Finished at: Mon Apr 11 00:57:32 PDT 2016
[INFO] Final Memory: 19M/324M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.1:build-classpath (default-cli) on project root: Execution default-cli of goal org.apache.maven.plugins:maven-dependency-plugin:2.1:build-classpath failed: Plugin org.apache.maven.plugins:maven-dependency-plugin:2.1 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven.doxia:doxia-core:jar:1.0-alpha-7 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-core/1.0-alpha-7/doxia-core-1.0-alpha-7.jar. Return code is: 503 , ReasonPhrase:Service Unavailable. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by risdenk** [comment]
@fizwhiz I've had no issues using Maven 3.0.5 from a Ubuntu Docker image for testing. The 503 error was probably intermittent and the resolution had nothing to do with upgrading Maven.

Here are the commands I've used:
```
docker run --rm -it ubuntu bash
```
then inside the Docker container
```
apt-get update && apt-get install -y --no-install-recommends maven git openjdk-7-jdk python
git clone https://github.com/brianfrankcooper/YCSB.git
cd YCSB
mvn clean package -DskipTests #skipTests to save some time
...
[INFO] Reactor Summary:
[INFO]
[INFO] YCSB Root ......................................... SUCCESS [2.270s]
[INFO] Core YCSB ......................................... SUCCESS [6.940s]
[INFO] Per Datastore Binding descriptor .................. SUCCESS [0.311s]
[INFO] YCSB Datastore Binding Parent ..................... SUCCESS [0.619s]
[INFO] Accumulo DB Binding ............................... SUCCESS [6.609s]
[INFO] Aerospike DB Binding .............................. SUCCESS [0.791s]
[INFO] Cassandra DB Binding .............................. SUCCESS [2.566s]
[INFO] Cassandra 2.1+ DB Binding ......................... SUCCESS [1.796s]
[INFO] Couchbase Binding ................................. SUCCESS [0.931s]
[INFO] Couchbase Java SDK 2.x Binding .................... SUCCESS [1.049s]
[INFO] DynamoDB DB Binding ............................... SUCCESS [4.414s]
[INFO] Elasticsearch Binding ............................. SUCCESS [2.631s]
[INFO] Geode DB Binding .................................. SUCCESS [6.830s]
[INFO] Google Cloud Datastore Binding .................... SUCCESS [1.177s]
[INFO] Google Cloud Bigtable Binding ..................... SUCCESS [3.042s]
[INFO] HBase 0.98.x DB Binding ........................... SUCCESS [3.120s]
[INFO] HBase 0.94.x DB Binding ........................... SUCCESS [3.960s]
[INFO] HBase 1.0 DB Binding .............................. SUCCESS [5.208s]
[INFO] Hypertable DB Binding ............................. SUCCESS [1.217s]
[INFO] Infinispan DB Binding ............................. SUCCESS [8.939s]
[INFO] JDBC DB Binding ................................... SUCCESS [4.721s]
[INFO] Kudu DB Binding ................................... SUCCESS [9.382s]
[INFO] memcached binding ................................. SUCCESS [2.391s]
[INFO] MongoDB Binding ................................... SUCCESS [7.070s]
[INFO] Oracle NoSQL Database Binding ..................... SUCCESS [2.259s]
[INFO] OrientDB Binding .................................. SUCCESS [12.383s]
[INFO] Redis DB Binding .................................. SUCCESS [1.106s]
[INFO] S3 Storage Binding ................................ SUCCESS [2.477s]
[INFO] Solr Binding ...................................... SUCCESS [31.477s]
[INFO] Tarantool DB Binding .............................. SUCCESS [1.182s]
[INFO] YCSB Release Distribution Builder ................. SUCCESS [19.096s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:38.523s
[INFO] Finished at: Tue Apr 12 21:25:31 UTC 2016
[INFO] Final Memory: 128M/305M
[INFO] ------------------------------------------------------------------------

./bin/ycsb load basic -P workloads/workloada
...
[OVERALL], RunTime(ms), 1026.0
[OVERALL], Throughput(ops/sec), 974.6588693957115
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 1.0
[CLEANUP], MinLatency(us), 1.0
[CLEANUP], MaxLatency(us), 1.0
[CLEANUP], 95thPercentileLatency(us), 1.0
[CLEANUP], 99thPercentileLatency(us), 1.0
[INSERT], Operations, 1000.0
[INSERT], AverageLatency(us), 875.279
[INSERT], MinLatency(us), 173.0
[INSERT], MaxLatency(us), 12607.0
[INSERT], 95thPercentileLatency(us), 2585.0
[INSERT], 99thPercentileLatency(us), 4859.0
[INSERT], Return=OK, 1000

./bin/ycsb run basic -P workloads/workloada
...
[OVERALL], RunTime(ms), 329.0
[OVERALL], Throughput(ops/sec), 3039.51367781155
[CLEANUP], Operations, 1.0
[CLEANUP], AverageLatency(us), 3.0
[CLEANUP], MinLatency(us), 3.0
[CLEANUP], MaxLatency(us), 3.0
[CLEANUP], 95thPercentileLatency(us), 3.0
[CLEANUP], 99thPercentileLatency(us), 3.0
[READ], Operations, 513.0
[READ], AverageLatency(us), 151.05653021442495
[READ], MinLatency(us), 55.0
[READ], MaxLatency(us), 1856.0
[READ], 95thPercentileLatency(us), 438.0
[READ], 99thPercentileLatency(us), 704.0
[READ], Return=OK, 513
[UPDATE], Operations, 487.0
[UPDATE], AverageLatency(us), 308.9158110882957
[UPDATE], MinLatency(us), 117.0
[UPDATE], MaxLatency(us), 8311.0
[UPDATE], 95thPercentileLatency(us), 780.0
[UPDATE], 99thPercentileLatency(us), 1161.0
[UPDATE], Return=OK, 487
```

Here is the relevant information about OS, Maven, Java, Python, etc:
```
# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

# mvn --version
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_95, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.1.19-boot2docker", arch: "amd64", family: "unix"

# python --version
Python 2.7.6
```

**Comment by risdenk** [comment]
The underlying error from Python should be fixed even though the error that caused this seems to be Maven central being flakey.
```
Traceback (most recent call last):
  File "bin/ycsb", line 261, in <module>
    sys.exit(main())
  File "bin/ycsb", line 234, in main
    maven_says = get_classpath_from_maven(project)
  File "bin/ycsb", line 180, in get_classpath_from_maven
    + err.output)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by fizwhiz** [comment]
You're right, I tried this on a different public cloud but retained the _old_ maven version and things worked just fine. Didn't suspect that that a flakey central repo could manifest this way in the traceback. Thanks much @busbey for recommending that I run the `mvn -pl ...` command to reveal further insights into the issue, and thanks @risdenk for helping clarify the root cause!

**Comment by risdenk** [comment]
awesome glad we could help. I'm going to open an issue for the Python error to try to track that down. Thanks for reporting. Open a new issue if you have any other problems.

**Comment by intasp** [comment]
I met this problem too, are u fixed this problem? can u share it ?
