### ISSUE TITLE
YCSB 0.7.0 with Cassandra 3.4.0 gets a NoHostAvailableException due to unsupported protocol

### ISSUE THREAD

**Issue by karenlaw** [brianfrankcooper/YCSB#702]
I am trying to run ycsb 0.7.0 on cassandra 3.4.0 cluster. I am getting NoHostAvailableException. However, when I do cqlsh <ip of cassandra cluster>, I can connect successfully and issue select statement. What am I missing? Please help. I have tried the command with and without quote around hosts option as suggested by another post. It doesn't make a difference.
```
[root@CassandraTest ycsb-0.7.0]# cqlsh xxx.xxx.xxx.xxx --cqlversion=3.4.0
Connected to DCVP_C2 at xxx.xxx.xxx.xxx:9042.
[cqlsh 5.0.1 | Cassandra 3.4.0 | CQL spec 3.4.0 | Native protocol v4]
Use HELP for help.
cqlsh> select * from ycsb.usertable
   ... ;

 y_id | field0 | field1 | field10 | field11 | field12 | field13 | field14 | field15 | field16 | field17 | field18 | field19 | field2 | field20 | field3 | field4 | field5 | field6 | field7 | field8 | field9
------+--------+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+--------+---------+--------+--------+--------+--------+--------+--------+--------

(0 rows)

[root@CassandraTest ycsb-0.7.0]# ./bin/ycsb load cassandra-cql -p hosts=xxx.xxx.xxx.xxx -P workloads/workloada -s
[WARN]  The 'cassandra-7', 'cassandra-8', 'cassandra-10', and cassandra-cql' clients are deprecated. If you are using Cassandra 2.X try using the 'cassandra2-cql' client instead.
java -cp /home/cassandra/ycsb-0.7.0/cassandra-binding/conf:/home/cassandra/ycsb-0.7.0/conf:/home/cassandra/ycsb-0.7.0/lib/core-0.7.0.jar:/home/cassandra/ycsb-0.7.0/lib/jackson-mapper-asl-1.9.4.jar:/home/cassandra/ycsb-0.7.0/lib/jackson-core-asl-1.9.4.jar:/home/cassandra/ycsb-0.7.0/lib/HdrHistogram-2.1.4.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/snakeyaml-1.6.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/snappy-java-1.0.5.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/snaptree-0.1.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/stringtemplate-3.2.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/cassandra-binding-0.7.0.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/antlr-2.7.7.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/antlr-3.2.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/antlr-runtime-3.2.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/avro-1.4.0-cassandra-1.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/cassandra-all-1.2.9.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/cassandra-driver-core-1.0.3.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/cassandra-thrift-1.2.9.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/commons-cli-1.1.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/commons-codec-1.2.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/commons-lang-2.6.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/commons-logging-1.1.1.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/compress-lzf-0.8.4.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/concurrentlinkedhashmap-lru-1.3.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/guava-13.0.1.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/high-scale-lib-1.1.2.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/httpclient-4.0.1.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/httpcore-4.0.1.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/jackson-core-asl-1.9.2.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/jackson-mapper-asl-1.9.2.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/jamm-0.2.5.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/jbcrypt-0.3m.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/jetty-6.1.22.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/jetty-util-6.1.22.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/jline-1.0.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/json-simple-1.1.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/libthrift-0.7.0.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/log4j-1.2.16.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/lz4-1.1.0.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/metrics-core-2.0.3.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/netty-3.5.9.Final.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/servlet-api-2.5-20081211.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/servlet-api-2.5.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/slf4j-api-1.6.4.jar:/home/cassandra/ycsb-0.7.0/cassandra-binding/lib/slf4j-log4j12-1.7.2.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=10.195.39.246 -P workloads/workloada -s -load
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=10.195.39.246 -P workloads/workloada -s -load
Loading workload...
Starting test.
2016-04-11 17:10:01:671 0 sec: 0 operations; est completion in 0 seconds 
log4j:WARN No appenders could be found for logger (com.datastax.driver.core.Cluster).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.195.39.246 ([/10.195.39.246] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/10.195.39.246] Unexpected exception triggered (org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 4))))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:159)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.195.39.246 ([/10.195.39.246] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/10.195.39.246] Unexpected exception triggered (org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 4))))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:186)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:644)
	at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:586)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:69)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:96)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:567)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:129)
	... 2 more
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.195.39.246 ([/10.195.39.246] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/10.195.39.246] Unexpected exception triggered (org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 4))))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:159)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.195.39.246 ([/10.195.39.246] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/10.195.39.246] Unexpected exception triggered (org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 4))))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:186)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:644)
	at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:586)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:69)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:96)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:567)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:129)
	... 2 more
2016-04-11 17:10:02:796 1 sec: 0 operations; est completion in 106751991167300 days 15 hours 
[OVERALL], RunTime(ms), 1209.0
[OVERALL], Throughput(ops/sec), 0.0
[root@CassandraTest ycsb-0.7.0]# 
```

**Comment by risdenk** [comment]
The error is in the message you got "Invalid or unsupported protocol version: 4" 

Cassandra 3.x isn't supported in YCSB 0.7.0. Support was just added into master with #612 and should be available with YCSB 0.8.0 which is being tracked here #678

**Comment by risdenk** [comment]
Closing since YCSB 0.8.0 was just released: https://github.com/brianfrankcooper/YCSB/releases/tag/0.8.0 It should contain support for Cassandra 3.x. 

Please reopen if it doesn't work.

**Comment by rosstex** [comment]
I am getting this error with Cassandra 3.0.6
