### ISSUE TITLE
[hbase10] see if we can silence unneeded warnings

### ISSUE THREAD

**Issue by busbey** [brianfrankcooper/YCSB#706]
Running the hbase10 client from 0.8.0 on a cluster with all /etc/hosts based DNS and a local hostname that is not in said /etc/hosts, I got hte following message during set up.

```
16/04/13 17:38:16 WARN net.DNS: Unable to determine address of the host-falling back to "localhost" address
java.net.UnknownHostException: exampleedge: exampleedge: Name or service not known
        at java.net.InetAddress.getLocalHost(InetAddress.java:1496)
        at org.apache.hadoop.net.DNS.resolveLocalHostIPAddress(DNS.java:287)
        at org.apache.hadoop.net.DNS.<clinit>(DNS.java:58)
        at org.apache.hadoop.hbase.client.ScannerCallable.<clinit>(ScannerCallable.java:84)
        at org.apache.hadoop.hbase.client.ClientSmallScanner$SmallScannerCallableFactory.getCallable(ClientSmallScanner.java:308)
        at org.apache.hadoop.hbase.client.ClientSmallReversedScanner.nextScanner(ClientSmallReversedScanner.java:167)
        at org.apache.hadoop.hbase.client.ClientSmallReversedScanner.loadCache(ClientSmallReversedScanner.java:205)
        at org.apache.hadoop.hbase.client.ClientSmallReversedScanner.next(ClientSmallReversedScanner.java:185)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegionInMeta(ConnectionManager.java:1200)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.locateRegion(ConnectionManager.java:1109)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:369)
        at org.apache.hadoop.hbase.client.AsyncProcess.submit(AsyncProcess.java:320)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.backgroundFlushCommits(BufferedMutatorImpl.java:206)
        at org.apache.hadoop.hbase.client.BufferedMutatorImpl.flush(BufferedMutatorImpl.java:183)
        at org.apache.hadoop.hbase.client.HTable.flushCommits(HTable.java:1470)
        at org.apache.hadoop.hbase.client.HTable.put(HTable.java:1064)
        at com.yahoo.ycsb.db.HBaseClient10.update(HBaseClient10.java:450)
        at com.yahoo.ycsb.db.HBaseClient10.insert(HBaseClient10.java:481)
        at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:208)
        at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:579)
        at com.yahoo.ycsb.ClientThread.run(Client.java:346)
Caused by: java.net.UnknownHostException: exampleedge: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:922)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1316)
        at java.net.InetAddress.getLocalHost(InetAddress.java:1492)
        ... 20 more
```

The client recovered fine and went on its way. Should we suppress this message?

**Comment by risdenk** [comment]
This error looks correct and we shouldn't suppress it. It points to localhost not being configured in /etc/hosts right? That to me would be a misconfigured node. If that isn't an error then upstream hbase should not print the message. We shouldn't be doing anything special for clients in my opinion.

**Comment by risdenk** [comment]
Whoops misread error on my phone. I'm curious why hbase is printing that warning. Still don't think we should suppress it.

**Comment by busbey** [comment]
Well so long as someone finds it useful and we haven't started getting complaints yet, that's good enough for me.

I guess the hbase warning about no HDFS implementation probably happens more often and thus confuses more folks anyways.
