### ISSUE TITLE
bin/ycsb gives a TypeError when there is an error from Maven

### ISSUE THREAD

**Issue by risdenk** [brianfrankcooper/YCSB#708]
Traceback (most recent call last):
  File "bin/ycsb", line 261, in <module>
    sys.exit(main())
  File "bin/ycsb", line 234, in main
    maven_says = get_classpath_from_maven(project)
  File "bin/ycsb", line 180, in get_classpath_from_maven
    + err.output)
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by risdenk** [comment]
reported in #700
