### ISSUE TITLE
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed

### ISSUE THREAD

**Issue by taraliza** [brianfrankcooper/YCSB#710]
I am new to YCSB and am trying to benchmark Cassandra using YCSB.
My system specs are: Ubuntu 14, Cassandra 2.1, YCSB 0.7.0
As mentioned in the YCSB documentation, I am trying to execute the following command: 

```
./bin/ycsb load cassandra2-cql -p hosts="128.46.208.229" -p port=9042 -p debug=true -P workloads/workloada -s
```

But I get the following error:

```
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=128.46.208.229 -p port=9042 -p debug=true -P workloads/workloada -s -load
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2016-04-14 19:07:21:325 0 sec: 0 operations; est completion in 0 seconds
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /128.46.208.229:9042 (com.datastax.driver.core.TransportException: [/128.46.208.229:9042] Cannot connect))
        at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:193)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
        at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /128.46.208.229:9042 (com.datastax.driver.core.TransportException: [/128.46.208.229:9042] Cannot connect))
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:227)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1409)
        at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:382)
        at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:180)
        ... 2 more
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /128.46.208.229:9042 (com.datastax.driver.core.TransportException: [/128.46.208.229:9042] Cannot connect))
        at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:193)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
        at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /128.46.208.229:9042 (com.datastax.driver.core.TransportException: [/128.46.208.229:9042] Cannot connect))
        at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:227)
        at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1409)
        at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:382)
        at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:180)
        ... 2 more
2016-04-14 19:07:21:742 0 sec: 0 operations; est completion in 106751991167300 days 15 hours
[OVERALL], RunTime(ms), 444.0
[OVERALL], Throughput(ops/sec), 0.0
```

I googled for the error and tried updating my cassandra.yaml file as mentioned in https://github.com/brianfrankcooper/YCSB/issues/502.

It still is not working.

Could someone please help me debug this?

Thank you!

**Comment by risdenk** [comment]
@taraliza I added some formatting to your post to make it more readable.

Can you try removing the quotes from the hosts parameter?

```
./bin/ycsb load cassandra2-cql -p hosts=128.46.208.229 -p port=9042 -p debug=true -P workloads/workloada -s
```

**Comment by taraliza** [comment]
It looks like it was an issue with the Cassandra installation.

Seems like my JMX was not enabled to receive remote connections previously.
After updating the cassandra-env.sh file with the following changes, now I am able to connect successfully.
Uncomment JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=" and change to JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=127.0.0.1"
Change LOCAL_JMX=yes to LOCAL_JMX=no

Thanks for your help!

Closing this issue because the system is working now.
