### ISSUE TITLE
Cassandra: NoHostAvailableException (Unsupported Protocol Version 4)

### ISSUE THREAD

**Issue by rosstex** [brianfrankcooper/YCSB#761]
On YCSB 0.9.0, using Cassandra 3.0.6
```
rteixeira-mbp:ycsb-0.9.0 rteixeira$ bin/ycsb load cassandra2-cql -P workloads/workloada -p hosts="xxx.xxx.xxx.xxx"
java -cp /Users/rteixeira/Downloads/ycsb-0.9.0/cassandra2-binding/conf:/Users/rteixeira/Downloads/ycsb-0.9.0/conf:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/antlr-2.7.7.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/antlr-3.2.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/antlr-runtime-3.2.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/avro-1.4.0-cassandra-1.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/cassandra-all-1.2.9.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/cassandra-binding-0.9.0.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/cassandra-driver-core-1.0.3.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/cassandra-thrift-1.2.9.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/commons-cli-1.1.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/commons-codec-1.2.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/commons-lang-2.6.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/commons-logging-1.1.1.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/compress-lzf-0.8.4.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/concurrentlinkedhashmap-lru-1.3.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/core-0.9.0.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/guava-13.0.1.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/HdrHistogram-2.1.4.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/high-scale-lib-1.1.2.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/htrace-core4-4.1.0-incubating.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/httpclient-4.0.1.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/httpcore-4.0.1.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/jackson-core-asl-1.9.2.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/jackson-core-asl-1.9.4.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/jackson-mapper-asl-1.9.2.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/jackson-mapper-asl-1.9.4.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/jamm-0.2.5.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/jbcrypt-0.3m.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/jetty-6.1.22.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/jetty-util-6.1.22.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/jline-1.0.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/json-simple-1.1.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/libthrift-0.7.0.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/log4j-1.2.16.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/lz4-1.1.0.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/metrics-core-2.0.3.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/netty-3.5.9.Final.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/servlet-api-2.5-20081211.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/servlet-api-2.5.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/slf4j-api-1.6.4.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/slf4j-log4j12-1.7.2.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/snakeyaml-1.6.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/snappy-java-1.0.5.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/snaptree-0.1.jar:/Users/rteixeira/Downloads/ycsb-0.9.0/lib/stringtemplate-3.2.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloada -p hosts=10.8.107.77 -load
YCSB Client 0.9.0
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloada -p hosts=10.8.107.77 -load
Loading workload...
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.8.107.77 ([/10.8.107.77] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/10.8.107.77] Unexpected exception triggered (org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 4))))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:159)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:99)
	at com.yahoo.ycsb.ClientThread.run(Client.java:418)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.8.107.77 ([/10.8.107.77] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/10.8.107.77] Unexpected exception triggered (org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 4))))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:186)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:644)
	at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:586)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:69)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:96)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:567)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:130)
	... 3 more
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.8.107.77 ([/10.8.107.77] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/10.8.107.77] Unexpected exception triggered (org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 4))))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:159)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:99)
	at com.yahoo.ycsb.ClientThread.run(Client.java:418)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /10.8.107.77 ([/10.8.107.77] Unexpected error during transport initialization (com.datastax.driver.core.TransportException: [/10.8.107.77] Unexpected exception triggered (org.apache.cassandra.transport.ProtocolException: Invalid or unsupported protocol version: 4))))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:186)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:81)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:644)
	at com.datastax.driver.core.Cluster$Manager.access$100(Cluster.java:586)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:69)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:96)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:567)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:130)
	... 3 more
[OVERALL], RunTime(ms), 417.0
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 0.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 0.0
[TOTAL_GC_TIME], Time(ms), 0.0
[TOTAL_GC_TIME_%], Time(%), 0.0
```

**Comment by rosstex** [comment]
Similar to #702

**Comment by kruthar** [comment]
Hey @rosstex - could you share how you acquired your built copy of ycsb-0.9.0? I'm asking because I just pulled it down from here: https://github.com/brianfrankcooper/YCSB/releases/download/0.9.0/ycsb-0.9.0.tar.gz, unpacked it and tried to run your exact load command (with an appropriate host) and I could not do it. Received this error:

```
arrakis:ycsb-0.9.0 kruthar$ ./bin/ycsb load cassandra2-cql -P workloads/workloada -p hosts="192.168.56.41"
java -cp /Users/kruthar/projects/ycsb_releases/ycsb-0.9.0/cassandra2-binding/conf:/Users/kruthar/projects/ycsb_releases/ycsb-0.9.0/conf:/Users/kruthar/projects/ycsb_releases/ycsb-0.9.0/lib/core-0.9.0.jar:/Users/kruthar/projects/ycsb_releases/ycsb-0.9.0/lib/HdrHistogram-2.1.4.jar:/Users/kruthar/projects/ycsb_releases/ycsb-0.9.0/lib/htrace-core4-4.1.0-incubating.jar:/Users/kruthar/projects/ycsb_releases/ycsb-0.9.0/lib/jackson-core-asl-1.9.4.jar:/Users/kruthar/projects/ycsb_releases/ycsb-0.9.0/lib/jackson-mapper-asl-1.9.4.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloada -p hosts=192.168.56.41 -load
YCSB Client 0.9.0
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloada -p hosts=192.168.56.41 -load
Loading workload...
Starting test.
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.CassandraCQLClient
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:37)
	at com.yahoo.ycsb.Client.main(Client.java:1058)
Exception in thread "Thread-2" java.lang.NullPointerException
	at com.yahoo.ycsb.ClientThread.run(Client.java:418)
	at java.lang.Thread.run(Thread.java:745)
[OVERALL], RunTime(ms), 2.0
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 0.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 0.0
[TOTAL_GC_TIME], Time(ms), 0.0
[TOTAL_GC_TIME_%], Time(%), 0.0
```

It seems that the cassandra2-binding did not make it into the packaged ycsb-0.9.0 release. You can see this because 1) the path that gets built does not have any of the cassandra2-binding jars on it and 2) the cassandra2-binding is just not present in ycsb-0.9.0.tar.gz.

So, back to why I asked how you acquired your version of ycsb-0.9.0, your posted output suggests that the cassandra2-binding DOES exist in what ever release you are using, which to me is a mystery. The only way I can reason that this would be the case is if you hand built YCSB while we were still on ycsb-0.8.0, but even that does not seem plausible as it produces a differently named directory then where you are running from.

So, I know all that does not solve your problem. In the mean time, can you try two things:
1. Running your exact load command against source? You can do this by simply cloning the code base and running your command from there. Does that make things work?
2. Try pulling a fresh release from the link I provided above and verify if the cassandra2-binding is or is not present.

**Comment by kruthar** [comment]
@rosstex - did running against source work for you? You can also trying downloading and using the ycsb-0.8.0 release from here if you prefer a prebuilt package: https://github.com/brianfrankcooper/YCSB/releases/download/0.8.0/ycsb-0.8.0.tar.gz

**Comment by rosstex** [comment]
@kruthar Hi Kruthar. After pulling a fresh copy of the source and compiling/running, it ended up working. I'm not totally sure what happened, but I'm guessing that I had downloaded the packaged .tar, noticed cassandra missing and tried to manually merge it/compile from source. Lesson learned!
