### ISSUE TITLE
Large recordcount value exception: java.lang.NumberFormatException

### ISSUE THREAD

**Issue by salim-on-github** [brianfrankcooper/YCSB#764]
I am getting a `java.lang.NumberFormatException` because my database has more than 2 billion records. I suggest using `long`instead of `int` to parse the `recordcount`and `operationcount`values.

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "2700000000"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:76)
        at java.lang.Integer.parseInt(Integer.java:595)
        at java.lang.Integer.parseInt(Integer.java:627)
        at com.yahoo.ycsb.workloads.CoreWorkload.init(CoreWorkload.java:385)
        at com.yahoo.ycsb.Client.main(Client.java:836)
```

**Comment by kruthar** [comment]
@salim-on-github - thanks for the input. We have seen similar requests: #664, and this fix was actually attempted but then abandoned: #265. If you are interested in contributing this fix we would welcome it. Thanks!

**Comment by risdenk** [comment]
Closing as duplicate.
