### ISSUE TITLE
hbase10 binding fails with setDurability call on HBase 1.2.0 / CDH  5.7.1

### ISSUE THREAD

**Issue by lexpierce** [brianfrankcooper/YCSB#802]
```
Exception in thread "Thread-3" java.lang.NoSuchMethodError: org.apache.hadoop.hbase.client.Put.setDurability(Lorg/apache/hadoop/hbase/client/Durability;)Lorg/apache/hadoop/hbase/client/Put;
	at com.yahoo.ycsb.db.HBaseClient10.update(HBaseClient10.java:435)
	at com.yahoo.ycsb.DBWrapper.update(DBWrapper.java:216)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionUpdate(CoreWorkload.java:800)
	at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:633)
	at com.yahoo.ycsb.ClientThread.run(Client.java:458)
	at java.lang.Thread.run(Thread.java:745)
```

This is using ycsb-hbase10-binding-0.10.0 release.

Classpath
```
java.class.path=/etc/hbase/conf:/usr/lib/hbase/lib/jets3t-0.9.0.jar:/usr/lib/hbase/lib/activation-1.1.jar:/usr/lib/hbase/lib/jackson-core-asl-1.8.8.jar:/usr/lib/hbase/lib/apacheds-i18n-2.0.0-M15.jar:/usr/lib/hbase/lib/esapi-2.1.0.jar:/usr/lib/hbase/lib/xom-1.2.5.jar:/usr/lib/hbase/lib/apacheds-kerberos-codec-2.0.0-M15.jar:/usr/lib/hbase/lib/jackson-jaxrs-1.8.8.jar:/usr/lib/hbase/lib/api-asn1-api-1.0.0-M20.jar:/usr/lib/hbase/lib/jackson-mapper-asl-1.8.8.jar:/usr/lib/hbase/lib/api-util-1.0.0-M20.jar:/usr/lib/hbase/lib/asm-3.2.jar:/usr/lib/hbase/lib/log4j-1.2.17.jar:/usr/lib/hbase/lib/avro.jar:/usr/lib/hbase/lib/jackson-xc-1.8.8.jar:/usr/lib/hbase/lib/commons-beanutils-1.7.0.jar:/usr/lib/hbase/lib/hbase-annotations-1.2.0-cdh5.7.1-tests.jar:/usr/lib/hbase/lib/jettison-1.3.3.jar:/usr/lib/hbase/lib/commons-cli-1.2.jar:/usr/lib/hbase/lib/hbase-annotations-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/commons-codec-1.9.jar:/usr/lib/hbase/lib/commons-collections-3.2.2.jar:/usr/lib/hbase/lib/jasper-compiler-5.5.23.jar:/usr/lib/hbase/lib/commons-compress-1.4.1.jar:/usr/lib/hbase/lib/commons-configuration-1.6.jar:/usr/lib/hbase/lib/jasper-runtime-5.5.23.jar:/usr/lib/hbase/lib/commons-daemon-1.0.3.jar:/usr/lib/hbase/lib/java-xmlbuilder-0.4.jar:/usr/lib/hbase/lib/commons-digester-1.8.jar:/usr/lib/hbase/lib/jetty-6.1.26.cloudera.4.jar:/usr/lib/hbase/lib/commons-el-1.0.jar:/usr/lib/hbase/lib/jaxb-api-2.1.jar:/usr/lib/hbase/lib/commons-httpclient-3.1.jar:/usr/lib/hbase/lib/joni-2.1.2.jar:/usr/lib/hbase/lib/commons-io-2.4.jar:/usr/lib/hbase/lib/jruby-cloudera-1.0.0.jar:/usr/lib/hbase/lib/commons-lang-2.6.jar:/usr/lib/hbase/lib/jaxb-impl-2.2.3-1.jar:/usr/lib/hbase/lib/commons-logging-1.2.jar:/usr/lib/hbase/lib/jsch-0.1.42.jar:/usr/lib/hbase/lib/commons-math-2.1.jar:/usr/lib/hbase/lib/jcodings-1.0.8.jar:/usr/lib/hbase/lib/commons-math3-3.1.1.jar:/usr/lib/hbase/lib/jsp-2.1-6.1.14.jar:/usr/lib/hbase/lib/commons-net-3.1.jar:/usr/lib/hbase/lib/jsp-api-2.1-6.1.14.jar:/usr/lib/hbase/lib/core-3.1.1.jar:/usr/lib/hbase/lib/jersey-client-1.9.jar:/usr/lib/hbase/lib/curator-client-2.7.1.jar:/usr/lib/hbase/lib/jersey-core-1.9.jar:/usr/lib/hbase/lib/curator-framework-2.7.1.jar:/usr/lib/hbase/lib/jersey-json-1.9.jar:/usr/lib/hbase/lib/curator-recipes-2.7.1.jar:/usr/lib/hbase/lib/jsp-api-2.1.jar:/usr/lib/hbase/lib/disruptor-3.3.0.jar:/usr/lib/hbase/lib/jackson-annotations-2.2.3.jar:/usr/lib/hbase/lib/findbugs-annotations-1.3.9-1.jar:/usr/lib/hbase/lib/jsr305-1.3.9.jar:/usr/lib/hbase/lib/gson-2.2.4.jar:/usr/lib/hbase/lib/junit-4.12.jar:/usr/lib/hbase/lib/guava-12.0.1.jar:/usr/lib/hbase/lib/jersey-server-1.9.jar:/usr/lib/hbase/lib/hamcrest-core-1.3.jar:/usr/lib/hbase/lib/batik-css-1.7.jar:/usr/lib/hbase/lib/xalan-2.7.0.jar:/usr/lib/hbase/lib/libthrift-0.9.3.jar:/usr/lib/hbase/lib/high-scale-lib-1.1.1.jar:/usr/lib/hbase/lib/hsqldb-1.8.0.10.jar:/usr/lib/hbase/lib/jackson-core-2.2.3.jar:/usr/lib/hbase/lib/htrace-core-3.2.0-incubating.jar:/usr/lib/hbase/lib/aws-java-sdk-core-1.10.6.jar:/usr/lib/hbase/lib/aws-java-sdk-s3-1.10.6.jar:/usr/lib/hbase/lib/bsh-core-2.0b4.jar:/usr/lib/hbase/lib/jackson-databind-2.2.3.jar:/usr/lib/hbase/lib/htrace-core.jar:/usr/lib/hbase/lib/xz-1.0.jar:/usr/lib/hbase/lib/nekohtml-1.9.12.jar:/usr/lib/hbase/lib/htrace-core4-4.0.1-incubating.jar:/usr/lib/hbase/lib/antisamy-1.4.3.jar:/usr/lib/hbase/lib/xml-apis-1.3.03.jar:/usr/lib/hbase/lib/batik-util-1.7.jar:/usr/lib/hbase/lib/commons-fileupload-1.2.jar:/usr/lib/hbase/lib/jamon-runtime-2.4.1.jar:/usr/lib/hbase/lib/httpclient-4.2.5.jar:/usr/lib/hbase/lib/zookeeper.jar:/usr/lib/hbase/lib/spymemcached-2.11.6.jar:/usr/lib/hbase/lib/httpcore-4.2.5.jar:/usr/lib/hbase/lib/hbase-client-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/aws-java-sdk-kms-1.10.6.jar:/usr/lib/hbase/lib/batik-ext-1.7.jar:/usr/lib/hbase/lib/commons-beanutils-core-1.7.0.jar:/usr/lib/hbase/lib/xml-apis-ext-1.3.04.jar:/usr/lib/hbase/lib/jetty-sslengine-6.1.26.cloudera.4.jar:/usr/lib/hbase/lib/jetty-util-6.1.26.cloudera.4.jar:/usr/lib/hbase/lib/leveldbjni-all-1.8.jar:/usr/lib/hbase/lib/metrics-core-2.2.0.jar:/usr/lib/hbase/lib/netty-all-4.0.23.Final.jar:/usr/lib/hbase/lib/paranamer-2.3.jar:/usr/lib/hbase/lib/protobuf-java-2.5.0.jar:/usr/lib/hbase/lib/servlet-api-2.5-6.1.14.jar:/usr/lib/hbase/lib/servlet-api-2.5.jar:/usr/lib/hbase/lib/slf4j-api-1.7.5.jar:/usr/lib/hbase/lib/slf4j-log4j12.jar:/usr/lib/hbase/lib/snappy-java-1.0.4.1.jar:/usr/lib/hbase/lib/xercesImpl-2.9.1.jar:/usr/lib/hbase/lib/xmlenc-0.52.jar:/usr/lib/hbase/lib/hbase-hadoop2-compat-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-protocol-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-resource-bundle-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-procedure-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-rest-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-server-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-thrift-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-server-1.2.0-cdh5.7.1-tests.jar:/usr/lib/hbase/lib/hbase-spark-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-common-1.2.0-cdh5.7.1-tests.jar:/usr/lib/hbase/lib/hbase-common-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-examples-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-external-blockcache-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-hadoop-compat-1.2.0-cdh5.7.1-tests.jar:/usr/lib/hbase/lib/hbase-hadoop-compat-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-hadoop2-compat-1.2.0-cdh5.7.1-tests.jar:/usr/lib/hbase/lib/hbase-it-1.2.0-cdh5.7.1-tests.jar:/usr/lib/hbase/lib/hbase-it-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-prefix-tree-1.2.0-cdh5.7.1.jar:/usr/lib/hbase/lib/hbase-shell-1.2.0-cdh5.7.1.jar:/usr/lib/hadoop/parquet-format-javadoc.jar:/usr/lib/hadoop/parquet-format-sources.jar:/usr/lib/hadoop/parquet-format.jar:/usr/lib/hadoop/parquet-avro.jar:/usr/lib/hadoop/parquet-cascading.jar:/usr/lib/hadoop/parquet-column.jar:/usr/lib/hadoop/parquet-common.jar:/usr/lib/hadoop/parquet-encoding.jar:/usr/lib/hadoop/parquet-generator.jar:/usr/lib/hadoop/parquet-hadoop-bundle.jar:/usr/lib/hadoop/parquet-hadoop.jar:/usr/lib/hadoop/parquet-jackson.jar:/usr/lib/hadoop/parquet-pig-bundle.jar:/usr/lib/hadoop/parquet-pig.jar:/usr/lib/hadoop/parquet-protobuf.jar:/usr/lib/hadoop/parquet-scala_2.10.jar:/usr/lib/hadoop/parquet-scrooge_2.10.jar:/usr/lib/hadoop/parquet-test-hadoop2.jar:/usr/lib/hadoop/parquet-thrift.jar:/usr/lib/hadoop/parquet-tools.jar:/usr/lib/hadoop/hadoop-annotations.jar:/usr/lib/hadoop/hadoop-auth.jar:/usr/lib/hadoop/hadoop-aws.jar:/usr/lib/hadoop/hadoop-common-tests.jar:/usr/lib/hadoop/hadoop-common.jar:/usr/lib/hadoop/hadoop-nfs.jar:/usr/lib/hadoop/hadoop-annotations-2.6.0-cdh5.7.1.jar:/usr/lib/hadoop/hadoop-auth-2.6.0-cdh5.7.1.jar:/usr/lib/hadoop/hadoop-aws-2.6.0-cdh5.7.1.jar:/usr/lib/hadoop/hadoop-common-2.6.0-cdh5.7.1-tests.jar:/usr/lib/hadoop/hadoop-common-2.6.0-cdh5.7.1.jar:/usr/lib/hadoop/hadoop-nfs-2.6.0-cdh5.7.1.jar:/usr/lib/hadoop/lib/activation-1.1.jar:/usr/lib/hadoop/lib/jsch-0.1.42.jar:/usr/lib/hadoop/lib/apacheds-i18n-2.0.0-M15.jar:/usr/lib/hadoop/lib/mockito-all-1.8.5.jar:/usr/lib/hadoop/lib/apacheds-kerberos-codec-2.0.0-M15.jar:/usr/lib/hadoop/lib/netty-3.6.2.Final.jar:/usr/lib/hadoop/lib/api-asn1-api-1.0.0-M20.jar:/usr/lib/hadoop/lib/paranamer-2.3.jar:/usr/lib/hadoop/lib/api-util-1.0.0-M20.jar:/usr/lib/hadoop/lib/asm-3.2.jar:/usr/lib/hadoop/lib/avro.jar:/usr/lib/hadoop/lib/protobuf-java-2.5.0.jar:/usr/lib/hadoop/lib/pd-commons-logging.jar:/usr/lib/hadoop/lib/servlet-api-2.5.jar:/usr/lib/hadoop/lib/commons-beanutils-1.7.0.jar:/usr/lib/hadoop/lib/jets3t-0.9.0.jar:/usr/lib/hadoop/lib/commons-beanutils-core-1.8.0.jar:/usr/lib/hadoop/lib/commons-cli-1.2.jar:/usr/lib/hadoop/lib/slf4j-api-1.7.5.jar:/usr/lib/hadoop/lib/commons-codec-1.4.jar:/usr/lib/hadoop/lib/jettison-1.1.jar:/usr/lib/hadoop/lib/commons-collections-3.2.2.jar:/usr/lib/hadoop/lib/slf4j-log4j12.jar:/usr/lib/hadoop/lib/commons-compress-1.4.1.jar:/usr/lib/hadoop/lib/jetty-6.1.26.cloudera.4.jar:/usr/lib/hadoop/lib/commons-configuration-1.6.jar:/usr/lib/hadoop/lib/snappy-java-1.0.4.1.jar:/usr/lib/hadoop/lib/commons-digester-1.8.jar:/usr/lib/hadoop/lib/commons-el-1.0.jar:/usr/lib/hadoop/lib/stax-api-1.0-2.jar:/usr/lib/hadoop/lib/commons-httpclient-3.1.jar:/usr/lib/hadoop/lib/commons-io-2.4.jar:/usr/lib/hadoop/lib/commons-lang-2.6.jar:/usr/lib/hadoop/lib/xmlenc-0.52.jar:/usr/lib/hadoop/lib/commons-logging-1.1.3.jar:/usr/lib/hadoop/lib/xz-1.0.jar:/usr/lib/hadoop/lib/commons-math3-3.1.1.jar:/usr/lib/hadoop/lib/commons-net-3.1.jar:/usr/lib/hadoop/lib/zookeeper.jar:/usr/lib/hadoop/lib/curator-client-2.7.1.jar:/usr/lib/hadoop/lib/pd-lib4j.jar:/usr/lib/hadoop/lib/curator-framework-2.7.1.jar:/usr/lib/hadoop/lib/aws-java-sdk-kms-1.10.6.jar:/usr/lib/hadoop/lib/curator-recipes-2.7.1.jar:/usr/lib/hadoop/lib/gson-2.2.4.jar:/usr/lib/hadoop/lib/guava-11.0.2.jar:/usr/lib/hadoop/lib/hamcrest-core-1.3.jar:/usr/lib/hadoop/lib/jetty-util-6.1.26.cloudera.4.jar:/usr/lib/hadoop/lib/htrace-core4-4.0.1-incubating.jar:/usr/lib/hadoop/lib/httpclient-4.2.5.jar:/usr/lib/hadoop/lib/httpcore-4.2.5.jar:/usr/lib/hadoop/lib/aws-java-sdk-core-1.10.6.jar:/usr/lib/hadoop/lib/jackson-core-asl-1.8.8.jar:/usr/lib/hadoop/lib/aws-java-sdk-s3-1.10.6.jar:/usr/lib/hadoop/lib/jackson-jaxrs-1.8.8.jar:/usr/lib/hadoop/lib/jackson-mapper-asl-1.8.8.jar:/usr/lib/hadoop/lib/jackson-xc-1.8.8.jar:/usr/lib/hadoop/lib/jasper-compiler-5.5.23.jar:/usr/lib/hadoop/lib/jasper-runtime-5.5.23.jar:/usr/lib/hadoop/lib/java-xmlbuilder-0.4.jar:/usr/lib/hadoop/lib/jaxb-api-2.2.2.jar:/usr/lib/hadoop/lib/jaxb-impl-2.2.3-1.jar:/usr/lib/hadoop/lib/jersey-core-1.9.jar:/usr/lib/hadoop/lib/jersey-json-1.9.jar:/usr/lib/hadoop/lib/jersey-server-1.9.jar:/usr/lib/hadoop/lib/jsp-api-2.1.jar:/usr/lib/hadoop/lib/jsr305-3.0.0.jar:/usr/lib/hadoop/lib/junit-4.11.jar:/usr/lib/hadoop/lib/log4j-1.2.17.jar:/usr/lib/hadoop/lib/logredactor-1.0.3.jar:/usr/lib/hadoop/lib/PepperdataSupervisor.jar:/usr/lib/hadoop-hdfs/hadoop-hdfs-nfs.jar:/usr/lib/hadoop-hdfs/hadoop-hdfs-tests.jar:/usr/lib/hadoop-hdfs/hadoop-hdfs.jar:/usr/lib/hadoop-hdfs/hadoop-hdfs-2.6.0-cdh5.7.1-tests.jar:/usr/lib/hadoop-hdfs/hadoop-hdfs-2.6.0-cdh5.7.1.jar:/usr/lib/hadoop-hdfs/hadoop-hdfs-nfs-2.6.0-cdh5.7.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/hbase10-binding/conf:/home/alex/Source/ycsb-hbase10-binding-0.10.0/conf:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/core-0.10.0.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/htrace-core4-4.1.0-incubating.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/HdrHistogram-2.1.4.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hbase-client-1.0.2.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hbase-annotations-1.0.2.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/findbugs-annotations-1.3.9-1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/log4j-1.2.17.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hbase-common-1.0.2.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/guava-12.0.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/jsr305-1.3.9.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-logging-1.2.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-codec-1.9.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-lang-2.6.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-collections-3.2.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-io-2.4.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/protobuf-java-2.5.0.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/jetty-util-6.1.26.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/htrace-core-3.1.0-incubating.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hadoop-common-2.5.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hadoop-annotations-2.5.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-cli-1.2.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-math3-3.1.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/xmlenc-0.52.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-httpclient-3.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-net-3.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/jaxb-api-2.2.2.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/stax-api-1.0-2.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/activation-1.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/jackson-core-asl-1.9.4.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/jackson-mapper-asl-1.8.8.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-el-1.0.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/httpclient-4.2.5.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/httpcore-4.2.4.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-configuration-1.6.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-digester-1.8.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-beanutils-1.7.0.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-beanutils-core-1.8.0.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/slf4j-api-1.6.4.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/slf4j-log4j12-1.7.7.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/avro-1.7.4.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/paranamer-2.3.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/snappy-java-1.0.4.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/commons-compress-1.4.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/xz-1.0.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hadoop-auth-2.5.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/apacheds-kerberos-codec-2.0.0-M15.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/apacheds-i18n-2.0.0-M15.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/api-asn1-api-1.0.0-M20.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/api-util-1.0.0-M20.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/jsch-0.1.42.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/zookeeper-3.4.6.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hadoop-mapreduce-client-core-2.5.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hadoop-yarn-common-2.5.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hadoop-yarn-api-2.5.1.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hbase-protocol-1.0.2.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/netty-all-4.0.23.Final.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/jcodings-1.0.8.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/joni-2.1.2.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/netty-3.6.2.Final.jar:/home/alex/Source/ycsb-hbase10-binding-0.10.0/lib/hbase10-binding-0.10.0.jar
```

**Comment by busbey** [comment]
What version of YCSB are you using?

How are you invoking YCSB?

It looks like you are ending up with both the client jars for HBase that we ship as well as the HBase client jars that come with CDH. You should only have the former.

**Comment by busbey** [comment]
any update on trying with just the hbase jars YCSB ships?

**Comment by lexpierce** [comment]
Sorry-- been away. Yes, it worked better with just the provided jars. I used a launch script from an old 0.3.0 launch and things have changed a lot.
