### ISSUE TITLE
ycsb can not connect to mongodb with auth?

### ISSUE THREAD

**Issue by hzruandd** [brianfrankcooper/YCSB#809]
When ycsb connected mongodb cluster,login access authentication failed,but succeed with mongo shell.
**mongodb** : Version3.2.6
**ycsb**: latest master branch

ERROR:
     Command line: -db com.yahoo.ycsb.db.AsyncMongoDbClient -P workloads/workload1 -s -load
Loading workload...
Starting test.
2016-07-26 18:21:21:812 0 sec: 0 operations; est completion in 0 seconds 
2016-07-26 18:21:21:812 0 sec: 0 operations; est completion in 0 seconds 
mongo connection created with mongodb://yy:yy@localhost:27017/ycsb?w=1
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
Jul 26, 2016 6:21:22 PM com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection ensureAuthenticated
WARNING: Authentication failed: []
com.allanbank.mongodb.error.MongoDbAuthenticationException: com.allanbank.mongodb.error.ReplyException: auth failed at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:123)

**Comment by allanbank** [comment]
What type of authentication is the MongoDB server configured to use?  The async binding's driver does not support the SCRAM_SHA_1 authentication in a released version.

**Comment by hzruandd** [comment]
i use the keyfile(openssl).

**Comment by allanbank** [comment]
Are you using x.509 authentication?  Can you paste your mongodb shell command (mask any passwords)?

**Comment by hzruandd** [comment]
i only use the keyfile.

security:
   authorization: enabled
   keyFile: /data/mongodbtest/replset/keyfile

**Comment by allanbank** [comment]
The key file is only used for authentication of the members of the cluster.  

You said in the original request that you could connect via the MongoDB shell.  What does the `mongo` command line look like that you are using?

**Comment by allanbank** [comment]
Also out of curiosity can you try connecting without the user name and password in the MongoDB URI?  Use something like:

    mongodb://localhost:27017/ycsb?w=1

**Comment by hzruandd** [comment]
As we all know,we should connect with the user name and password in the MongoDB URI when  set authorization to enable in the config file.  i think it maybe the JavaClient has not support the auth.

**Comment by busbey** [comment]
Did you try out the suggestion @hzruandd? Could you provide the mongo command line that works?

**Comment by risdenk** [comment]
Closing due to inactivity.

**Comment by lzbgt** [comment]
I have the same problem with mongodb-async. the sync version is ok.
```
[root@redis3 ycsb-0.12.0]# bin/ycsb load mongodb-async -p mongodb.url=mongodb://ycsb:ycsb@192.168.50.136/ycsb?w=1 -s -P workloads/workloada
java -cp /root/work/ycsb-0.12.0/mongodb-binding/conf:/root/work/ycsb-0.12.0/conf:/root/work/ycsb-0.12.0/lib/core-0.12.0.jar:/root/work/ycsb-0.12.0/lib/htrace-core4-4.1.0-incubating.jar:/root/work/ycsb-0.12.0/lib/jackson-mapper-asl-1.9.4.jar:/root/work/ycsb-0.12.0/lib/jackson-core-asl-1.9.4.jar:/root/work/ycsb-0.12.0/lib/HdrHistogram-2.1.4.jar:/root/work/ycsb-0.12.0/mongodb-binding/lib/logback-classic-1.1.2.jar:/root/work/ycsb-0.12.0/mongodb-binding/lib/logback-core-1.1.2.jar:/root/work/ycsb-0.12.0/mongodb-binding/lib/mongo-java-driver-3.0.3.jar:/root/work/ycsb-0.12.0/mongodb-binding/lib/mongodb-async-driver-2.0.1.jar:/root/work/ycsb-0.12.0/mongodb-binding/lib/slf4j-api-1.6.4.jar:/root/work/ycsb-0.12.0/mongodb-binding/lib/mongodb-binding-0.12.0.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.AsyncMongoDbClient -p mongodb.url=mongodb://ycsb:ycsb@192.168.50.136/ycsb?w=1 -s -P workloads/workloada -load
YCSB Client 0.12.0
Command line: -db com.yahoo.ycsb.db.AsyncMongoDbClient -p mongodb.url=mongodb://ycsb:ycsb@192.168.50.136/ycsb?w=1 -s -P workloads/workloada -load
Loading workload...
Starting test.
2018-03-07 17:58:45:459 0 sec: 0 operations; est completion in 0 seconds 
mongo connection created with mongodb://ycsb:ycsb@192.168.50.136/ycsb?w=1
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
17:58:45.802 [Thread-3] WARN  c.a.m.c.c.a.AuthenticatingConnection - Authentication failed: []
com.allanbank.mongodb.error.MongoDbAuthenticationException: com.allanbank.mongodb.error.ReplyException: auth failed
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:123) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.ensureAuthenticated(AuthenticatingConnection.java:181) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.AuthenticatingConnection.send(AuthenticatingConnection.java:133) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.bootstrap(BootstrapConnectionFactory.java:179) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.createDelegate(BootstrapConnectionFactory.java:290) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getDelegate(BootstrapConnectionFactory.java:268) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.bootstrap.BootstrapConnectionFactory.getClusterStats(BootstrapConnectionFactory.java:114) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.ClientImpl.getClusterStats(ClientImpl.java:199) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.doInsertAsync(AbstractMongoOperations.java:1037) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractMongoOperations.insertAsync(AbstractMongoOperations.java:583) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.AbstractAsyncMongoCollection.insertAsync(AbstractAsyncMongoCollection.java:1255) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:684) [mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.SynchronousMongoCollectionImpl.insert(SynchronousMongoCollectionImpl.java:722) [mongodb-async-driver-2.0.1.jar:na]
	at com.yahoo.ycsb.db.AsyncMongoDbClient.insert(AsyncMongoDbClient.java:272) [mongodb-binding-0.12.0.jar:na]
	at com.yahoo.ycsb.DBWrapper.insert(DBWrapper.java:240) [core-0.12.0.jar:na]
	at com.yahoo.ycsb.workloads.CoreWorkload.doInsert(CoreWorkload.java:593) [core-0.12.0.jar:na]
	at com.yahoo.ycsb.ClientThread.run(Client.java:475) [core-0.12.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]
Caused by: java.util.concurrent.ExecutionException: com.allanbank.mongodb.error.ReplyException: auth failed
	at com.allanbank.mongodb.client.FutureCallback$Sync.getValue(FutureCallback.java:581) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback$Sync.get(FutureCallback.java:489) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.FutureCallback.get(FutureCallback.java:223) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.auth.MongoDbAuthenticator.result(MongoDbAuthenticator.java:117) ~[mongodb-async-driver-2.0.1.jar:na]
	... 17 common frames omitted
Caused by: com.allanbank.mongodb.error.ReplyException: auth failed
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:197) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:216) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:141) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.asError(AbstractValidatingReplyCallback.java:112) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.checkForError(AbstractValidatingReplyCallback.java:244) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.verify(AbstractValidatingReplyCallback.java:298) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.callback(AbstractValidatingReplyCallback.java:90) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.AbstractValidatingReplyCallback.callback(AbstractValidatingReplyCallback.java:51) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.ReplyHandler.run(ReplyHandler.java:127) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.callback.ReplyHandler.reply(ReplyHandler.java:96) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.reply(AbstractSocketConnection.java:632) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.AbstractSocketConnection.doReceiveOne(AbstractSocketConnection.java:509) ~[mongodb-async-driver-2.0.1.jar:na]
	at com.allanbank.mongodb.client.connection.socket.ReceiveRunnable.run(ReceiveRunnable.java:59) ~[mongodb-async-driver-2.0.1.jar:na]
	... 1 common frames omitted

```

**Comment by bertramlau** [comment]
@lzbgt try     bin/ycsb load mongodb -p mongodb.url=mongodb://ycsb:ycsb@192.168.50.136/ycsb?w=1 -s -P workloads/workloada
