### ISSUE TITLE
My tests do not show results, I'm doing the right way?

### ISSUE THREAD

**Issue by maxwellazevedo** [brianfrankcooper/YCSB#816]
example running and output:

```
/ycsb-0.10.0$ bin/ycsb load cassandra-10 -P workloads/workloada
[WARN]  The 'cassandra-7', 'cassandra-8', 'cassandra-10', and cassandra-cql' clients are deprecated. If you are using Cassandra 2.X try using the 'cassandra2-cql' client instead.
java -cp /home/max/ycsb-0.10.0/cassandra-binding/conf:/home/max/ycsb-0.10.0/conf:/home/max/ycsb-0.10.0/lib/jackson-mapper-asl-1.9.4.jar:/home/max/ycsb-0.10.0/lib/HdrHistogram-2.1.4.jar:/home/max/ycsb-0.10.0/lib/htrace-core4-4.1.0-incubating.jar:/home/max/ycsb-0.10.0/lib/core-0.10.0.jar:/home/max/ycsb-0.10.0/lib/jackson-core-asl-1.9.4.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/antlr-runtime-3.2.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/stringtemplate-3.2.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/slf4j-api-1.6.4.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/snakeyaml-1.6.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/httpclient-4.0.1.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/jackson-core-asl-1.9.2.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/metrics-core-2.0.3.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/jamm-0.2.5.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/jetty-util-6.1.22.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/cassandra-thrift-1.2.9.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/slf4j-log4j12-1.7.2.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/compress-lzf-0.8.4.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/jetty-6.1.22.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/snaptree-0.1.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/jackson-mapper-asl-1.9.2.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/log4j-1.2.16.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/cassandra-all-1.2.9.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/httpcore-4.0.1.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/commons-codec-1.2.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/cassandra-binding-0.10.0.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/jbcrypt-0.3m.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/json-simple-1.1.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/libthrift-0.7.0.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/servlet-api-2.5.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/antlr-2.7.7.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/commons-logging-1.1.1.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/antlr-3.2.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/servlet-api-2.5-20081211.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/lz4-1.1.0.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/cassandra-driver-core-1.0.3.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/avro-1.4.0-cassandra-1.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/guava-13.0.1.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/concurrentlinkedhashmap-lru-1.3.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/high-scale-lib-1.1.2.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/netty-3.5.9.Final.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/jline-1.0.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/commons-cli-1.1.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/snappy-java-1.0.5.jar:/home/max/ycsb-0.10.0/cassandra-binding/lib/commons-lang-2.6.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraClient10 -P workloads/workloada -load
YCSB Client 0.10.0
Command line: -db com.yahoo.ycsb.db.CassandraClient10 -P workloads/workloada -load
Loading workload...
log4j:WARN No appenders could be found for logger (org.apache.htrace.core.Tracer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test.
com.yahoo.ycsb.DBException: Required property "hosts" missing for CassandraClient
	at com.yahoo.ycsb.db.CassandraClient10.init(CassandraClient10.java:128)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:99)
	at com.yahoo.ycsb.ClientThread.run(Client.java:418)
	at java.lang.Thread.run(Thread.java:745)
com.yahoo.ycsb.DBException: Required property "hosts" missing for CassandraClient
	at com.yahoo.ycsb.db.CassandraClient10.init(CassandraClient10.java:128)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:99)
	at com.yahoo.ycsb.ClientThread.run(Client.java:418)
	at java.lang.Thread.run(Thread.java:745)
[OVERALL], RunTime(ms), 6.0
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_MarkSweepCompact], Count, 0.0
[TOTAL_GC_TIME_MarkSweepCompact], Time(ms), 0.0
[TOTAL_GC_TIME_%_MarkSweepCompact], Time(%), 0.0
[TOTAL_GCS_Copy], Count, 0.0
[TOTAL_GC_TIME_Copy], Time(ms), 0.0
[TOTAL_GC_TIME_%_Copy], Time(%), 0.0
[TOTAL_GCs], Count, 0.0
[TOTAL_GC_TIME], Time(ms), 0.0
[TOTAL_GC_TIME_%], Time(%), 0.0
```

**Comment by busbey** [comment]
The error messages that look like this:

```
com.yahoo.ycsb.DBException: Required property "hosts" missing for CassandraClient
```

means you aren't getting to the point of talking to Cassandra. Please see [the README for the cassandra binding](https://github.com/brianfrankcooper/YCSB/tree/0.10.0/cassandra) for details on specifying the Cassandra cluster hosts.

Also note that if you are using a modern version of Cassandra, you should probably be using the 'cassandra2-cql' binding.

**Comment by maxwellazevedo** [comment]
I'm using cassandra 2 and I'm using a VM in Azure with docker, I could not change the "hosts" within the container.

**Comment by busbey** [comment]
By "hosts" I mean the addressable name of where the Cassandra instance is. If you're running both Cassandra and YCSB within the same container, I'd expect the value "localhost" to work.

**Comment by maxwellazevedo** [comment]
Yes, I managed using the command (-p --hosts "localhost"), but the error actually occurred because the doors had to be routed to the right place, managed to do that.
Thank you very much.
