### ISSUE TITLE
Authentication  failure with cassandra2 binding

### ISSUE THREAD

**Issue by shridharr** [brianfrankcooper/YCSB#817]
I am relatively new to Cassandra. This issue may be related to cassandra db configuration or issue with YCSB, not sure, but I can take some help/guidance here.

What I am trying to do some Load/Performance tests on a cassandra database using tool YCSB. I have YCSB tool installed on a remote machine, node-01 and my cassandra is on IP: 1.2.3.4. and I was able to connect to Cassandra database instance remotely from my node-01 machine using both cqlsh and cassandra-cli.

```
[root@node-01 ycsb-0.10.0]# cassandra-cli -host 1.2.3.4 -port 9160 -username cassandra -password cassandra -keyspace usertable 
InvalidRequestException(why:unconfigured table schema_columnfamilies) 
Welcome to Cassandra CLI version 1.2.19

Type 'help;' or '?' for help. 
Type 'quit;' or 'exit;' to quit.

[cassandra@usertable]
```

```
[root@node-01 ycsb-0.10.0]# cqlsh 1.2.3.4 -u cassandra -p cassandra 
Connected to 679ddd19-8bc8-43c7-921a-6d138d4c7a25 at 1.2.3.4:9160. 
[cqlsh 3.1.8 | Cassandra 3.0.8 | CQL spec 3.0.5 | Thrift protocol 20.1.0] 
Use HELP for help. 
cqlsh> 
cqlsh> 
cqlsh> list users ;

name | super 
-----------+------- 
TEST1 | True 
cassandra | True 
os_admin | True 
user | False

cqlsh> 
cqlsh> exit 
```

But when I try to run YCSB workload, i am getting an error as ->

```
[root@node-01 ycsb-0.10.0]# ./bin/ycsb load cassandra2-cql -p hosts="1.2.3.4" -P workloads/workloada -s > workloada_load_res.txt 
java -cp /usr/ycsb-0.10.0/cassandra2-binding/conf:/usr/ycsb-0.10.0/conf:/usr/ycsb-0.10.0/lib/core-0.10.0.jar:/usr/ycsb-0.10.0/lib/htrace-core4-4.1.0-incubating.jar:/usr/ycsb-0.10.0/lib/jackson-mapper-asl-1.9.4.jar:/usr/ycsb-0.10.0/lib/jackson-core-asl-1.9.4.jar:/usr/ycsb-0.10.0/lib/HdrHistogram-2.1.4.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/cassandra-driver-core-3.0.0.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/guava-16.0.1.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/metrics-core-3.1.2.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/netty-buffer-4.0.33.Final.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/netty-codec-4.0.33.Final.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/netty-common-4.0.33.Final.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/netty-handler-4.0.33.Final.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/netty-transport-4.0.33.Final.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/slf4j-api-1.6.4.jar:/usr/ycsb-0.10.0/cassandra2-binding/lib/cassandra2-binding-0.10.0.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=1.2.3.4 -P workloads/workloada -s -load 
YCSB Client 0.10.0 
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -p hosts=1.2.3.4 -P workloads/workloada -s -load 
Loading workload... 
Starting test. 
2016-07-31 19:24:04:689 0 sec: 0 operations; est completion in 0 seconds 
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /1.2.3.4:9042: Host /1.2.3.4:9042 requires authentication, but no authenticator found in Cluster configuration 
at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:193) 
at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:99) 
at com.yahoo.ycsb.ClientThread.run(Client.java:418) 
at java.lang.Thread.run(Thread.java:745) 
Caused by: com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /1.2.3.4:9042: Host /1.2.3.4:9042 requires authentication, but no authenticator found in Cluster configuration
```

**Comment by busbey** [comment]
Please check [the Cassandra2 binding's README for connection properties](https://github.com/brianfrankcooper/YCSB/tree/0.10.0/cassandra2#cassandra-configuration-parameters). It doesn't look like you're passing in either of `cassandra.username` or `cassandra.password` for the YCSB command line.

**Comment by risdenk** [comment]
@shridharr Were you able to resolve your issue based on what @busbey said?

**Comment by risdenk** [comment]
Closing due to no update.
