### ISSUE TITLE
ycsb cannot handle 1.00E+010 rows

### ISSUE THREAD

**Issue by madrob** [brianfrankcooper/YCSB#824]
When attempting to run with recordcount=10000000000 I get the following error:

```
Exception in thread "main" java.lang.NumberFormatException: For input string: "10000000000"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:495)
    at java.lang.Integer.parseInt(Integer.java:527)
    at com.yahoo.ycsb.workloads.CoreWorkload.init(CoreWorkload.java:399)
    at com.yahoo.ycsb.Client.main(Client.java:1016)

```

**Comment by busbey** [comment]
probably duplicate of #664, #764, #126, and/or #432?

**Comment by madrob** [comment]
Sure looks like it, thanks. Reading through them, I can't tell what version they are fixed in, if any.

**Comment by busbey** [comment]
oh no, not fixed in any version so far as I know. The closest was #432 I think.

Can you work around for now by splitting the works amongst enough client instances to keep the work for any one of them below MAX_INT? that'll mean inserting duplicates, but depending on your use case that might be okay?

**Comment by madrob** [comment]
Yea, I think I can make that work by using 5 clients with 2e9 operations each, and pointing them at different tables.

**Comment by risdenk** [comment]
Closing as duplicate.
