### ISSUE TITLE
Getting Exception - java.io.IOException: No FileSystem for scheme: hdfs

### ISSUE THREAD

**Issue by Manoj-Gandikota** [brianfrankcooper/YCSB#860]
Hi,

I am using the below command to start ycsb benchmarking.

`ycsb load habse10 -s -P /usr/share/ycsb/workloads/workloada -p recordcount=100000 -p operationcount=100000 -threads 1 -target 2000 -p columnfamily=cf `

I am getting the below exception while running the above command. 

`16/10/06 23:30:54 WARN util.DynamicClassLoader: Failed to identify the fs of dir hdfs://node1:8020/hbase/lib, ignored
java.io.IOException: No FileSystem for scheme: hdfs
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2579)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2586)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:89)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2625)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2607)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:368)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:296)
        at org.apache.hadoop.hbase.util.DynamicClassLoader.<init>(DynamicClassLoader.java:104)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.<clinit>(ProtobufUtil.java:232)
        at org.apache.hadoop.hbase.ClusterId.parseFrom(ClusterId.java:64)
        at org.apache.hadoop.hbase.zookeeper.ZKClusterId.readClusterIdZNode(ZKClusterId.java:75)
        at org.apache.hadoop.hbase.client.ZooKeeperRegistry.getClusterId(ZooKeeperRegistry.java:86)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.retrieveClusterId(ConnectionManager.java:833)
        at org.apache.hadoop.hbase.client.ConnectionManager$HConnectionImplementation.<init>(ConnectionManager.java:623)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218)
        at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119)
        at com.yahoo.ycsb.db.HBaseClient10.init(HBaseClient10.java:149)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:99)
        at com.yahoo.ycsb.ClientThread.run(Client.java:418)
        at java.lang.Thread.run(Thread.java:745)
DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
`
I checked in another post and found that I have to set the log level of "`org.apache.hadoop.hbase.util.DynamicClassLoader`" to ERROR. I did that, but it still throws the exeception. Please let me know how can I get rid of this exception?

Thanks

**Comment by busbey** [comment]
It's a warning from the HBase client that you can ignore. If you want to avoid it being printed you'll need to configure your log4j settings on the client side.

**Comment by busbey** [comment]
The UI you posted a screenshot of changes the log level on the server side. the message you're getting is from the client that is used within YCSB. To change it you'll need to change the configuration of the log4j settings within your invocation of YCSB.

For example, presuming a user named "busbey" with a home directory in "/home/busbey" and a file "/home/busbey/ycsb_log4j.properties" that contains:

```
log4j.logger.org.apache.hadoop.hbase.util.DynamicClassLoader=ERROR
```

Then you can alter your given cli invocation to include it like this:

```bash
ycsb load habse10 -jvm-args "-Dlog4j.configuration=/home/busbey/ycsb_log4j.properties" -s -P /usr/share/ycsb/workloads/workloada -p recordcount=100000 -p operationcount=100000 -threads 1 -target 2000 -p columnfamily=cf
```

**Comment by Manoj-Gandikota** [comment]
@busbey , Thanks for your reply. I was using Cloudera Distribution of Hadoop (CDH 5.8.0). So, I have edited the log4j.properties file in the path "/opt/cloudera/parcels/CLABS_YCSB-0.9.0-1.clabs_ycsb1.5.0.p0.1/lib/ycsb/hbase10-binding/conf/log4j.properties" and ran ycsb load command without giving the option "-jvm-args" . 
This time I did not get the exception. 
Thanks for your help.

**Comment by bosaidong** [comment]
No FileSystem for scheme: hdfs  
is a execption caused by mvn dependency problem as described in  https://stackoverflow.com/questions/17265002/hadoop-no-filesystem-for-scheme-file

so , may be we can specify  hadoop config , in hdfs-site.xml 

for YCSB 

but as others mentioned , it's a WARN not an error , we clound just ignore it by log4j config
