### ISSUE TITLE
Cannot run with Couchbase

### ISSUE THREAD

**Issue by kyungmi** [brianfrankcooper/YCSB#878]
Hi.
I have some problems while benchmarking Couchbase.

I use
- Couchbase 4.1.1 (Coummunity), clustered (4 nodes)
- 1 client(macOS) for test
- Replication factor is 2 for default bucket.
- uses default workloada file

First, I made 10,000,000 records in the Couchbase cluster with below command.

```
./bin/ycsb load couchbase2 -P workloads/workloada -p recordcount=10000000 -p couchbase.host=x.x.x.x -p couchbase.persistTo=1 -p couchbase.replicateTo=2 -s -threads 32 -target 10000 > results/couchbase/load-test.txt
```

Then I run below test on these records.
```
./bin/ycsb run couchbase2 -P workloads/workloada -p operationcount=1000000 -p couchbase.host=x.x.x.x -p couchbase.persistTo=1 -p couchbase.replicateTo=2 -s -threads 32 > results/couchbase/run-test-a-t32.txt
```

Unfortunately I encountered a lot of errors while testing.

```
com.couchbase.client.java.error.DurabilityException: Durability requirement failed: The CAS on the active node changed for ID "usertable:user8457711521909979413", indicating it has been modified in the meantime.
	at com.couchbase.client.java.CouchbaseAsyncBucket$21$1.call(CouchbaseAsyncBucket.java:647)
	at com.couchbase.client.java.CouchbaseAsyncBucket$21$1.call(CouchbaseAsyncBucket.java:643)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:139)
	at rx.internal.operators.OperatorMap$MapSubscriber.onError(OperatorMap.java:85)
	at rx.internal.operators.OperatorMap$MapSubscriber.onError(OperatorMap.java:85)
	at rx.internal.operators.OperatorTake$1.onError(OperatorTake.java:65)
	at rx.internal.operators.OperatorSkipWhile$1.onError(OperatorSkipWhile.java:62)
	at rx.internal.operators.OnSubscribeRedo$4$1.onError(OnSubscribeRedo.java:331)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:266)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:810)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:571)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:276)
	at rx.internal.operators.OperatorMap$MapSubscriber.onError(OperatorMap.java:85)
	at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onError(OperatorZip.java:325)
	at rx.internal.operators.OperatorMap$MapSubscriber.onError(OperatorMap.java:85)
	at rx.internal.operators.OnSubscribeRedo$3$1.onNext(OnSubscribeRedo.java:305)
	at rx.internal.operators.OnSubscribeRedo$3$1.onNext(OnSubscribeRedo.java:289)
	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.emitNext(SubjectSubscriptionManager.java:253)
	at rx.subjects.BehaviorSubject.onNext(BehaviorSubject.java:160)
	at rx.internal.operators.OnSubscribeRedo$2$1.onError(OnSubscribeRedo.java:242)
	at rx.internal.operators.OperatorScan$InitialProducer.checkTerminated(OperatorScan.java:212)
	at rx.internal.operators.OperatorScan$InitialProducer.emitLoop(OperatorScan.java:309)
	at rx.internal.operators.OperatorScan$InitialProducer.emit(OperatorScan.java:295)
	at rx.internal.operators.OperatorScan$InitialProducer.onError(OperatorScan.java:227)
	at rx.internal.operators.OperatorScan$3.onError(OperatorScan.java:149)
	at rx.internal.operators.OperatorMap$MapSubscriber.onError(OperatorMap.java:85)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:70)
	at rx.observers.Subscribers$5.onNext(Subscribers.java:229)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:391)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:353)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:838)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitScalar(OperatorMerge.java:391)
	at rx.internal.operators.OperatorMerge$MergeSubscriber.tryEmit(OperatorMerge.java:353)
	at rx.internal.operators.OperatorMerge$InnerSubscriber.onNext(OperatorMerge.java:838)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:153)
	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
	at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
	at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.setProducer(OperatorOnErrorResumeNextViaFunction.java:158)
	at rx.subjects.AsyncSubject.onCompleted(AsyncSubject.java:105)
	at com.couchbase.client.core.endpoint.AbstractGenericHandler.completeResponse(AbstractGenericHandler.java:348)
	at com.couchbase.client.core.endpoint.AbstractGenericHandler.publishResponse(AbstractGenericHandler.java:331)
	at com.couchbase.client.core.endpoint.AbstractGenericHandler.decode(AbstractGenericHandler.java:231)
	at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81)
	at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
	at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at com.couchbase.client.deps.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at com.couchbase.client.deps.io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
	at com.couchbase.client.deps.io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
	at com.couchbase.client.deps.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
	at com.couchbase.client.deps.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at com.couchbase.client.deps.io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at com.couchbase.client.deps.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at com.couchbase.client.deps.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	at com.couchbase.client.deps.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528)
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
	at com.couchbase.client.deps.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
	at com.couchbase.client.deps.io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at com.couchbase.client.deps.io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.couchbase.client.core.DocumentConcurrentlyModifiedException: The CAS on the active node changed for ID "usertable:user8457711521909979413", indicating it has been modified in the meantime.
	at com.couchbase.client.core.message.observe.ObserveViaCAS$ObserveItem.<init>(ObserveViaCAS.java:232)
	at com.couchbase.client.core.message.observe.ObserveViaCAS$5.call(ObserveViaCAS.java:71)
	at com.couchbase.client.core.message.observe.ObserveViaCAS$5.call(ObserveViaCAS.java:68)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:66)
	... 41 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.couchbase.client.core.message.kv.ObserveResponse.class
	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
	at rx.internal.operators.OperatorMap$MapSubscriber.onNext(OperatorMap.java:70)
	... 41 more

```

What is the real problem? Help me please.

**Comment by kyungmi** [comment]
Hmm... I resolved this issue with removing the options `-p couchbase.persistTo=1 -p couchbase.replicateTo=2` from `run` command.
Is that all right?
