### ISSUE TITLE
Mapkeeper test bug,  org.apache.thrift.transport.TTransportException: Frame size (348470237) larger than max length (16384000)

### ISSUE THREAD

**Issue by CaixinGong** [brianfrankcooper/YCSB#892]
After I followed #885, I build mapkeeper on  YCSB-0.4.0 successfully.
I defined a new workload which try to scan 0-1000,000 records each time.  Each record size is 1000 bytes. I found a bug  when I run a new workload  and the bug is as follows:
**org.apache.thrift.transport.TTransportException: Frame size (348470237) larger than max length (16384000)!**
        at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:137)
        at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:297)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:204)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
        at com.yahoo.mapkeeper.MapKeeper$Client.recv_scan(MapKeeper.java:381)
        at com.yahoo.mapkeeper.MapKeeper$Client.scan(MapKeeper.java:361)
        at com.yahoo.ycsb.db.MapKeeperClient.scan(MapKeeperClient.java:158)
        at com.yahoo.ycsb.DBWrapper.scan(DBWrapper.java:113)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:732)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:579)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)
**org.apache.thrift.transport.TTransportException: Read a negative frame size (-2147418110)!**
        at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:133)
        at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
        at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
        at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378)
        at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:297)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:204)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
        at com.yahoo.mapkeeper.MapKeeper$Client.recv_scan(MapKeeper.java:381)
        at com.yahoo.mapkeeper.MapKeeper$Client.scan(MapKeeper.java:361)
        at com.yahoo.ycsb.db.MapKeeperClient.scan(MapKeeperClient.java:158)
        at com.yahoo.ycsb.DBWrapper.scan(DBWrapper.java:113)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:732)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:579)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)
**Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space**
        at org.apache.thrift.protocol.TBinaryProtocol.readStringBody(TBinaryProtocol.java:353)
        at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:215)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
        at com.yahoo.mapkeeper.MapKeeper$Client.recv_scan(MapKeeper.java:381)
        at com.yahoo.mapkeeper.MapKeeper$Client.scan(MapKeeper.java:361)
        at com.yahoo.ycsb.db.MapKeeperClient.scan(MapKeeperClient.java:158)
        at com.yahoo.ycsb.DBWrapper.scan(DBWrapper.java:113)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransactionScan(CoreWorkload.java:732)
        at com.yahoo.ycsb.workloads.CoreWorkload.doTransaction(CoreWorkload.java:579)
        at com.yahoo.ycsb.ClientThread.run(Client.java:329)

I can successfully run workload**e** which scan 0-100 records each time . How can I fix this bug?
**ps:** 
I fixed another bug of mapkeeper to support the scan operation, the original mapkeeper can only scan one record, I change the line 207 and 243 of mapkeeper/leveldb/LevelDbServer.cpp
` if (_return.records.size() >= (uint32_t)maxRecords || numBytes >= maxBytes)`
to 
`if (_return.records.size() >= (uint32_t)maxRecords)`
because the maxBytes is always 0, which make the scan operation can only read one record.

**Comment by risdenk** [comment]
You mentioned that this modified LevelDbServer.cpp which isn't in this project. I don't think this is related to YCSB.
