### ISSUE TITLE
Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (validate) on project mapkeeper-binding: You have 2 Checkstyle violations.

### ISSUE THREAD

**Issue by shingjan** [brianfrankcooper/YCSB#953]
I was trying to use YCSB with MapKeeper module to test LevelDB  and tried this first:
https://github.com/m1ch1/mapkeeper/wiki/Getting-Started
and of course, this didn't work very well without the binding between Mapkeeper and YCSB. Then I found issues like 181 and 260, then got the solution here:
https://github.com/brianfrankcooper/YCSB/pull/262
but it turns out that there are two Check Validations while I try to call "mvn clean package" under the directory "mapkeeper/ycsb/YCSB", the full logs are here:

-------------------------------------------------------------------
```
Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (validate) on project mapkeeper-binding: You have 2 Checkstyle violations. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.16:check (validate) on project mapkeeper-binding: You have 2 Checkstyle violations.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: You have 2 Checkstyle violations.
	at org.apache.maven.plugin.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:588)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :mapkeeper-binding
```
-----------------------------------------------
And in issue https://github.com/brianfrankcooper/YCSB/issues/885, it seems that CaixinGong has solved the problem by re-install a YCSB with other version. I am using the current YCSB on Github so wondering how to get rid of these two Check Validations on maven and make YCSB & MapKeeper work on testing LevelDB? Any kind of help or suggestion would be appreciated!

**Comment by risdenk** [comment]
#267 started enforcing checkstyle. The mapkeeper binding hasn't been kept up to date due to not being published in maven. The maven output will describe what the two checkstyle errors are. They could be line length or other things.

**Comment by busbey** [comment]
closing as stale. if you'd like more assistance please reopen.
