### ISSUE TITLE
YCSB run giving DBexception for couchbase2 

### ISSUE THREAD

**Issue by meghalidhoble** [brianfrankcooper/YCSB#955]
I am trying to run the workload tests for couchbase2 database with YCSB as I have a installed couchbase 4.5.0 version on my machine. However during the run it's showing me DBException as below;

com.yahoo.ycsb.DBException: Could not connect to Couchbase Bucket.
        at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:208)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:99)
        at com.yahoo.ycsb.ClientThread.run(Client.java:418)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException
        at com.couchbase.client.java.util.Blocking.blockForSingle(Blocking.java:71)
        at com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:290)
        at com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:271)
        at com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:260)
        at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:205)
        ... 3 more
Caused by: java.util.concurrent.TimeoutException

And the throughput is seen as 0.0 at the end result. 

[OVERALL], RunTime(ms), 30261.0
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 1.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 7.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.023132084200786492
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 1.0
[TOTAL_GC_TIME], Time(ms), 7.0
[TOTAL_GC_TIME_%], Time(%), 0.023132084200786492

Has anyone seen this kind of logs before? Any pointers would really help. 
Thanks.

**Comment by dineiar** [comment]
Are you testing against Couchbase Community or Enterprise?

How many threads have you used? Try using a single thread and see if the problem persists.

Can you post the workload and the command line you ran?

The Community edition has limited support for concurrency and parallelism:

> **High Performance Concurrent Query Execution**: Couchbase Server query service achieves great query throughput and query latency by taking advantage of large number of queries concurrently and by parallelizing query execution across multiple cores. Only Enterprise Edition comes with full parallelism and concurrency support. Community edition can only be deployed in homogeneous deploy model and comes with limited concurrency and parallelism (max parallelism can be 4) on each node.

Source: [Couchbase Blog](https://blog.couchbase.com/couchbase-server-editions-explained-open-source-community-edition-and-enterprise-edition/)

**Comment by busbey** [comment]
Any luck trying out the suggestions above?

**Comment by dhoblem** [comment]
@dineiar , Thanks for your reply and suggestions and very sorry for the delayed response on this.  Somehow I missed to respond to this.
To answer the command line and workload related question above, I used the below command with 'workloada' available under the workloads folder.
     $ bin/ycsb load couchbase2 -s -P workloads/workloada

Though I couldn't try all of the above suggestions, I was able to resolve the "Could not connect to Couchbase Bucket." error by using the default bucket configurations by exploring the couchbaseMock setup. 
Thanks @busbey , for checking with me and reminding me regarding this thread discussion.

**Comment by dsukhoroslov** [comment]
looks like a duplicate for #1062 
was anyone able to connect to couchbase server when it is installed not on localhost?

**Comment by dsukhoroslov** [comment]
I have the same issue with Couchbase server 5.0.1-5003, Community Edition. The server is installed in my local network on SLES11. When installing cluster I set server IP address to my host address: 192.168.1.139 and added 'default' basket and user. Then I trying to load the backet from YCSB test. Workload A params:
couchbase.host=192.168.1.139
couchbase.bucket=default
couchbase.password=default

but the client just cannot connect to the server, the test output is:
```
Command line: -load -db com.yahoo.ycsb.db.couchbase2.Couchbase2Client -s -P workloads/workloadaYCSB Client 0.14.0-SNAPSHOT

Loading workload...
Starting test.
2018-02-14 00:05:45:417 0 sec: 0 operations; est completion in 0 second
Feb 14, 2018 12:05:45 AM com.yahoo.ycsb.db.couchbase2.Couchbase2Client logParams
INFO: ===> Using Params: host=192.168.1.139, bucket=default, upsert=false, persistTo=NONE, replicateTo=NONE, syncMutResponse=true, adhoc=false, kv=true, maxParallelism=1, queryEndpoints=1, kvEndpoints=1, queryEndpoints=1, epoll=false, boost=3, networkMetricsInterval=0, runtimeMetricsInterval=0
Feb 14, 2018 12:05:45 AM com.couchbase.client.core.CouchbaseCore <init>
INFO: CouchbaseEnvironment: {sslEnabled=false, sslKeystoreFile='null', sslKeystorePassword=false, sslKeystore=null, bootstrapHttpEnabled=true, bootstrapCarrierEnabled=true, bootstrapHttpDirectPort=8091, bootstrapHttpSslPort=18091, bootstrapCarrierDirectPort=11210, bootstrapCarrierSslPort=11207, ioPoolSize=8, computationPoolSize=8, responseBufferSize=16384, requestBufferSize=16384, kvServiceEndpoints=1, viewServiceEndpoints=1, queryServiceEndpoints=1, searchServiceEndpoints=1, ioPool=NioEventLoopGroup, coreScheduler=CoreScheduler, eventBus=DefaultEventBus, packageNameAndVersion=couchbase-java-client/2.3.1 (git: 2.3.1, core: 1.3.1), dcpEnabled=false, retryStrategy=BestEffort, maxRequestLifetime=75000, retryDelay=ExponentialDelay{growBy 1.0 MICROSECONDS, powers of 2; lower=100, upper=100000}, reconnectDelay=ExponentialDelay{growBy 1.0 MILLISECONDS, powers of 2; lower=32, upper=4096}, observeIntervalDelay=ExponentialDelay{growBy 1.0 MICROSECONDS, powers of 2; lower=10, upper=100000}, keepAliveInterval=30000, autoreleaseAfter=2000, bufferPoolingEnabled=true, tcpNodelayEnabled=true, mutationTokensEnabled=false, socketConnectTimeout=10000, dcpConnectionBufferSize=20971520, dcpConnectionBufferAckThreshold=0.2, dcpConnectionName=dcp/core-io, callbacksOnIoPool=true, disconnectTimeout=25000, requestBufferWaitStrategy=com.couchbase.client.core.env.DefaultCoreEnvironment$2@8e5baa0, queryTimeout=75000, viewTimeou12:17 AM kvTimeout=10000, connectTimeout=30000, dnsSrvEnabled=false}
2018-02-14 00:05:55:398 10 sec: 0 operations; est completion in 106751991167300 days 15 hours
2018-02-14 00:06:05:398 20 sec: 0 operations; est completion in 106751991167300 days 15 hours
2018-02-14 00:06:15:398 30 sec: 0 operations; est completion in 106751991167300 days 15 hours
com.yahoo.ycsb.DBException: Could not connect to Couchbase Bucket.
        at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:208)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
        at com.yahoo.ycsb.ClientThread.run(Client.java:423)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException
        at com.couchbase.client.java.util.Blocking.blockForSingle(Blocking.java:71)
        at com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:290)
        at com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:271)
        at com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:260)
        at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:205)
        ... 3 more
Caused by: java.util.concurrent.TimeoutException
        ... 8 more
com.yahoo.ycsb.DBException: Could not connect to Couchbase Bucket.
        at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:208)
        at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:86)
        at com.yahoo.ycsb.ClientThread.run(Client.java:423)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.util.concurrent.TimeoutException
        at com.couchbase.client.java.util.Blocking.blockForSingle(Blocking.java:71)
        at com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:290)
        at com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:271)
        at com.couchbase.client.java.CouchbaseCluster.openBucket(CouchbaseCluster.java:260)
        at com.yahoo.ycsb.db.couchbase2.Couchbase2Client.init(Couchbase2Client.java:205)
        ... 3 more
Caused by: java.util.concurrent.TimeoutException
        ... 8 more
2018-02-14 00:06:15:918 30 sec: 0 operations; est completion in 106751991167300 days 15 hours
```
Any clue how to solve this?

Thanks, Denis

**Comment by dsukhoroslov** [comment]
Still have no solution for this. If I run the test from the same box where Couchbase server is installed then no issues at all. But when I run client from separate box, I got this TimeoutException.

Detailed log on the client side:
```
16:15:00.970 [Thread-3] DEBUG c.c.c.c.config.ConfigurationProvider - Setting seed hosts to [linbox.sdv.home/192.168.1.139]
16:15:00.980 [Thread-3] DEBUG c.c.c.c.config.ConfigurationProvider - Got instructed to open bucket default
16:15:00.980 [Thread-3] DEBUG c.c.client.core.config.loader.Loader - Loading Config for bucket default
16:15:00.980 [Thread-3] DEBUG c.c.client.core.config.loader.Loader - Loading Config for bucket default
16:15:00.990 [Thread-3] DEBUG c.c.client.core.RequestHandler - Got instructed to add Node linbox.sdv.home/192.168.1.139
16:15:00.990 [Thread-3] DEBUG c.c.client.core.RequestHandler - Connecting Node linbox.sdv.home/192.168.1.139
16:15:00.990 [Thread-3] DEBUG com.couchbase.client.core.node.Node - [linbox.sdv.home]: Got instructed to connect.
16:15:00.990 [Thread-3] DEBUG c.c.client.core.RequestHandler - Connect finished, registering for use.
16:15:00.990 [cb-computations-4] DEBUG c.c.client.core.config.loader.Loader - Successfully added Node linbox.sdv.home/192.168.1.139
16:15:01.000 [cb-computations-4] DEBUG c.c.client.core.RequestHandler - Got instructed to add Service BINARY, to Node linbox.sdv.home/192.168.1.139
16:15:01.000 [cb-computations-4] DEBUG com.couchbase.client.core.node.Node - [linbox.sdv.home]: Adding Service BINARY
16:15:01.000 [cb-computations-4] DEBUG com.couchbase.client.core.node.Node - [linbox.sdv.home]: Adding Service BINARY to registry and connecting it.
16:15:01.000 [cb-computations-4] DEBUG c.c.client.core.service.Service - [linbox.sdv.home][KeyValueService]: Got instructed to connect.
16:15:01.020 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 16
16:15:01.020 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 16
16:15:01.020 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
16:15:01.020 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
16:15:01.020 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
16:15:01.020 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
16:15:01.030 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
16:15:01.030 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
16:15:01.030 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
16:15:01.030 [cb-computations-4] DEBUG c.c.c.d.i.n.b.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
16:15:01.040 [cb-computations-4] DEBUG c.c.client.core.service.Service - [linbox.sdv.home][KeyValueService]: Initializing connect on Endpoint.
16:15:01.050 [cb-computations-4] DEBUG c.c.c.d.i.n.u.i.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0xf4fb68f2d8488026 (took 0 ms)
16:15:01.070 [cb-computations-4] DEBUG c.c.c.d.io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
16:15:01.070 [cb-computations-4] DEBUG c.c.c.d.io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
16:15:01.070 [cb-computations-4] DEBUG c.c.c.d.io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
2018-03-08 16:15:10:578 10 sec: 0 operations; est completion in 106751991167300 days 15 hours
16:15:10.948 [cb-computations-2] DEBUG c.c.c.c.config.ConfigurationProvider - Received signal for outdated configuration.
16:15:10.948 [cb-computations-2] DEBUG c.c.c.c.config.ConfigurationProvider - Ignoring outdated signal, since no buckets are open.
2018-03-08 16:15:20:577 20 sec: 0 operations; est completion in 106751991167300 days 15 hours
16:15:20.947 [cb-computations-2] DEBUG c.c.c.c.config.ConfigurationProvider - Received signal for outdated configuration.
16:15:20.947 [cb-computations-2] DEBUG c.c.c.c.config.ConfigurationProvider - Ignoring outdated signal, since no buckets are open.
...................
```
Loks like the client was able to connect, but cannot open the bucket. Does anyone know how to fix this?

Thanks, Denis

**Comment by dsukhoroslov** [comment]
solved this setting couchbase.boost=0

**Comment by busbey** [comment]
great to hear you solved your timeout issue. I'd love to know if someone has succeeded running from a remote client with boost set above 0.
