### ISSUE TITLE
unable to test HBase 1.2.5 with pseudo-distributed local install

### ISSUE THREAD

**Issue by zhichao-cao** [brianfrankcooper/YCSB#966]
I just begin to install and try HBase. 
**1. I download the stable version of HBase 1.2.5 tar and hadoop-2.7.3 tar** to install the HBase and HDFS in pseudo-distributed fashion. I followed the official instructions:
http://hbase.apache.org/book.html#ops.date.tiered.config
http://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html#Pseudo-Distributed_Operation

**2. The conf/hbase-site.xml is as:<configuration>**
  <property>
    <name>hbase.rootdir</name>
    <value>hdfs://localhost:9000/hbase</value>
  </property>
  <property>
    <name>hbase.zookeeper.property.dataDir</name>
    <value>/home/zhichao/zookeeper</value>
  </property>
  <property>
    <name>hbase.cluster.distributed</name>
    <value>true</value>
  </property>
  <property>
    <name>hbase.zookeeper.quorum</name>
    <value>localhost</value>
 </property>
</configuration>

**3. Next I download the YCSB.0.12.0 tar from the** 
https://github.com/brianfrankcooper/YCSB/releases/tag/0.12.0

**4. I copied all the jar files from hbase/lib/* to ycsb.0.12.0/hbase10-blinding/lib
and copied all the conf files from hbase/conf/* to ycsb.0.12.0/hbase10-blinding/conf.**

**5. Before testing, I created the table:**
create 'usertable', 'family', {SPLITS => (1..n_splits).map {|i| "user#{1000+i*(9999-1000)/n_splits}"}}

**6. Then run:**
./bin/ycsb load hbase -P workloads/workloada -cp hbase10-binding/conf -p table=usertable -p columnfamily=family -p recordcount=1000

**It seems that YCSB can not connect to the zookeeper or to the client. The logs are the following:**

Command line: -db com.yahoo.ycsb.db.HBaseClient10 -P workloads/workloada -p table=usertable -p columnfamily=family -p recordcount=1000 -load
Loading workload...
Starting test.
2017-05-08 23:16:40,413 WARN  [Thread-2] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2017-05-08 23:16:40,836 INFO  [Thread-2] zookeeper.RecoverableZooKeeper: Process identifier=hconnection-0x3ed6d0aa connecting to ZooKeeper ensemble=localhost:2181
2017-05-08 23:16:40,843 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2017-05-08 23:16:40,843 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:host.name=mist34-umh
2017-05-08 23:16:40,843 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:java.version=1.8.0_131
2017-05-08 23:16:40,843 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:java.vendor=Oracle Corporation
2017-05-08 23:16:40,843 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:java.home=/usr/lib/jvm/java-8-oracle/jre
2017-05-08 23:16:40,843 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:java.class.path=hbase10-binding/conf:/home/zhichao/ycsb-0.12.0/hbase10-binding/conf:/home/zhichao/ycsb-0.12.0/conf:/home/zhichao/ycsb-0.12.0/lib/jackson-core-asl-1.9.4.jar:/home/zhichao/ycsb-0.12.0/lib/jackson-mapper-asl-1.9.4.jar:/home/zhichao/ycsb-0.12.0/lib/htrace-core4-4.1.0-incubating.jar:/home/zhichao/ycsb-0.12.0/lib/HdrHistogram-2.1.4.jar:/home/zhichao/ycsb-0.12.0/lib/core-0.12.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-hadoop2-compat-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-collections-3.2.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jsp-api-2.1-6.1.14.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-annotations-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/htrace-core-3.1.0-incubating.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-el-1.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-protocol-1.0.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-logging-1.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/libthrift-0.9.3.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-it-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-client-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-prefix-tree-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-daemon-1.0.13.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-client-1.0.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/slf4j-log4j12-1.7.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-mapreduce-client-common-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/servlet-api-2.5-6.1.14.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-compress-1.4.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-beanutils-1.7.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jcodings-1.0.8.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-mapreduce-client-app-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-lang-2.6.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/xmlenc-0.52.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jackson-mapper-asl-1.9.13.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/slf4j-api-1.6.4.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-it-1.2.5-tests.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-net-3.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-yarn-api-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jruby-complete-1.6.8.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-server-1.2.5-tests.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/guice-3.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-yarn-server-common-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jamon-runtime-2.4.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/disruptor-3.3.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/guice-servlet-3.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-auth-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/servlet-api-2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/log4j-1.2.17.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/zookeeper-3.4.6.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-collections-3.2.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-common-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/joni-2.1.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-mapreduce-client-shuffle-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-yarn-common-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/paranamer-2.3.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jersey-core-1.9.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jackson-core-asl-1.9.4.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jsp-2.1-6.1.14.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jackson-core-asl-1.9.13.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-external-blockcache-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-protocol-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/apacheds-i18n-2.0.0-M15.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-yarn-client-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jersey-server-1.9.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-server-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-annotations-1.0.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jsr305-1.3.9.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jersey-guice-1.9.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-beanutils-core-1.8.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-math-2.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jets3t-0.9.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/spymemcached-2.11.6.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jasper-compiler-5.5.23.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-rest-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/protobuf-java-2.5.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/aopalliance-1.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-thrift-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-io-2.4.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/junit-4.12.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/asm-3.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/xz-1.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/snappy-java-1.0.4.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/netty-all-4.0.23.Final.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jetty-util-6.1.26.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/guava-12.0.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-procedure-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/stax-api-1.0-2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/slf4j-log4j12-1.7.7.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jackson-xc-1.9.13.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/httpclient-4.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jettison-1.3.3.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-shell-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jasper-runtime-5.5.23.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/apacheds-kerberos-codec-2.0.0-M15.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/leveldbjni-all-1.8.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-math3-3.1.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jersey-client-1.9.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jackson-jaxrs-1.9.13.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jaxb-impl-2.2.3-1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase10-binding-0.12.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/metrics-core-2.2.0.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-examples-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-common-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-cli-1.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-common-1.2.5-tests.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/javax.inject-1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/api-util-1.0.0-M20.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/avro-1.7.4.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/httpcore-4.4.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jackson-mapper-asl-1.8.8.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-mapreduce-client-core-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/java-xmlbuilder-0.4.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/slf4j-api-1.7.7.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/netty-3.6.2.Final.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-hadoop-compat-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jetty-sslengine-6.1.26.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-codec-1.9.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-digester-1.8.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-mapreduce-client-jobclient-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-annotations-1.2.5-tests.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/httpcore-4.2.4.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-client-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/activation-1.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-common-1.0.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jetty-6.1.26.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jersey-json-1.9.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jaxb-api-2.2.2.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hbase-resource-bundle-1.2.5.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-configuration-1.6.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/commons-httpclient-3.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-annotations-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/jsch-0.1.42.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/findbugs-annotations-1.3.9-1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/hadoop-hdfs-2.5.1.jar:/home/zhichao/ycsb-0.12.0/hbase10-binding/lib/api-asn1-api-1.0.0-M20.jar
2017-05-08 23:16:40,844 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2017-05-08 23:16:40,844 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:java.io.tmpdir=/tmp
2017-05-08 23:16:40,844 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:java.compiler=<NA>
2017-05-08 23:16:40,844 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:os.name=Linux
2017-05-08 23:16:40,844 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:os.arch=amd64
2017-05-08 23:16:40,844 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:os.version=3.19.0-25-generic
2017-05-08 23:16:40,844 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:user.name=root
2017-05-08 23:16:40,844 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:user.home=/root
2017-05-08 23:16:40,844 INFO  [Thread-2] zookeeper.ZooKeeper: Client environment:user.dir=/home/zhichao/ycsb-0.12.0
2017-05-08 23:16:40,845 INFO  [Thread-2] zookeeper.ZooKeeper: Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x3ed6d0aa0x0, quorum=localhost:2181, baseZNode=/hbase
2017-05-08 23:16:40,863 INFO  [Thread-2-SendThread(localhost:2181)] zookeeper.ClientCnxn: Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2017-05-08 23:16:40,872 INFO  [Thread-2-SendThread(localhost:2181)] zookeeper.ClientCnxn: Socket connection established to localhost/127.0.0.1:2181, initiating session
2017-05-08 23:16:40,881 INFO  [Thread-2-SendThread(localhost:2181)] zookeeper.ClientCnxn: Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x15bea14997f000b, negotiated timeout = 90000
2017-05-08 23:17:29,660 INFO  [Thread-2] client.RpcRetryingCaller: Call exception, tries=10, retries=35, started=48436 ms ago, cancelled=false, msg=
2017-05-08 23:17:49,736 INFO  [Thread-2] client.RpcRetryingCaller: Call exception, tries=11, retries=35, started=68512 ms ago, cancelled=false, msg=
2017-05-08 23:18:09,833 INFO  [Thread-2] client.RpcRetryingCaller: Call exception, tries=12, retries=35, started=88609 ms ago, cancelled=false, msg=

**If I only use the lib from HBase (remove the origian lib in the hbase10, and cp all the lib from hbase to the hbase10-blinding), the exceptions are:**
Command line: -db com.yahoo.ycsb.db.HBaseClient10 -P workloads/workloada -p table=usertable -p columnfamily=family -p recordcount=1000 -load
Loading workload...
Starting test.
java.lang.ClassNotFoundException: com.yahoo.ycsb.db.HBaseClient10
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.yahoo.ycsb.DBFactory.newDB(DBFactory.java:37)
	at com.yahoo.ycsb.Client.main(Client.java:1058)
Exception in thread "Thread-1" java.lang.NullPointerException
	at com.yahoo.ycsb.ClientThread.run(Client.java:418)
	at java.lang.Thread.run(Thread.java:748)
[OVERALL], RunTime(ms), 1.0
[OVERALL], Throughput(ops/sec), 0.0
[TOTAL_GCS_PS_Scavenge], Count, 0.0
[TOTAL_GC_TIME_PS_Scavenge], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_Scavenge], Time(%), 0.0
[TOTAL_GCS_PS_MarkSweep], Count, 0.0
[TOTAL_GC_TIME_PS_MarkSweep], Time(ms), 0.0
[TOTAL_GC_TIME_%_PS_MarkSweep], Time(%), 0.0
[TOTAL_GCs], Count, 0.0
[TOTAL_GC_TIME], Time(ms), 0.0
[TOTAL_GC_TIME_%], Time(%), 0.0

**What's the problem? Did I miss some steps to setup YCSB?**

**Comment by busbey** [comment]
You shouldn't need to alter the library files that come in the YCSB install to test against an HBase cluster. You also shouldn't need to copy the hbase configuration files at all.

[The README on the hbase098 binding|https://github.com/brianfrankcooper/YCSB/tree/master/hbase098] should work for the hbase10 binding as well. Essentially, you want to point YCSB's classpath to your HBase conf directory. The example given in the README  is something like `-cp /HBASE-HOME-DIR/conf` in a common cluster deploy this would be something like `-cp /etc/hbase/conf`. On the install on my laptop it's `-cp /Users/busbey/hbase-conf-dir`.

It looks like you have the correct root cause, YCSB can't talk to ZK. Does connecting with the hbase shell work? Does connecting directly to ZK on `localhost:2181` work with the zookeeper client?

**Comment by busbey** [comment]
Have you had a chance to check the things I mentioned, @zhichao-cao ?

**Comment by zhichao-cao** [comment]
Hi @busbey 

Thanks for your suggestions. The problem is caused by copying the library files to the YCSB blinding. I followed your instructions and it works now. In the local installation, YCSB is able to connect to ZK on localhost:2891. 

Thanks again!

Zhichao

**Comment by busbey** [comment]
glad it worked out!

**Comment by zhichao-cao** [comment]
Sorry for the late reply.

Thanks again!

Zhichao
